In [1]:
import warnings
from IPython.core.interactiveshell import InteractiveShell
from IPython.display import display, Markdown, HTML, Javascript
from tqdm import tqdm


def alert(message='Loop completed!'):
    # Check if the system supports 'say' and notifications
    os.system(f'osascript -e \'display notification "{message}" with title "Notification"\'')
    # Speak the alert
    os.system(f'say "{message}"')        
        
InteractiveShell.ast_node_interactivity = "all"
warnings.filterwarnings("ignore")
tqdm.pandas()

In [2]:
import geopandas as gpd
import pandas as pd

In [29]:
area_df = gpd.read_file('data/raw/areas.shp')
area_df['latlng'] = area_df.lookup_lat.fillna(area_df.center_lat).apply(eval)
area_df = area_df.rename(columns={'intersecti': 'intersection_id'})
# we first chopped it to test area_df = area_df.head()

In [49]:
print(area_df.tail(10))

       intersection_id    zip county district  population          state  \
60158            65430  25674  Wayne       01      1771.0  West Virginia
60159            65431  25524  Wayne       01      2786.0  West Virginia
60160            65432  25530  Wayne       05      6665.0  West Virginia
60161            65434  25530  Wayne       01      6665.0  West Virginia
60162            65435  25535  Wayne       01      2991.0  West Virginia
60163            65436  25555  Wayne       05      2518.0  West Virginia
60164            65437  25555  Wayne       01      2518.0  West Virginia
60165            65438  25570  Wayne       01      4887.0  West Virginia
60166            65439  25699  Wayne       01       606.0  West Virginia
60167            65440  25701  Wayne       01     21375.0  West Virginia

      state_id                                center_lat  \
60158       WV   (37.89816159256202, -82.38922280324576)
60159       WV   (38.03135364993199, -82.22660019732452)
60160       WV   (38.39304271335658, -82.59620755035604)
60161       WV   (38.35554960401771, -82.56254502126755)
60162       WV   (38.30774199020909, -82.43405688875309)
60163       WV  (38.232440634728874, -82.59977435647347)
60164       WV  (38.235627259720516, -82.55517447787659)
60165       WV   (38.23506484691762, -82.41931113076365)
60166       WV   (37.96168427102013, -82.33255384878288)
60167       WV   (38.354640706117934, -82.4457980499672)

                                     lookup_lat    best_width  \
60158   (37.89816159256202, -82.38922280324576)   4043.273545
60159   (38.03135364993199, -82.22660019732452)   2407.805553
60160   (38.39304271335658, -82.59620755035604)    342.608780
60161                     (38.34969, -82.50693)   3815.163560
60162                     (38.30772, -82.43405)   4535.603041
60163  (38.232440634728874, -82.59977435647347)   2076.214300
60164                     (38.23525, -82.55913)   5969.570585
60165                     (38.23508, -82.41927)  10020.498261
60166   (37.96168427102013, -82.33255384878288)   3711.816933
60167   (38.354640706117934, -82.4457980499672)   3175.400946

                                                    link  \
60158  https://edbltn.github.io/show-me-the-ballot/da...
60159  https://edbltn.github.io/show-me-the-ballot/da...
60160  https://edbltn.github.io/show-me-the-ballot/da...
60161  https://edbltn.github.io/show-me-the-ballot/da...
60162  https://edbltn.github.io/show-me-the-ballot/da...
60163  https://edbltn.github.io/show-me-the-ballot/da...
60164  https://edbltn.github.io/show-me-the-ballot/da...
60165  https://edbltn.github.io/show-me-the-ballot/da...
60166  https://edbltn.github.io/show-me-the-ballot/da...
60167  https://edbltn.github.io/show-me-the-ballot/da...

                                                geometry  \
60158  POLYGON ((1186499.109 1740265.351, 1186494.382...
60159  POLYGON ((1194452.492 1755574.679, 1194478.436...
60160  MULTIPOLYGON (((1159100.129 1779528.996, 11590...
60161  POLYGON ((1158567.761 1781506.423, 1158537.64 ...
60162  POLYGON ((1173421.272 1785162.677, 1173450.488...
60163  MULTIPOLYGON (((1158608.846 1767135.304, 11586...
60164  MULTIPOLYGON (((1158351.152 1765443.623, 11583...
60165  POLYGON ((1178600.418 1781981.614, 1178763.034...
60166  POLYGON ((1190135.968 1745836.73, 1190133.901 ...
60167  MULTIPOLYGON (((1174535.693 1784470.02, 117473...

                                         latlng
60158   (37.89816159256202, -82.38922280324576)
60159   (38.03135364993199, -82.22660019732452)
60160   (38.39304271335658, -82.59620755035604)
60161                     (38.34969, -82.50693)
60162                     (38.30772, -82.43405)
60163  (38.232440634728874, -82.59977435647347)
60164                     (38.23525, -82.55913)
60165                     (38.23508, -82.41927)
60166   (37.96168427102013, -82.33255384878288)
60167   (38.354640706117934, -82.4457980499672)

In [31]:
area_df['district'] = area_df.district.str.replace('00', '01')

In [15]:
#we imported results results_2024-11-03.csv to see what was inside 
old_result_df = pd.read_csv('data/raw/results_2024-11-03.csv')
old_result_df.head()

,Unnamed: 0,zip,county,district,state,lat,lng,response
0,0,68791,Cuming,NE-CD01,Nebraska,41.991030,-96.932450,"{""success"": true, ""data"": {""districts"": [{""id""..."
1,21,68047,Cuming,NE-CD01,Nebraska,42.062633,-96.755579,"{""success"": true, ""data"": {""districts"": [{""id""..."
2,40,68057,Cuming,NE-CD01,Nebraska,41.748409,-96.593060,"{""success"": true, ""data"": {""districts"": [{""id""..."
3,61,68038,Cuming,NE-CD01,Nebraska,41.913534,-96.571270,"{""success"": true, ""data"": {""districts"": [{""id""..."
4,82,68641,Cuming,NE-CD01,Nebraska,41.802225,-96.993344,"{""success"": true, ""data"": {""districts"": [{""id""..."

# Define Ballotpedia API lookup

Caches and retrieves Ballotpedia geographic data for a given latitude/longitude. Uses polite rate limiting and request headers. Function has a 100,000 item cache to avoid duplicate API calls.

In [9]:
import requests
from functools import lru_cache

@lru_cache(maxsize=100_000)
def get_ballotpedia_data_rigorous(lat, lng, rate_limit=2):
    url = "https://api4.ballotpedia.org/myvote_redistricting_with_historical"
    params = {
        'long': str(lng),
        'lat': str(lat),
        'include_volunteer': 'true'
    }
    headers = {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36',
        'Referer': 'https://sblv3.ballotpedia.org/',
        'Origin': 'https://sblv3.ballotpedia.org'
    }
    
    response = requests.get(url, params=params, headers=headers)

    # Rate limit
    time.sleep(rate_limit)
    
    if response.json().get('message') == 'Forbidden':
        raise PermissionError


    print(response.json())
    return response.json()

# Define processing functions

Functions to transform raw API election data into a structured format:
- Process ballot measures and candidate information
- Calculate decision metrics (number of races and options)
- Format final output as a pandas DataFrame with location data

In [10]:
import pandas as pd
from typing import Dict, List, Optional
from collections import defaultdict

def extract_election_data(api_response: Dict) -> List[Dict]:
    return api_response.get('data', {}).get('elections', [])

def process_ballot_measure(measure: Dict, common_data: Dict) -> Dict:
    return {
        **common_data,
        'race_type': 'Ballot Measure',
        'office.name': measure['name'],
        'office.type': 'Ballot Measure',
        'office.level': common_data['district_type'],
        'office.branch': 'N/A',
        'number_of_seats': 1,
        'person.name': 'Yes/No Question',
        'person.url': None,
        'party_affiliation': None,
        'status': 'On the Ballot',
        'is_incumbent': False,
        'running_mate.name': None,
        'measure_id': measure['id'],
        'measure_district_type': measure['district_type']
    }

def process_candidate(candidate: Dict, race: Dict, common_data: Dict) -> Dict:
    office = race['office']
    return {
        **common_data,
        'race_type': 'Candidate',
        'office.name': office['name'],
        'office.type': office['type'],
        'office.level': office['level'],
        'office.branch': office['branch'],
        'number_of_seats': race['number_of_seats'],
        'person.name': candidate['person']['name'],
        'person.url': candidate['person']['url'],
        'party_affiliation': candidate['party_affiliation'],
        'status': candidate['status'],
        'is_incumbent': candidate['is_incumbent'],
        'running_mate.name': candidate['running_mate']['name'] if candidate.get('running_mate') else None,
        'measure_id': None,
        'measure_district_type': None
    }

def process_district(district: Dict, election_date: str) -> List[Dict]:
    common_data = {
        'election_date': election_date,
        'district_name': district['name'],
        'district_type': district['type']
    }
    
    ballot_measures = [process_ballot_measure(measure, common_data) for measure in district.get('ballot_measures') or []]
    candidates = [process_candidate(candidate, race, common_data) 
                  for race in district.get('races')  or []
                  for candidate in race['candidates']]
    
    return ballot_measures + candidates

def calculate_decision_metrics(df: pd.DataFrame) -> pd.DataFrame:
    def count_decisions_and_options(group):
        decisions = defaultdict(int)
        for _, row in group.iterrows():
            if row['race_type'] == 'Ballot Measure':
                decisions[row['office.name']] = 2  # Yes/No options
            else:
                decisions[row['office.name']] += 1
        
        unique_decisions = len(decisions)
        total_options = sum(decisions.values())
        
        group['unique_decisions'] = unique_decisions
        group['total_options'] = total_options
        return group

    return df.groupby(['district_name', 'district_type']).apply(count_decisions_and_options).reset_index(drop=True)

def process_api_response(api_response: Dict, lat: float, lng: float) -> Optional[pd.DataFrame]:
    if not api_response:
        return None
        
    elections = extract_election_data(api_response)
    if not elections:
        return None
    
    processed_data = [
        item for election in elections
        for district in election['districts']
        for item in process_district(district, election['date'])
    ]
    
    df = pd.DataFrame(processed_data)
    df['group_id'] = df.groupby(['district_name', 'district_type']).ngroup()
    df['lat'], df['lng'] = lat, lng
    
    df = calculate_decision_metrics(df)
    
    return df

# Define main processing loop

Processes and accumulates data for each geographic point through the Ballotpedia API

In [17]:
#running this cell to CREATE an empty result_df 
import json
#result_df = pd.read_csv('data/raw/results_2024-11-03.csv')
result_df = pd.DataFrame()

In [ ]:
#strategy: Eric is re-using previous data (collected during the elections) instead of creating a new db for the full ballot version; we must try from scratch data-wise, but using some of the methods already created

In [ ]:
# # Define the desired column names
# column_names = ['Name', 'Age', 'City']

# # Create an empty DataFrame with the specified columns
# empty_df = pd.DataFrame(columns=column_names)

# # Print the empty DataFrame
# print(empty_df)

In [32]:
# Define the desired column names
column_names = ['zip', 'state', 'district', 'county', 'lat', 'lng', 'response']

# Create an empty DataFrame with the specified columns
empty_df = pd.DataFrame(columns=column_names)

result_df = empty_df
# Print the empty DataFrame
print(result_df)

Empty DataFrame
Columns: [zip, state, district, county, lat, lng, response]
Index: []

In [26]:
# result_df['zip'] = result_df.zip.astype(str)
# result_df['district'] = result_df.district.astype(str).str.slice(-2)
# result_df['lat'] = result_df.lat.astype(str).str.slice(0, 12)
# result_df['lng'] = result_df.lng.astype(str).str.slice(0, 12)
response_lookup = dict(result_df
                       .drop_duplicates(['zip', 'lat', 'lng'])
                       .set_index(['zip', 'lat', 'lng'])
                       .response.apply(json.loads))
response_lookup.update(dict(result_df
                            .drop_duplicates(['zip', 'county', 'district'])
                            .set_index(['zip', 'county', 'district'])
                            .response.apply(json.loads)))

In [44]:
import os
import time

def process_dataframe(df):
    all_results = []
    
    for row in tqdm(df.itertuples(), total=len(df), desc="Processing rows"):

        lat, lng = row.latlng
        key1 = (str(int(row.zip)), str(lat)[:12], str(lng)[:12])
        key2 = (f'{int(row.zip):05}', str(lat)[:12], str(lng)[:12])
        key3 = (str(int(row.zip)), row.county, row.district)
        key4 = (str(int(row.zip)), row.county, None)
        key5 = (str(int(row.zip)), row.county, 'ne')
        key6 = (str(int(row.zip)), row.county, '00')
        key7 = (str(int(row.zip)), row.county, '01')
        for key_ in [key1, key2, key3, key4, key5, key6, key7]:
            if key_ in response_lookup:
                break
        key = key_
        if key in response_lookup:
            response = response_lookup[key]
        else:
            response = None
            for i in range(60):
                try:
                    response = get_ballotpedia_data_rigorous(lat, lng, rate_limit=0.1)
                    if response['data']['districts'] is not None:
                        response['data']['districts'][0]
                    break
                except PermissionError:
                    if i == 0:
                        print('PermissionError:', lat, lng, row.state, row.county)
                    os.system('say "beep"')  # Uses system text-to-speech to make a sound
                    time.sleep(3**(i))
                    continue
                except Exception as e:
                    print('Exception:', e, lat, lng, row.state, row.county)
                    print(response)
                    print(e)
                    time.sleep(2**(i))
                    continue
                
        response_df = process_api_response(response, lat, lng)
        if response_df is None:
            display(row.zip)
            display(row.county)
            display(row.district)
            continue
        else:
            response_lookup[row.zip, row.county, row.district] = response
            
        response_df['response'] = json.dumps(response)
        response_df['intersection_id'] = row.intersection_id
        response_df['district'] = row.district
        response_df['county'] = row.county
        response_df['state'] = row.state
        response_df['zip'] = row.zip
        response_df['geometry'] = row.geometry
        results = response_df.to_dict(orient='records')
        
        all_results.extend(results)
    # return all_results (failed attempt 9/22)
        
    return pd.DataFrame(all_results)

In [50]:
sample_area_df = area_df.iloc[120:170]

In [51]:
sample_area_df

,intersection_id,zip,county,district,population,state,state_id,center_lat,lookup_lat,best_width,link,geometry,latlng
120,140,95936,Sierra,03,146.0,California,CA,"(39.56334083842082, -120.7928168166203)","(39.56336, -120.79279)",6243.286785,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-2095264.521 2111470.261, -2095257.5...","(39.56336, -120.79279)"
121,141,95960,Sierra,03,647.0,California,CA,"(39.43397267406749, -120.9724979006489)","(39.43397267406749, -120.9724979006489)",3287.766034,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-2103559.932 2099602.534, -2103574.1...","(39.43397267406749, -120.9724979006489)"
122,142,95944,Sierra,03,647.0,California,CA,"(39.53484448258896, -120.86151275525232)","(39.53482, -120.86159)",2835.936694,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-2096173.573 2113442.189, -2096151.3...","(39.53482, -120.86159)"
123,145,38549,Clinton,01,4115.0,Tennessee,TN,"(36.62904160864791, -85.15907395015846)","(36.62904160864791, -85.15907395015846)",926.549184,https://edbltn.github.io/show-me-the-ballot/da...,"MULTIPOLYGON (((957477.504 1563339.03, 957349....","(36.62904160864791, -85.15907395015846)"
124,146,42717,Clinton,01,5953.0,Kentucky,KY,"(36.67011781873429, -85.26428368249475)","(36.67011781873429, -85.26428368249475)",2164.947426,https://edbltn.github.io/show-me-the-ballot/da...,"MULTIPOLYGON (((948198.685 1562503.111, 948112...","(36.67011781873429, -85.26428368249475)"
125,147,42717,Clinton,06,5953.0,Kentucky,KY,"(36.62603647734905, -85.29535459873286)","(36.62603647734905, -85.29535459873286)",34.905863,https://edbltn.github.io/show-me-the-ballot/da...,"MULTIPOLYGON (((946836.971 1562308.294, 946853...","(36.62603647734905, -85.29535459873286)"
126,148,42602,Clinton,05,9255.0,Kentucky,KY,"(36.7163442528393, -85.00994673876218)","(36.7163442528393, -85.00994673876218)",515.330287,https://edbltn.github.io/show-me-the-ballot/da...,"MULTIPOLYGON (((973730.479 1564660.914, 973744...","(36.7163442528393, -85.00994673876218)"
127,149,42602,Clinton,01,9255.0,Kentucky,KY,"(36.72938186345639, -85.13375009209312)","(36.73201, -85.13324)",17831.086030,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((969991.06 1577959.949, 969986.14 157...","(36.73201, -85.13324)"
128,150,42602,Clinton,06,9255.0,Kentucky,KY,"(36.62238971615073, -85.09630313505714)","(36.62238971615073, -85.09630313505714)",16.112004,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((964046.553 1563809.657, 963984.565 1...","(36.62238971615073, -85.09630313505714)"
129,151,42603,Clinton,05,521.0,Kentucky,KY,"(36.78850355924633, -85.02057487135353)","(36.78850355924633, -85.02057487135353)",455.433255,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((967814.078 1585001.896, 967815.594 1...","(36.78850355924633, -85.02057487135353)"
130,152,42603,Clinton,01,521.0,Kentucky,KY,"(36.7726518565568, -85.02549370136113)","(36.7726518565568, -85.02549370136113)",1933.116828,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((970386.905 1579606.193, 970337.122 1...","(36.7726518565568, -85.02549370136113)"
131,155,45881,Hancock,05,1556.0,Ohio,OH,"(40.94974035029383, -83.77425176601031)","(40.95, -83.78)",5447.347244,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1011882.411 2061936.052, 1011843.12 ...","(40.95, -83.78)"
132,157,45810,Hancock,05,7714.0,Ohio,OH,"(40.82952353505696, -83.81309388040539)","(40.82952353505696, -83.81309388040539)",2429.633888,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1015883.466 2043975.283, 1015860.787...","(40.82952353505696, -83.81309388040539)"
133,158,45858,Hancock,05,2540.0,Ohio,OH,"(41.10688015203116, -83.80335486148884)","(41.10688, -83.80338)",9430.254457,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1008147.083 2066508.532, 1008137.162...","(41.10688, -83.80338)"
134,159,45836,Hancock,05,1417.0,Ohio,OH,"(40.8230420975061, -83.66921343209896)","(40.8230420975061, -83.66921343209896)",847.732325,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1030103.304 2045794.514, 1029891.983...","(40.8230420975061, -83.66921343209896)"
135,160,45877,Hancock,05,2305.0,Ohio,OH,"(40.95936807735481, -83.8781597735101)","(40.95936807735481, -83.8781597735101)",508.851060,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1009218.335 2058253.091, 1009201.917...","(40.95936807735481, -83.8781597735101)"
136,162,45817,Hancock,05,6236.0,Ohio,OH,"(40.884100255756294, -83.83815124273845)","(40.884100255756294, -83.83815124273845)",7705.781868,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1009683.38 2054676.219, 1009680.339 ...","(40.884100255756294, -83.83815124273845)"
137,164,45843,Hancock,05,3733.0,Ohio,OH,"(40.83664974415822, -83.63217093047234)","(40.83664974415822, -83.63217093047234)",3440.827843,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1041198.369 2048756.248, 1041264.78 ...","(40.83664974415822, -83.63217093047234)"
138,165,43316,Hancock,05,6251.0,Ohio,OH,"(40.93026627067479, -83.4802185949351)","(40.93026627067479, -83.4802185949351)",1603.370107,https://edbltn.github.io/show-me-the-ballot/da...,"MULTIPOLYGON (((1044240.213 2062707.118, 10443...","(40.93026627067479, -83.4802185949351)"
139,166,43516,Hancock,05,2696.0,Ohio,OH,"(41.16042889244864, -83.83672152189213)","(41.16042889244864, -83.83672152189213)",1711.062983,https://edbltn.github.io/show-me-the-ballot/da...,"MULTIPOLYGON (((1011724.606 2082789.24, 101175...","(41.16042889244864, -83.83672152189213)"
140,167,44804,Hancock,05,1605.0,Ohio,OH,"(41.10705214434945, -83.53537658851104)","(41.10708, -83.53538)",4532.465955,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1030940.77 2077214.279, 1030930.1 20...","(41.10708, -83.53538)"
141,168,44802,Hancock,05,952.0,Ohio,OH,"(41.038053330951485, -83.44472111226575)","(41.038053330951485, -83.44472111226575)",4060.836881,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1045634.826 2075542.157, 1045635.196...","(41.038053330951485, -83.44472111226575)"
142,169,44817,Hancock,05,1524.0,Ohio,OH,"(41.154915615221995, -83.54581679061131)","(41.154915615221995, -83.54581679061131)",2618.486432,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1032342.992 2085303.68, 1032344.808 ...","(41.154915615221995, -83.54581679061131)"
143,170,44830,Hancock,05,17974.0,Ohio,OH,"(41.124931290273615, -83.46303189597994)","(41.124931290273615, -83.46303189597994)",5821.932182,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1037616.423 2085888.76, 1038518.317 ...","(41.124931290273615, -83.46303189597994)"
144,171,45868,Hancock,05,904.0,Ohio,OH,"(40.969108029960886, -83.84665643947639)","(40.96986, -83.84839)",3612.226815,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1008991.975 2059962.636, 1008982.715...","(40.96986, -83.84839)"
145,172,45872,Hancock,05,4330.0,Ohio,OH,"(41.16175756830999, -83.70355071166406)","(41.16175756830999, -83.70355071166406)",1599.500443,https://edbltn.github.io/show-me-the-ballot/da...,"MULTIPOLYGON (((1025396.981 2084494.564, 10253...","(41.16175756830999, -83.70355071166406)"
146,173,45889,Hancock,05,1573.0,Ohio,OH,"(41.14600635976272, -83.64085045554948)","(41.14606, -83.64101)",4168.047642,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1029154.596 2084947.705, 1029937.061...","(41.14606, -83.64101)"
147,174,45890,Hancock,05,907.0,Ohio,OH,"(40.977480806809226, -83.49107798393185)","(40.97752, -83.49105)",3567.520390,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1043840.106 2067051.602, 1043786.031...","(40.97752, -83.49105)"
148,175,45897,Hancock,05,2753.0,Ohio,OH,"(40.83436052045881, -83.65675417102757)","(40.83434, -83.65676)",934.459325,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1030187.139 2045805.695, 1030177.697...","(40.83434, -83.65676)"
149,176,45814,Hancock,05,2753.0,Ohio,OH,"(40.901201217414965, -83.61547822204433)","(40.90119, -83.61545)",5701.266339,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1025614.325 2049845.552, 1025574.865...","(40.90119, -83.61545)"
150,177,45816,Hancock,05,904.0,Ohio,OH,"(41.004537466026036, -83.79400512792817)","(41.00452, -83.79392)",759.611117,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1015573.721 2065180.351, 1015622.331...","(41.00452, -83.79392)"
151,178,45840,Hancock,05,54624.0,Ohio,OH,"(41.02624341092074, -83.64942859500755)","(41.02626, -83.64943)",15222.359213,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1008399.036 2064584.249, 1008382.487...","(41.02626, -83.64943)"
152,179,45841,Hancock,05,936.0,Ohio,OH,"(40.87953204164493, -83.7350231601088)","(40.87955, -83.735)",5293.792957,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1018310.324 2049719.148, 1018289.838...","(40.87955, -83.735)"
153,180,45856,Hancock,05,5075.0,Ohio,OH,"(41.13866595319211, -83.87580319679206)","(41.13866595319211, -83.87580319679206)",925.201903,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1006763.423 2077157.425, 1006751.863...","(41.13866595319211, -83.87580319679206)"
154,181,45867,Hancock,05,1031.0,Ohio,OH,"(40.89793081317002, -83.53924003672381)","(40.89795, -83.53825)",5227.597955,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((1042836.612 2061209.247, 1042597.226...","(40.89795, -83.53825)"
155,182,79052,Hale,19,1334.0,Texas,TX,"(34.296773863377496, -101.884381650323)","(34.296773863377496, -101.884381650323)",4260.363548,https://edbltn.github.io/show-me-the-ballot/da...,"MULTIPOLYGON (((-538507.565 1266693.259, -5381...","(34.296773863377496, -101.884381650323)"
156,183,79041,Hale,19,2821.0,Texas,TX,"(34.03921545357606, -101.92790517590997)","(34.0376, -101.93466)",16956.925809,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-558461.641 1221203.641, -558425.509...","(34.0376, -101.93466)"
157,184,79064,Hale,19,2442.0,Texas,TX,"(34.2025553858351, -102.06036085636114)","(34.2025553858351, -102.06036085636114)",5950.809545,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-557270.762 1242296.721, -557171.286...","(34.2025553858351, -102.06036085636114)"
158,185,79072,Hale,19,25831.0,Texas,TX,"(34.17189816932135, -101.74490815217268)","(34.1719, -101.745)",22775.839380,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-526540.32 1265948.066, -525924.809 ...","(34.1719, -101.745)"
159,186,79043,Hale,19,1650.0,Texas,TX,"(34.294736526811086, -102.05840251995456)","(34.294736526811086, -102.05840251995456)",4021.188655,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-555279.349 1267759.497, -555141.73 ...","(34.294736526811086, -102.05840251995456)"
160,187,79250,Hale,19,1188.0,Texas,TX,"(33.913733846904485, -101.63244283679751)","(33.88134, -101.59881)",12126.378320,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-509937.018 1229657.914, -509955.317...","(33.88134, -101.59881)"
161,188,79021,Hale,19,2821.0,Texas,TX,"(33.98366392557855, -101.99301363937872)","(33.98366, -101.99302)",3206.058702,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-551068.576 1231618.65, -550754.412 ...","(33.98366, -101.99302)"
162,189,79032,Hale,19,25831.0,Texas,TX,"(34.28780154213235, -101.89491888089567)","(34.2878, -101.89492)",2287.890474,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-540454.079 1266811.127, -540463.769...","(34.2878, -101.89492)"
163,190,79311,Hale,19,3767.0,Texas,TX,"(33.876155514332794, -101.89226811430619)","(33.85781, -101.88228)",9487.884467,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-525229.839 1211659.906, -525230.848...","(33.85781, -101.88228)"
164,191,79073,Hale,19,2821.0,Texas,TX,"(33.95608426322167, -101.94924827857788)","(33.95608, -101.94924)",1584.202508,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-546156.705 1228821.62, -546151.738 ...","(33.95608, -101.94924)"
165,192,36276,Clay,03,2817.0,Alabama,AL,"(33.135829644584476, -85.69447847299216)","(33.135829644584476, -85.69447847299216)",5661.161225,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((956816.143 1175354.187, 956878.377 1...","(33.135829644584476, -85.69447847299216)"
166,193,36256,Clay,03,1478.0,Alabama,AL,"(33.11256387936543, -85.76599538890353)","(33.11256387936543, -85.76599538890353)",1922.956889,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((949030.784 1166290.668, 948800.233 1...","(33.11256387936543, -85.76599538890353)"
167,194,35082,Clay,03,5413.0,Alabama,AL,"(33.15631130829701, -86.1545527539296)","(33.1563, -86.15456)",3207.399476,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((909418.288 1164945.133, 909392.874 1...","(33.1563, -86.15456)"
168,195,35150,Clay,03,17421.0,Alabama,AL,"(33.118476959800745, -86.16349575512038)","(33.118476959800745, -86.16349575512038)",327.646492,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((909475.335 1164319.013, 909467.466 1...","(33.118476959800745, -86.16349575512038)"
169,196,35160,Clay,03,26369.0,Alabama,AL,"(33.25663739888898, -86.03713617162886)","(33.25663739888898, -86.03713617162886)",9893.874799,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((925051.077 1189252.3, 924942.584 119...","(33.25663739888898, -86.03713617162886)"

In [52]:
result_df = process_dataframe(sample_area_df)

Processing rows:   2%|█                                                  | 1/50 [00:00<00:32,  1.52it/s]

{'success': True, 'data': {'districts': [{'id': 516, 'name': 'California', 'type': 'State', 'state': 'CA'}], 'polling_place_locator': {'url': 'https://www.sos.ca.gov/elections/polling-place/'}, 'elections': [{'date': '2025-11-04', 'candidate_lists_complete': False, 'districts': [{'id': 516, 'name': 'California', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 28073, 'name': 'California Proposition 50, Use of Legislative Congressional Redistricting Map Amendment (2025)', 'district_type': 'State'}], 'races': None}]}]}, 'message': None}

Processing rows:   4%|██                                                 | 2/50 [00:01<00:25,  1.86it/s]

{'success': True, 'data': {'districts': [{'id': 516, 'name': 'California', 'type': 'State', 'state': 'CA'}], 'polling_place_locator': {'url': 'https://www.sos.ca.gov/elections/polling-place/'}, 'elections': [{'date': '2025-11-04', 'candidate_lists_complete': False, 'districts': [{'id': 516, 'name': 'California', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 28073, 'name': 'California Proposition 50, Use of Legislative Congressional Redistricting Map Amendment (2025)', 'district_type': 'State'}], 'races': None}]}]}, 'message': None}

Processing rows:   6%|███                                                | 3/50 [00:01<00:23,  2.01it/s]

{'success': True, 'data': {'districts': [{'id': 516, 'name': 'California', 'type': 'State', 'state': 'CA'}], 'polling_place_locator': {'url': 'https://www.sos.ca.gov/elections/polling-place/'}, 'elections': [{'date': '2025-11-04', 'candidate_lists_complete': False, 'districts': [{'id': 516, 'name': 'California', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 28073, 'name': 'California Proposition 50, Use of Legislative Congressional Redistricting Map Amendment (2025)', 'district_type': 'State'}], 'races': None}]}]}, 'message': None}

Processing rows:   8%|████                                               | 4/50 [00:02<00:22,  2.07it/s]

{'success': True, 'data': {'districts': [{'id': 529, 'name': 'Kentucky', 'type': 'State', 'state': 'KY'}], 'polling_place_locator': {'url': 'https://vrsws.sos.ky.gov/vic/'}, 'elections': [{'date': '2026-05-19', 'candidate_lists_complete': False, 'districts': [{'id': 529, 'name': 'Kentucky', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62963, 'office': {'id': 1259, 'name': 'U.S. Senate Kentucky', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Kentucky', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 529, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Kentucky,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310208, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294606, 'name': 'Pamela Stevenson', 'first_name': 'Pamela', 'last_name': 'Stevenson', 'image': {'id': 165591, 'name': 'Pamela_Stevenson.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Pamela_Stevenson.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Pamela_Stevenson.jpg'}, 'url': 'https://ballotpedia.org/Pamela_Stevenson'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311153, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 626769, 'name': 'Wende Kennedy', 'first_name': 'Wende', 'last_name': 'Kennedy', 'image': None, 'url': 'https://ballotpedia.org/Wende_Kennedy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311272, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 308245, 'name': 'Daniel Cameron', 'first_name': 'Daniel', 'last_name': 'Cameron', 'image': {'id': 230697, 'name': 'dcameron3.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/dcameron3.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/dcameron3.jpg'}, 'url': 'https://ballotpedia.org/Daniel_Cameron'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329095, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 527799, 'name': 'Jared Randall', 'first_name': 'Jared', 'last_name': 'Randall', 'image': {'id': 237448, 'name': 'JaredRandall2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/JaredRandall2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/JaredRandall2024.jpeg'}, 'url': 'https://ballotpedia.org/Jared_Randall'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 346880, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 663270, 'name': 'Mike Faris', 'first_name': 'Mike', 'last_name': 'Faris', 'image': {'id': 258369, 'name': 'Mike_Faris_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Mike_Faris_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Mike_Faris_2025.jpeg'}, 'url': 'https://ballotpedia.org/Mike_Faris'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 354713, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 1846, 'name': 'Andy Barr', 'first_name': 'Andy', 'last_name': 'Barr', 'image': {'id': 105184, 'name': 'Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg'}, 'url': 'https://ballotpedia.org/Andy_Barr'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355784, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674750, 'name': 'Andrew Shelley', 'first_name': 'Andrew', 'last_name': 'Shelley', 'image': None, 'url': 'https://ballotpedia.org/Andrew_Shelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 359737, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679644, 'name': 'Nate Morris', 'first_name': 'Nate', 'last_name': 'Morris', 'image': None, 'url': 'https://ballotpedia.org/Nate_Morris'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360397, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680243, 'name': 'Vincent Thompson', 'first_name': 'Vincent', 'last_name': 'Thompson', 'image': None, 'url': 'https://ballotpedia.org/Vincent_Thompson_(Kentucky)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368402, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689162, 'name': 'Logan Forsythe', 'first_name': 'Logan', 'last_name': 'Forsythe', 'image': None, 'url': 'https://ballotpedia.org/Logan_Forsythe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368403, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689163, 'name': 'Joel Willett', 'first_name': 'Joel', 'last_name': 'Willett', 'image': None, 'url': 'https://ballotpedia.org/Joel_Willett'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 169, 'name': 'Kentucky District 1', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64409, 'office': {'id': 9528, 'name': 'U.S. House Kentucky District 1', 'url': "https://ballotpedia.org/Kentucky's_1st_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 169, 'url': "https://ballotpedia.org/Kentucky's_1st_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308081, 'race': 64409, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 22719, 'name': 'James Comer Jr.', 'first_name': 'James', 'last_name': 'Comer', 'image': {'id': 66601, 'name': 'James_Comer.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James_Comer.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James_Comer.jpg'}, 'url': 'https://ballotpedia.org/James_Comer_Jr.'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365884, 'race': 64409, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294531, 'name': 'Drew Williams', 'first_name': 'Drew', 'last_name': 'Williams', 'image': {'id': 262173, 'name': 'DrewWilliams2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/DrewWilliams2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/DrewWilliams2025.jpg'}, 'url': 'https://ballotpedia.org/Drew_Williams'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}]}, {'id': 4145, 'name': 'Kentucky House of Representatives District 83', 'type': 'State Legislative (Lower)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 72696, 'office': {'id': 29158, 'name': 'Kentucky House of Representatives District 83', 'url': 'https://ballotpedia.org/Kentucky_House_of_Representatives_District_83', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 4145, 'url': 'https://ballotpedia.org/Kentucky_House_of_Representatives_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative (Lower)', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310435, 'race': 72696, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 322196, 'name': 'Joshua Branscum', 'first_name': 'Joshua', 'last_name': 'Branscum', 'image': {'id': 217615, 'name': 'Josh-Branscum.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Josh-Branscum.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Josh-Branscum.jpg'}, 'url': 'https://ballotpedia.org/Joshua_Branscum'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}]}]}, 'message': None}

Processing rows:  10%|█████                                              | 5/50 [00:02<00:20,  2.21it/s]

{'success': True, 'data': {'districts': [{'id': 529, 'name': 'Kentucky', 'type': 'State', 'state': 'KY'}], 'polling_place_locator': {'url': 'https://vrsws.sos.ky.gov/vic/'}, 'elections': [{'date': '2026-05-19', 'candidate_lists_complete': False, 'districts': [{'id': 529, 'name': 'Kentucky', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62963, 'office': {'id': 1259, 'name': 'U.S. Senate Kentucky', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Kentucky', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 529, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Kentucky,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310208, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294606, 'name': 'Pamela Stevenson', 'first_name': 'Pamela', 'last_name': 'Stevenson', 'image': {'id': 165591, 'name': 'Pamela_Stevenson.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Pamela_Stevenson.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Pamela_Stevenson.jpg'}, 'url': 'https://ballotpedia.org/Pamela_Stevenson'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311153, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 626769, 'name': 'Wende Kennedy', 'first_name': 'Wende', 'last_name': 'Kennedy', 'image': None, 'url': 'https://ballotpedia.org/Wende_Kennedy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311272, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 308245, 'name': 'Daniel Cameron', 'first_name': 'Daniel', 'last_name': 'Cameron', 'image': {'id': 230697, 'name': 'dcameron3.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/dcameron3.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/dcameron3.jpg'}, 'url': 'https://ballotpedia.org/Daniel_Cameron'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329095, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 527799, 'name': 'Jared Randall', 'first_name': 'Jared', 'last_name': 'Randall', 'image': {'id': 237448, 'name': 'JaredRandall2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/JaredRandall2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/JaredRandall2024.jpeg'}, 'url': 'https://ballotpedia.org/Jared_Randall'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 346880, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 663270, 'name': 'Mike Faris', 'first_name': 'Mike', 'last_name': 'Faris', 'image': {'id': 258369, 'name': 'Mike_Faris_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Mike_Faris_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Mike_Faris_2025.jpeg'}, 'url': 'https://ballotpedia.org/Mike_Faris'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 354713, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 1846, 'name': 'Andy Barr', 'first_name': 'Andy', 'last_name': 'Barr', 'image': {'id': 105184, 'name': 'Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg'}, 'url': 'https://ballotpedia.org/Andy_Barr'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355784, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674750, 'name': 'Andrew Shelley', 'first_name': 'Andrew', 'last_name': 'Shelley', 'image': None, 'url': 'https://ballotpedia.org/Andrew_Shelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 359737, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679644, 'name': 'Nate Morris', 'first_name': 'Nate', 'last_name': 'Morris', 'image': None, 'url': 'https://ballotpedia.org/Nate_Morris'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360397, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680243, 'name': 'Vincent Thompson', 'first_name': 'Vincent', 'last_name': 'Thompson', 'image': None, 'url': 'https://ballotpedia.org/Vincent_Thompson_(Kentucky)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368402, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689162, 'name': 'Logan Forsythe', 'first_name': 'Logan', 'last_name': 'Forsythe', 'image': None, 'url': 'https://ballotpedia.org/Logan_Forsythe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368403, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689163, 'name': 'Joel Willett', 'first_name': 'Joel', 'last_name': 'Willett', 'image': None, 'url': 'https://ballotpedia.org/Joel_Willett'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 169, 'name': 'Kentucky District 1', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64409, 'office': {'id': 9528, 'name': 'U.S. House Kentucky District 1', 'url': "https://ballotpedia.org/Kentucky's_1st_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 169, 'url': "https://ballotpedia.org/Kentucky's_1st_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308081, 'race': 64409, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 22719, 'name': 'James Comer Jr.', 'first_name': 'James', 'last_name': 'Comer', 'image': {'id': 66601, 'name': 'James_Comer.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James_Comer.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James_Comer.jpg'}, 'url': 'https://ballotpedia.org/James_Comer_Jr.'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365884, 'race': 64409, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294531, 'name': 'Drew Williams', 'first_name': 'Drew', 'last_name': 'Williams', 'image': {'id': 262173, 'name': 'DrewWilliams2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/DrewWilliams2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/DrewWilliams2025.jpg'}, 'url': 'https://ballotpedia.org/Drew_Williams'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}]}, {'id': 4145, 'name': 'Kentucky House of Representatives District 83', 'type': 'State Legislative (Lower)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 72696, 'office': {'id': 29158, 'name': 'Kentucky House of Representatives District 83', 'url': 'https://ballotpedia.org/Kentucky_House_of_Representatives_District_83', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 4145, 'url': 'https://ballotpedia.org/Kentucky_House_of_Representatives_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative (Lower)', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310435, 'race': 72696, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 322196, 'name': 'Joshua Branscum', 'first_name': 'Joshua', 'last_name': 'Branscum', 'image': {'id': 217615, 'name': 'Josh-Branscum.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Josh-Branscum.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Josh-Branscum.jpg'}, 'url': 'https://ballotpedia.org/Joshua_Branscum'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}]}]}, 'message': None}

Processing rows:  14%|███████▏                                           | 7/50 [00:02<00:14,  3.04it/s]

{'success': True, 'data': {'districts': [{'id': 529, 'name': 'Kentucky', 'type': 'State', 'state': 'KY'}], 'polling_place_locator': {'url': 'https://vrsws.sos.ky.gov/vic/'}, 'elections': [{'date': '2026-05-19', 'candidate_lists_complete': False, 'districts': [{'id': 529, 'name': 'Kentucky', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62963, 'office': {'id': 1259, 'name': 'U.S. Senate Kentucky', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Kentucky', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 529, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Kentucky,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310208, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294606, 'name': 'Pamela Stevenson', 'first_name': 'Pamela', 'last_name': 'Stevenson', 'image': {'id': 165591, 'name': 'Pamela_Stevenson.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Pamela_Stevenson.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Pamela_Stevenson.jpg'}, 'url': 'https://ballotpedia.org/Pamela_Stevenson'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311153, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 626769, 'name': 'Wende Kennedy', 'first_name': 'Wende', 'last_name': 'Kennedy', 'image': None, 'url': 'https://ballotpedia.org/Wende_Kennedy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311272, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 308245, 'name': 'Daniel Cameron', 'first_name': 'Daniel', 'last_name': 'Cameron', 'image': {'id': 230697, 'name': 'dcameron3.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/dcameron3.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/dcameron3.jpg'}, 'url': 'https://ballotpedia.org/Daniel_Cameron'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329095, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 527799, 'name': 'Jared Randall', 'first_name': 'Jared', 'last_name': 'Randall', 'image': {'id': 237448, 'name': 'JaredRandall2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/JaredRandall2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/JaredRandall2024.jpeg'}, 'url': 'https://ballotpedia.org/Jared_Randall'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 346880, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 663270, 'name': 'Mike Faris', 'first_name': 'Mike', 'last_name': 'Faris', 'image': {'id': 258369, 'name': 'Mike_Faris_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Mike_Faris_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Mike_Faris_2025.jpeg'}, 'url': 'https://ballotpedia.org/Mike_Faris'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 354713, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 1846, 'name': 'Andy Barr', 'first_name': 'Andy', 'last_name': 'Barr', 'image': {'id': 105184, 'name': 'Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg'}, 'url': 'https://ballotpedia.org/Andy_Barr'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355784, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674750, 'name': 'Andrew Shelley', 'first_name': 'Andrew', 'last_name': 'Shelley', 'image': None, 'url': 'https://ballotpedia.org/Andrew_Shelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 359737, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679644, 'name': 'Nate Morris', 'first_name': 'Nate', 'last_name': 'Morris', 'image': None, 'url': 'https://ballotpedia.org/Nate_Morris'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360397, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680243, 'name': 'Vincent Thompson', 'first_name': 'Vincent', 'last_name': 'Thompson', 'image': None, 'url': 'https://ballotpedia.org/Vincent_Thompson_(Kentucky)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368402, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689162, 'name': 'Logan Forsythe', 'first_name': 'Logan', 'last_name': 'Forsythe', 'image': None, 'url': 'https://ballotpedia.org/Logan_Forsythe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368403, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689163, 'name': 'Joel Willett', 'first_name': 'Joel', 'last_name': 'Willett', 'image': None, 'url': 'https://ballotpedia.org/Joel_Willett'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 173, 'name': 'Kentucky District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64413, 'office': {'id': 3578, 'name': 'U.S. House Kentucky District 5', 'url': "https://ballotpedia.org/Kentucky's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 173, 'url': "https://ballotpedia.org/Kentucky's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 352862, 'race': 64413, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 20781, 'name': 'Hal Rogers', 'first_name': 'Hal', 'last_name': 'Rogers', 'image': {'id': 65577, 'name': 'Hal_Rogers.JPG', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Hal_Rogers.JPG', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Hal_Rogers.JPG'}, 'url': 'https://ballotpedia.org/Hal_Rogers'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354701, 'race': 64413, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673160, 'name': 'Ned Pillersdorf', 'first_name': 'Ned', 'last_name': 'Pillersdorf', 'image': None, 'url': 'https://ballotpedia.org/Ned_Pillersdorf'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360276, 'race': 64413, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 576069, 'name': 'Jacob Trimble', 'first_name': 'Jacob', 'last_name': 'Trimble', 'image': {'id': 260007, 'name': 'JacobTrimble2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/JacobTrimble2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/JacobTrimble2025.jpeg'}, 'url': 'https://ballotpedia.org/Jacob_Trimble'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}]}]}, 'message': None}

Processing rows:  16%|████████▏                                          | 8/50 [00:03<00:15,  2.68it/s]

{'success': True, 'data': {'districts': [{'id': 529, 'name': 'Kentucky', 'type': 'State', 'state': 'KY'}], 'polling_place_locator': {'url': 'https://vrsws.sos.ky.gov/vic/'}, 'elections': [{'date': '2026-05-19', 'candidate_lists_complete': False, 'districts': [{'id': 529, 'name': 'Kentucky', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62963, 'office': {'id': 1259, 'name': 'U.S. Senate Kentucky', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Kentucky', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 529, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Kentucky,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310208, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294606, 'name': 'Pamela Stevenson', 'first_name': 'Pamela', 'last_name': 'Stevenson', 'image': {'id': 165591, 'name': 'Pamela_Stevenson.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Pamela_Stevenson.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Pamela_Stevenson.jpg'}, 'url': 'https://ballotpedia.org/Pamela_Stevenson'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311153, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 626769, 'name': 'Wende Kennedy', 'first_name': 'Wende', 'last_name': 'Kennedy', 'image': None, 'url': 'https://ballotpedia.org/Wende_Kennedy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311272, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 308245, 'name': 'Daniel Cameron', 'first_name': 'Daniel', 'last_name': 'Cameron', 'image': {'id': 230697, 'name': 'dcameron3.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/dcameron3.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/dcameron3.jpg'}, 'url': 'https://ballotpedia.org/Daniel_Cameron'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329095, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 527799, 'name': 'Jared Randall', 'first_name': 'Jared', 'last_name': 'Randall', 'image': {'id': 237448, 'name': 'JaredRandall2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/JaredRandall2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/JaredRandall2024.jpeg'}, 'url': 'https://ballotpedia.org/Jared_Randall'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 346880, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 663270, 'name': 'Mike Faris', 'first_name': 'Mike', 'last_name': 'Faris', 'image': {'id': 258369, 'name': 'Mike_Faris_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Mike_Faris_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Mike_Faris_2025.jpeg'}, 'url': 'https://ballotpedia.org/Mike_Faris'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 354713, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 1846, 'name': 'Andy Barr', 'first_name': 'Andy', 'last_name': 'Barr', 'image': {'id': 105184, 'name': 'Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg'}, 'url': 'https://ballotpedia.org/Andy_Barr'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355784, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674750, 'name': 'Andrew Shelley', 'first_name': 'Andrew', 'last_name': 'Shelley', 'image': None, 'url': 'https://ballotpedia.org/Andrew_Shelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 359737, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679644, 'name': 'Nate Morris', 'first_name': 'Nate', 'last_name': 'Morris', 'image': None, 'url': 'https://ballotpedia.org/Nate_Morris'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360397, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680243, 'name': 'Vincent Thompson', 'first_name': 'Vincent', 'last_name': 'Thompson', 'image': None, 'url': 'https://ballotpedia.org/Vincent_Thompson_(Kentucky)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368402, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689162, 'name': 'Logan Forsythe', 'first_name': 'Logan', 'last_name': 'Forsythe', 'image': None, 'url': 'https://ballotpedia.org/Logan_Forsythe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368403, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689163, 'name': 'Joel Willett', 'first_name': 'Joel', 'last_name': 'Willett', 'image': None, 'url': 'https://ballotpedia.org/Joel_Willett'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 169, 'name': 'Kentucky District 1', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64409, 'office': {'id': 9528, 'name': 'U.S. House Kentucky District 1', 'url': "https://ballotpedia.org/Kentucky's_1st_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 169, 'url': "https://ballotpedia.org/Kentucky's_1st_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308081, 'race': 64409, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 22719, 'name': 'James Comer Jr.', 'first_name': 'James', 'last_name': 'Comer', 'image': {'id': 66601, 'name': 'James_Comer.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James_Comer.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James_Comer.jpg'}, 'url': 'https://ballotpedia.org/James_Comer_Jr.'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365884, 'race': 64409, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294531, 'name': 'Drew Williams', 'first_name': 'Drew', 'last_name': 'Williams', 'image': {'id': 262173, 'name': 'DrewWilliams2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/DrewWilliams2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/DrewWilliams2025.jpg'}, 'url': 'https://ballotpedia.org/Drew_Williams'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}]}, {'id': 4145, 'name': 'Kentucky House of Representatives District 83', 'type': 'State Legislative (Lower)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 72696, 'office': {'id': 29158, 'name': 'Kentucky House of Representatives District 83', 'url': 'https://ballotpedia.org/Kentucky_House_of_Representatives_District_83', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 4145, 'url': 'https://ballotpedia.org/Kentucky_House_of_Representatives_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative (Lower)', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310435, 'race': 72696, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 322196, 'name': 'Joshua Branscum', 'first_name': 'Joshua', 'last_name': 'Branscum', 'image': {'id': 217615, 'name': 'Josh-Branscum.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Josh-Branscum.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Josh-Branscum.jpg'}, 'url': 'https://ballotpedia.org/Joshua_Branscum'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}]}]}, 'message': None}

Processing rows:  20%|██████████                                        | 10/50 [00:03<00:13,  3.00it/s]

{'success': True, 'data': {'districts': [{'id': 529, 'name': 'Kentucky', 'type': 'State', 'state': 'KY'}], 'polling_place_locator': {'url': 'https://vrsws.sos.ky.gov/vic/'}, 'elections': [{'date': '2026-05-19', 'candidate_lists_complete': False, 'districts': [{'id': 529, 'name': 'Kentucky', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62963, 'office': {'id': 1259, 'name': 'U.S. Senate Kentucky', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Kentucky', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 529, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Kentucky,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310208, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294606, 'name': 'Pamela Stevenson', 'first_name': 'Pamela', 'last_name': 'Stevenson', 'image': {'id': 165591, 'name': 'Pamela_Stevenson.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Pamela_Stevenson.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Pamela_Stevenson.jpg'}, 'url': 'https://ballotpedia.org/Pamela_Stevenson'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311153, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 626769, 'name': 'Wende Kennedy', 'first_name': 'Wende', 'last_name': 'Kennedy', 'image': None, 'url': 'https://ballotpedia.org/Wende_Kennedy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311272, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 308245, 'name': 'Daniel Cameron', 'first_name': 'Daniel', 'last_name': 'Cameron', 'image': {'id': 230697, 'name': 'dcameron3.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/dcameron3.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/dcameron3.jpg'}, 'url': 'https://ballotpedia.org/Daniel_Cameron'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329095, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 527799, 'name': 'Jared Randall', 'first_name': 'Jared', 'last_name': 'Randall', 'image': {'id': 237448, 'name': 'JaredRandall2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/JaredRandall2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/JaredRandall2024.jpeg'}, 'url': 'https://ballotpedia.org/Jared_Randall'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 346880, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 663270, 'name': 'Mike Faris', 'first_name': 'Mike', 'last_name': 'Faris', 'image': {'id': 258369, 'name': 'Mike_Faris_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Mike_Faris_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Mike_Faris_2025.jpeg'}, 'url': 'https://ballotpedia.org/Mike_Faris'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 354713, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 1846, 'name': 'Andy Barr', 'first_name': 'Andy', 'last_name': 'Barr', 'image': {'id': 105184, 'name': 'Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg'}, 'url': 'https://ballotpedia.org/Andy_Barr'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355784, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674750, 'name': 'Andrew Shelley', 'first_name': 'Andrew', 'last_name': 'Shelley', 'image': None, 'url': 'https://ballotpedia.org/Andrew_Shelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 359737, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679644, 'name': 'Nate Morris', 'first_name': 'Nate', 'last_name': 'Morris', 'image': None, 'url': 'https://ballotpedia.org/Nate_Morris'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360397, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680243, 'name': 'Vincent Thompson', 'first_name': 'Vincent', 'last_name': 'Thompson', 'image': None, 'url': 'https://ballotpedia.org/Vincent_Thompson_(Kentucky)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368402, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689162, 'name': 'Logan Forsythe', 'first_name': 'Logan', 'last_name': 'Forsythe', 'image': None, 'url': 'https://ballotpedia.org/Logan_Forsythe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368403, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689163, 'name': 'Joel Willett', 'first_name': 'Joel', 'last_name': 'Willett', 'image': None, 'url': 'https://ballotpedia.org/Joel_Willett'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 169, 'name': 'Kentucky District 1', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64409, 'office': {'id': 9528, 'name': 'U.S. House Kentucky District 1', 'url': "https://ballotpedia.org/Kentucky's_1st_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 169, 'url': "https://ballotpedia.org/Kentucky's_1st_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308081, 'race': 64409, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 22719, 'name': 'James Comer Jr.', 'first_name': 'James', 'last_name': 'Comer', 'image': {'id': 66601, 'name': 'James_Comer.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James_Comer.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James_Comer.jpg'}, 'url': 'https://ballotpedia.org/James_Comer_Jr.'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365884, 'race': 64409, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294531, 'name': 'Drew Williams', 'first_name': 'Drew', 'last_name': 'Williams', 'image': {'id': 262173, 'name': 'DrewWilliams2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/DrewWilliams2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/DrewWilliams2025.jpg'}, 'url': 'https://ballotpedia.org/Drew_Williams'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}]}, {'id': 4145, 'name': 'Kentucky House of Representatives District 83', 'type': 'State Legislative (Lower)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 72696, 'office': {'id': 29158, 'name': 'Kentucky House of Representatives District 83', 'url': 'https://ballotpedia.org/Kentucky_House_of_Representatives_District_83', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 4145, 'url': 'https://ballotpedia.org/Kentucky_House_of_Representatives_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative (Lower)', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310435, 'race': 72696, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 322196, 'name': 'Joshua Branscum', 'first_name': 'Joshua', 'last_name': 'Branscum', 'image': {'id': 217615, 'name': 'Josh-Branscum.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Josh-Branscum.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Josh-Branscum.jpg'}, 'url': 'https://ballotpedia.org/Joshua_Branscum'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}]}]}, 'message': None}

Processing rows:  22%|███████████                                       | 11/50 [00:04<00:13,  2.85it/s]

{'success': True, 'data': {'districts': [{'id': 529, 'name': 'Kentucky', 'type': 'State', 'state': 'KY'}], 'polling_place_locator': {'url': 'https://vrsws.sos.ky.gov/vic/'}, 'elections': [{'date': '2026-05-19', 'candidate_lists_complete': False, 'districts': [{'id': 529, 'name': 'Kentucky', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62963, 'office': {'id': 1259, 'name': 'U.S. Senate Kentucky', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Kentucky', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 529, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Kentucky,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310208, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294606, 'name': 'Pamela Stevenson', 'first_name': 'Pamela', 'last_name': 'Stevenson', 'image': {'id': 165591, 'name': 'Pamela_Stevenson.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Pamela_Stevenson.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Pamela_Stevenson.jpg'}, 'url': 'https://ballotpedia.org/Pamela_Stevenson'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311153, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 626769, 'name': 'Wende Kennedy', 'first_name': 'Wende', 'last_name': 'Kennedy', 'image': None, 'url': 'https://ballotpedia.org/Wende_Kennedy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311272, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 308245, 'name': 'Daniel Cameron', 'first_name': 'Daniel', 'last_name': 'Cameron', 'image': {'id': 230697, 'name': 'dcameron3.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/dcameron3.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/dcameron3.jpg'}, 'url': 'https://ballotpedia.org/Daniel_Cameron'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329095, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 527799, 'name': 'Jared Randall', 'first_name': 'Jared', 'last_name': 'Randall', 'image': {'id': 237448, 'name': 'JaredRandall2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/JaredRandall2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/JaredRandall2024.jpeg'}, 'url': 'https://ballotpedia.org/Jared_Randall'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 346880, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 663270, 'name': 'Mike Faris', 'first_name': 'Mike', 'last_name': 'Faris', 'image': {'id': 258369, 'name': 'Mike_Faris_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Mike_Faris_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Mike_Faris_2025.jpeg'}, 'url': 'https://ballotpedia.org/Mike_Faris'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 354713, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 1846, 'name': 'Andy Barr', 'first_name': 'Andy', 'last_name': 'Barr', 'image': {'id': 105184, 'name': 'Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andy_Barr__official_portrait__113th_Congress-7_fixed.jpg'}, 'url': 'https://ballotpedia.org/Andy_Barr'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355784, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674750, 'name': 'Andrew Shelley', 'first_name': 'Andrew', 'last_name': 'Shelley', 'image': None, 'url': 'https://ballotpedia.org/Andrew_Shelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 359737, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679644, 'name': 'Nate Morris', 'first_name': 'Nate', 'last_name': 'Morris', 'image': None, 'url': 'https://ballotpedia.org/Nate_Morris'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360397, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680243, 'name': 'Vincent Thompson', 'first_name': 'Vincent', 'last_name': 'Thompson', 'image': None, 'url': 'https://ballotpedia.org/Vincent_Thompson_(Kentucky)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368402, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689162, 'name': 'Logan Forsythe', 'first_name': 'Logan', 'last_name': 'Forsythe', 'image': None, 'url': 'https://ballotpedia.org/Logan_Forsythe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368403, 'race': 62963, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689163, 'name': 'Joel Willett', 'first_name': 'Joel', 'last_name': 'Willett', 'image': None, 'url': 'https://ballotpedia.org/Joel_Willett'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 169, 'name': 'Kentucky District 1', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64409, 'office': {'id': 9528, 'name': 'U.S. House Kentucky District 1', 'url': "https://ballotpedia.org/Kentucky's_1st_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 169, 'url': "https://ballotpedia.org/Kentucky's_1st_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308081, 'race': 64409, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 22719, 'name': 'James Comer Jr.', 'first_name': 'James', 'last_name': 'Comer', 'image': {'id': 66601, 'name': 'James_Comer.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James_Comer.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James_Comer.jpg'}, 'url': 'https://ballotpedia.org/James_Comer_Jr.'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365884, 'race': 64409, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294531, 'name': 'Drew Williams', 'first_name': 'Drew', 'last_name': 'Williams', 'image': {'id': 262173, 'name': 'DrewWilliams2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/DrewWilliams2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/DrewWilliams2025.jpg'}, 'url': 'https://ballotpedia.org/Drew_Williams'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}]}, {'id': 4145, 'name': 'Kentucky House of Representatives District 83', 'type': 'State Legislative (Lower)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 72696, 'office': {'id': 29158, 'name': 'Kentucky House of Representatives District 83', 'url': 'https://ballotpedia.org/Kentucky_House_of_Representatives_District_83', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Closed', 'is_partisan': 'Partisan all'}, 'office_district': 4145, 'url': 'https://ballotpedia.org/Kentucky_House_of_Representatives_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative (Lower)', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310435, 'race': 72696, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 322196, 'name': 'Joshua Branscum', 'first_name': 'Joshua', 'last_name': 'Branscum', 'image': {'id': 217615, 'name': 'Josh-Branscum.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Josh-Branscum.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Josh-Branscum.jpg'}, 'url': 'https://ballotpedia.org/Joshua_Branscum'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}]}]}, 'message': None}

Processing rows:  24%|████████████                                      | 12/50 [00:04<00:15,  2.50it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  26%|█████████████                                     | 13/50 [00:05<00:15,  2.46it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  28%|██████████████                                    | 14/50 [00:05<00:15,  2.34it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  30%|███████████████                                   | 15/50 [00:06<00:15,  2.23it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  32%|████████████████                                  | 16/50 [00:06<00:16,  2.01it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  34%|█████████████████                                 | 17/50 [00:07<00:16,  1.96it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  36%|██████████████████                                | 18/50 [00:07<00:16,  1.96it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  38%|███████████████████                               | 19/50 [00:08<00:15,  1.95it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  40%|████████████████████                              | 20/50 [00:08<00:15,  1.98it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  42%|█████████████████████                             | 21/50 [00:09<00:15,  1.92it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  44%|██████████████████████                            | 22/50 [00:09<00:14,  1.98it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  46%|███████████████████████                           | 23/50 [00:10<00:13,  1.97it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  48%|████████████████████████                          | 24/50 [00:10<00:12,  2.03it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  50%|█████████████████████████                         | 25/50 [00:11<00:12,  2.08it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  52%|██████████████████████████                        | 26/50 [00:11<00:11,  2.11it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  54%|███████████████████████████                       | 27/50 [00:12<00:10,  2.20it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  56%|████████████████████████████                      | 28/50 [00:12<00:09,  2.22it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  58%|████████████████████████████▉                     | 29/50 [00:13<00:09,  2.19it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  60%|██████████████████████████████                    | 30/50 [00:13<00:08,  2.24it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  62%|███████████████████████████████                   | 31/50 [00:14<00:08,  2.21it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  64%|████████████████████████████████                  | 32/50 [00:14<00:08,  2.22it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  66%|█████████████████████████████████                 | 33/50 [00:14<00:07,  2.20it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  68%|██████████████████████████████████                | 34/50 [00:15<00:07,  2.12it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  70%|███████████████████████████████████               | 35/50 [00:15<00:06,  2.17it/s]

{'success': True, 'data': {'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'state': 'OH'}], 'polling_place_locator': {'url': 'https://voterlookup.ohiosos.gov/VoterLookup.aspx'}, 'elections': [{'date': '2026-05-05', 'candidate_lists_complete': False, 'districts': [{'id': 547, 'name': 'Ohio', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 76799, 'office': {'id': 1457, 'name': 'Governor of Ohio', 'url': 'https://ballotpedia.org/Governor_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_gubernatorial_and_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 308694, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 623618, 'name': 'Amy Acton', 'first_name': 'Amy', 'last_name': 'Acton', 'image': {'id': 252407, 'name': 'Amy_Acton_20250211_075037.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Amy_Acton_20250211_075037.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Amy_Acton_20250211_075037.jpg'}, 'url': 'https://ballotpedia.org/Amy_Acton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311234, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 400958, 'name': 'Vivek Ramaswamy', 'first_name': 'Vivek', 'last_name': 'Ramaswamy', 'image': {'id': 231854, 'name': 'ramaswamy24.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ramaswamy24.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ramaswamy24.jpg'}, 'url': 'https://ballotpedia.org/Vivek_Ramaswamy'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351045, 'race': 76799, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 667839, 'name': 'Heather Hill', 'first_name': 'Heather', 'last_name': 'Hill', 'image': {'id': 258780, 'name': 'HeatherHillOhio2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/HeatherHillOhio2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/HeatherHillOhio2025.jpg'}, 'url': 'https://ballotpedia.org/Heather_Hill_(Ohio)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76801, 'office': {'id': 6315, 'name': 'Ohio Treasurer', 'url': 'https://ballotpedia.org/Ohio_Treasurer', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Treasurer', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Treasurer_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310466, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 33147, 'name': 'Kristina Daley Roegner', 'first_name': 'Kristina', 'last_name': 'Roegner', 'image': {'id': 233422, 'name': 'Kristina_Roegner_20230531_084520.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Kristina_Roegner_20230531_084520.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Kristina_Roegner_20230531_084520.jpg'}, 'url': 'https://ballotpedia.org/Kristina_Daley_Roegner'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310678, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 42270, 'name': 'Niraj Antani', 'first_name': 'Niraj', 'last_name': 'Antani', 'image': {'id': 218063, 'name': 'Niraj-Antani.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Niraj-Antani.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Niraj-Antani.jpg'}, 'url': 'https://ballotpedia.org/Niraj_Antani'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351113, 'race': 76801, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 306168, 'name': 'Mike Zuren', 'first_name': 'Mike', 'last_name': 'Zuren', 'image': {'id': 259078, 'name': 'MikeZuren.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MikeZuren.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MikeZuren.jpg'}, 'url': 'https://ballotpedia.org/Mike_Zuren'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}]}, {'id': 76802, 'office': {'id': 8327, 'name': 'Ohio Secretary of State', 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Secretary of State', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Secretary_of_State_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310068, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 625467, 'name': 'Bryan Hambley', 'first_name': 'Bryan', 'last_name': 'Hambley', 'image': {'id': 257235, 'name': 'bhambley.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/bhambley.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/bhambley.jpg'}, 'url': 'https://ballotpedia.org/Bryan_Hambley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310253, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 47912, 'name': 'Robert Sprague', 'first_name': 'Robert', 'last_name': 'Sprague', 'image': {'id': 80920, 'name': 'Robert_Sprague.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Robert_Sprague.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Robert_Sprague.jpg'}, 'url': 'https://ballotpedia.org/Robert_Sprague'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355625, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 674460, 'name': 'Marcell Strbich', 'first_name': 'Marcell', 'last_name': 'Strbich', 'image': {'id': 259798, 'name': 'MarcellStrbich2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MarcellStrbich2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MarcellStrbich2025.png'}, 'url': 'https://ballotpedia.org/Marcell_Strbich'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361706, 'race': 76802, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 294872, 'name': 'Allison Russo', 'first_name': 'Allison', 'last_name': 'Russo', 'image': {'id': 232317, 'name': 'AllisonRussoOH.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AllisonRussoOH.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AllisonRussoOH.jpg'}, 'url': 'https://ballotpedia.org/Allison_Russo'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76803, 'office': {'id': 12999, 'name': 'Ohio Auditor of State', 'url': 'https://ballotpedia.org/Ohio_Auditor_of_State', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Auditor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Auditor_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310257, 'race': 76803, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 18321, 'name': 'Frank LaRose', 'first_name': 'Frank', 'last_name': 'LaRose', 'image': {'id': 230417, 'name': 'flarose2.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/flarose2.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/flarose2.jpg'}, 'url': 'https://ballotpedia.org/Frank_LaRose'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76804, 'office': {'id': 13617, 'name': 'Attorney General of Ohio', 'url': 'https://ballotpedia.org/Attorney_General_of_Ohio', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Attorney General', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/Ohio_Attorney_General_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310134, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31537, 'name': 'Keith Faber', 'first_name': 'Keith', 'last_name': 'Faber', 'image': {'id': 174667, 'name': 'Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Screen_Shot_2018-10-01_at_9.08.19_AM.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Screen_Shot_2018-10-01_at_9.08.19_AM.png'}, 'url': 'https://ballotpedia.org/Keith_Faber'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 311519, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 351339, 'name': 'Elliot Forhan', 'first_name': 'Elliot', 'last_name': 'Forhan', 'image': {'id': 225272, 'name': 'Elliot_Forhan.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Elliot_Forhan.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Elliot_Forhan.jpg'}, 'url': 'https://ballotpedia.org/Elliot_Forhan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 368559, 'race': 76804, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 689411, 'name': 'John Kulewicz', 'first_name': 'John', 'last_name': 'Kulewicz', 'image': None, 'url': 'https://ballotpedia.org/John_Kulewicz'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 177358, 'office': {'id': 13762, 'name': 'U.S. Senate Ohio', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Ohio', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 547, 'url': 'https://ballotpedia.org/United_States_Senate_special_election_in_Ohio,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Special', 'candidates': [{'id': 310137, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 331053, 'name': 'William Farms', 'first_name': 'William', 'last_name': 'Farms', 'image': None, 'url': 'https://ballotpedia.org/William_Farms'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 310244, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 29073, 'name': 'Jon Husted', 'first_name': 'Jon', 'last_name': 'Husted', 'image': {'id': 70228, 'name': 'Jon_Husted_2013.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Jon_Husted_2013.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Jon_Husted_2013.jpg'}, 'url': 'https://ballotpedia.org/Jon_Husted'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 346860, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624483, 'name': 'Brian Bibler', 'first_name': 'Brian', 'last_name': 'Bibler', 'image': None, 'url': 'https://ballotpedia.org/Brian_Bibler'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 353530, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 670704, 'name': 'Lynnea Lau', 'first_name': 'Lynnea', 'last_name': 'Lau', 'image': None, 'url': 'https://ballotpedia.org/Lynnea_Lau'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354717, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 673188, 'name': 'Christopher Volpe', 'first_name': 'Christopher', 'last_name': 'Volpe', 'image': None, 'url': 'https://ballotpedia.org/Christopher_Volpe'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356972, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676921, 'name': 'Ron Kincaid', 'first_name': 'Ron', 'last_name': 'Kincaid', 'image': None, 'url': 'https://ballotpedia.org/Ron_Kincaid'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 360444, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 51550, 'name': 'Sherrod Brown', 'first_name': 'Sherrod', 'last_name': 'Brown', 'image': {'id': 82944, 'name': 'Sherrod_Brown.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Sherrod_Brown.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Sherrod_Brown.jpg'}, 'url': 'https://ballotpedia.org/Sherrod_Brown'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 361694, 'race': 177358, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 681733, 'name': 'Fred Ode', 'first_name': 'Fred', 'last_name': 'Ode', 'image': None, 'url': 'https://ballotpedia.org/Fred_Ode'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 304, 'name': 'Ohio District 5', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 64545, 'office': {'id': 4216, 'name': 'U.S. House Ohio District 5', 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District", 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Lower', 'type': 'Representative', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 304, 'url': "https://ballotpedia.org/Ohio's_5th_Congressional_District_election,_2026", 'stage_type': 'Primary', 'district_type': 'Congress', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 310141, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 5004, 'name': 'Bob Latta', 'first_name': 'Bob', 'last_name': 'Latta', 'image': {'id': 56810, 'name': 'Bob_Latta.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bob_Latta.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bob_Latta.jpg'}, 'url': 'https://ballotpedia.org/Bob_Latta'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354409, 'race': 64545, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 672511, 'name': 'Erica Kelley', 'first_name': 'Erica', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Erica_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}]}, {'id': 1942, 'name': 'Ohio State Senate District 1', 'type': 'State Legislative (Upper)', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 74879, 'office': {'id': 2966, 'name': 'Ohio State Senate District 1', 'url': 'https://ballotpedia.org/Ohio_State_Senate_District_1', 'level': 'State', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 1942, 'url': 'https://ballotpedia.org/Ohio_State_Senate_elections,_2026', 'stage_type': 'Primary', 'district_type': 'State Legislative

Processing rows:  72%|████████████████████████████████████              | 36/50 [00:16<00:06,  2.13it/s]

{'success': True, 'data': {'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'state': 'TX'}], 'polling_place_locator': {'url': 'https://teamrv-mvp.sos.texas.gov/MVP/mvp.do'}, 'elections': [{'date': '2025-11-04', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27986, 'name': 'Texas Proposition 10, Property Tax Exemption for Improvements to Homestead Destroyed by Fire Amendment (2025)', 'district_type': 'State'}, {'id': 27976, 'name': 'Texas Proposition 11, Increase Homestead Tax Exemption for Elderly and Disabled Amendment (2025)', 'district_type': 'State'}, {'id': 28007, 'name': 'Texas Proposition 12, Change Membership and Authority of State Commission on Judicial Conduct Amendment (2025)', 'district_type': 'State'}, {'id': 27975, 'name': 'Texas Proposition 13, Increase Homestead Property Tax Exemption Amendment (2025)', 'district_type': 'State'}, {'id': 27950, 'name': 'Texas Proposition 14, Establish Dementia Prevention and Research Institute of Texas Amendment (2025)', 'district_type': 'State'}, {'id': 27967, 'name': 'Texas Proposition 15, Parental Rights Amendment (2025)', 'district_type': 'State'}, {'id': 27948, 'name': 'Texas Proposition 16, Citizenship Voting Requirement Amendment (2025)', 'district_type': 'State'}, {'id': 27974, 'name': 'Texas Proposition 17, Property Tax Exemption for Border Security Infrastructure Amendment (2025)', 'district_type': 'State'}, {'id': 27998, 'name': 'Texas Proposition 1, Establish Special Funds for State Technical College System Amendment (2025)', 'district_type': 'State'}, {'id': 27944, 'name': 'Texas Proposition 2, Prohibit Capital Gains Tax on Individuals, Estates, and Trusts Amendment (2025)', 'district_type': 'State'}, {'id': 28006, 'name': 'Texas Proposition 3, Denial of Bail for Certain Violent or Sexual Offenses Punishable as a Felony Amendment (2025)', 'district_type': 'State'}, {'id': 28005, 'name': 'Texas Proposition 4, Allocate Portion of Sales Tax Revenue to Water Fund Amendment (2025)', 'district_type': 'State'}, {'id': 27951, 'name': 'Texas Proposition 5, Property Tax Exemption on Retail Animal Feed Amendment (2025)', 'district_type': 'State'}, {'id': 27932, 'name': 'Texas Proposition 6, Prohibit Taxes on Certain Securities Transactions Amendment (2025)', 'district_type': 'State'}, {'id': 27985, 'name': 'Texas Proposition 7, Establish Homestead Exemption for Surviving Spouses of Veterans Killed by a Service-Connected Disease Amendment (2025)', 'district_type': 'State'}, {'id': 27949, 'name': 'Texas Proposition 8, Prohibit Estate Taxes and New Taxes on Estate Transfers, Inheritances, and Gifts Amendment (2025)', 'district_type': 'State'}, {'id': 27958, 'name': 'Texas Proposition 9, Authorize $125,000 Tax Exemption for Tangible Property Used for Income Production Amendment (2025)', 'district_type': 'State'}], 'races': None}]}, {'date': '2026-03-03', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62982, 'office': {'id': 1150, 'name': 'U.S. Senate Texas', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Texas', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Texas,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 194592, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 480284, 'name': 'Rennie Mann', 'first_name': 'Rennie', 'last_name': 'Mann', 'image': {'id': 259440, 'name': 'Rennie_Mann_20250529_012636.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Rennie_Mann_20250529_012636.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Rennie_Mann_20250529_012636.jpg'}, 'url': 'https://ballotpedia.org/Rennie_Mann'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 264716, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 27527, 'name': 'John Cornyn', 'first_name': 'John', 'last_name': 'Cornyn', 'image': {'id': 69348, 'name': 'John_Cornyn.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/John_Cornyn.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/John_Cornyn.jpg'}, 'url': 'https://ballotpedia.org/John_Cornyn'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 307578, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 622164, 'name': 'Leo Wyatt', 'first_name': 'Leo', 'last_name': 'Wyatt', 'image': None, 'url': 'https://ballotpedia.org/Leo_Wyatt'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 308697, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 623620, 'name': 'Tony Schmoker', 'first_name': 'Tony', 'last_name': 'Schmoker', 'image': {'id': 258791, 'name': 'TonySchmoker2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/TonySchmoker2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/TonySchmoker2025.jpg'}, 'url': 'https://ballotpedia.org/Tony_Schmoker'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 309436, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624675, 'name': 'Alexander Duncan', 'first_name': 'Alexander', 'last_name': 'Duncan', 'image': {'id': 248352, 'name': 'AlexanderDuncan_TX.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AlexanderDuncan_TX.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AlexanderDuncan_TX.jpeg'}, 'url': 'https://ballotpedia.org/Alexander_Duncan_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310070, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 625468, 'name': 'Barrett McNabb', 'first_name': 'Barrett', 'last_name': 'McNabb', 'image': {'id': 257306, 'name': 'Barrett_McNabb_20250307_031108.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Barrett_McNabb_20250307_031108.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Barrett_McNabb_20250307_031108.png'}, 'url': 'https://ballotpedia.org/Barrett_McNabb'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329097, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 349024, 'name': 'Gulrez Khan', 'first_name': 'Gulrez', 'last_name': 'Khan', 'image': {'id': 259487, 'name': 'Gulrez_Khan_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Gulrez_Khan_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Gulrez_Khan_2025.jpeg'}, 'url': 'https://ballotpedia.org/Gulrez_Khan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 347628, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31934, 'name': 'Ken Paxton', 'first_name': 'Ken', 'last_name': 'Paxton', 'image': {'id': 213529, 'name': 'Ken-Paxton.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ken-Paxton.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ken-Paxton.jpg'}, 'url': 'https://ballotpedia.org/Ken_Paxton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 348603, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 336399, 'name': 'Andrew Alvarez', 'first_name': 'Andrew', 'last_name': 'Alvarez', 'image': {'id': 221333, 'name': 'Andrew_Alvarez1.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andrew_Alvarez1.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andrew_Alvarez1.png'}, 'url': 'https://ballotpedia.org/Andrew_Alvarez_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351082, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 667895, 'name': 'Michael Swanson', 'first_name': 'Michael', 'last_name': 'Swanson', 'image': {'id': 259267, 'name': 'Michael_Swanson_2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Michael_Swanson_2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Michael_Swanson_2025.jpg'}, 'url': 'https://ballotpedia.org/Michael_Swanson_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354059, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 671153, 'name': 'Matthew Elliot Kelley', 'first_name': 'Matthew Elliot', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Matthew_Elliot_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355726, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 320691, 'name': 'Virgil Bierschwale', 'first_name': 'Virgil', 'last_name': 'Bierschwale', 'image': {'id': 260203, 'name': 'vbierschwale.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/vbierschwale.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/vbierschwale.jpg'}, 'url': 'https://ballotpedia.org/Virgil_Bierschwale'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356111, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675163, 'name': 'Terry Virts', 'first_name': 'Terry', 'last_name': 'Virts', 'image': None, 'url': 'https://ballotpedia.org/Terry_Virts'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356310, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 287100, 'name': 'Colin Allred', 'first_name': 'Colin', 'last_name': 'Allred', 'image': {'id': 237057, 'name': 'ColinAllred2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ColinAllred2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ColinAllred2024.jpeg'}, 'url': 'https://ballotpedia.org/Colin_Allred'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359785, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 679722, 'name': 'Emily Morgul', 'first_name': 'Emily', 'last_name': 'Morgul', 'image': {'id': 261421, 'name': 'Emily_Morgul_20250805_042926.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Emily_Morgul_20250805_042926.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Emily_Morgul_20250805_042926.jpeg'}, 'url': 'https://ballotpedia.org/Emily_Morgul'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359787, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679723, 'name': 'Ronald Evans', 'first_name': 'Ronald', 'last_name': 'Evans', 'image': None, 'url': 'https://ballotpedia.org/Ronald_Evans'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365873, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 293105, 'name': 'James Talarico', 'first_name': 'James', 'last_name': 'Talarico', 'image': {'id': 213740, 'name': 'James-Talarico.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James-Talarico.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James-Talarico.jpg'}, 'url': 'https://ballotpedia.org/James_Talarico'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76845, 'office': {'id': 690, 'name': 'Governor of Texas', 'url': 'https://ballotpedia.org/Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 356163, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675192, 'name': 'Bobby Cole', 'first_name': 'Bobby', 'last_name': 'Cole', 'image': {'id': 260839, 'name': 'Bobby_Cole_20250710_120937.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bobby_Cole_20250710_120937.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bobby_Cole_20250710_120937.jpg'}, 'url': 'https://ballotpedia.org/Bobby_Cole'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356465, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 342856, 'name': 'Ronnie Tullos', 'first_name': 'Ronnie', 'last_name': 'Tullos', 'image': {'id': 240369, 'name': 'Ronnie_Bubba_Tullos_20240808_094757.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ronnie_Bubba_Tullos_20240808_094757.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ronnie_Bubba_Tullos_20240808_094757.jpg'}, 'url': 'https://ballotpedia.org/Ronnie_Tullos'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356626, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676637, 'name': 'Meagan Tehseldar', 'first_name': 'Meagan', 'last_name': 'Tehseldar', 'image': {'id': 261171, 'name': 'MeaganTehseldar2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MeaganTehseldar2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MeaganTehseldar2025.png'}, 'url': 'https://ballotpedia.org/Meagan_Tehseldar'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 360436, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680292, 'name': 'Nick Pappas', 'first_name': 'Nick', 'last_name': 'Pappas', 'image': {'id': 261729, 'name': 'Nick_Pappas_25.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Nick_Pappas_25.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Nick_Pappas_25.jpeg'}, 'url': 'https://ballotpedia.org/Nick_Pappas'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361281, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 20241, 'name': 'Greg Abbott', 'first_name': 'Greg', 'last_name': 'Abbott', 'image': {'id': 65280, 'name': 'GregAbbott2015.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/GregAbbott2015.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/GregAbbott2015.jpg'}, 'url': 'https://ballotpedia.org/Greg_Abbott'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76846, 'office': {'id': 12974, 'name': 'Lieutenant Governor of Texas', 'url': 'https://ballotpedia.org/Lieutenant_Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Lieutenant Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 179947, 'race': 76846, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 11132, 'name': 'Dan Patrick', 'first_name': 'Dan', 'last_name': 'Patrick', 'image': {'id': 60278, 'name': 'Dan_Patrick.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaw

Processing rows:  74%|█████████████████████████████████████             | 37/50 [00:16<00:06,  2.10it/s]

{'success': True, 'data': {'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'state': 'TX'}], 'polling_place_locator': {'url': 'https://teamrv-mvp.sos.texas.gov/MVP/mvp.do'}, 'elections': [{'date': '2025-11-04', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27986, 'name': 'Texas Proposition 10, Property Tax Exemption for Improvements to Homestead Destroyed by Fire Amendment (2025)', 'district_type': 'State'}, {'id': 27976, 'name': 'Texas Proposition 11, Increase Homestead Tax Exemption for Elderly and Disabled Amendment (2025)', 'district_type': 'State'}, {'id': 28007, 'name': 'Texas Proposition 12, Change Membership and Authority of State Commission on Judicial Conduct Amendment (2025)', 'district_type': 'State'}, {'id': 27975, 'name': 'Texas Proposition 13, Increase Homestead Property Tax Exemption Amendment (2025)', 'district_type': 'State'}, {'id': 27950, 'name': 'Texas Proposition 14, Establish Dementia Prevention and Research Institute of Texas Amendment (2025)', 'district_type': 'State'}, {'id': 27967, 'name': 'Texas Proposition 15, Parental Rights Amendment (2025)', 'district_type': 'State'}, {'id': 27948, 'name': 'Texas Proposition 16, Citizenship Voting Requirement Amendment (2025)', 'district_type': 'State'}, {'id': 27974, 'name': 'Texas Proposition 17, Property Tax Exemption for Border Security Infrastructure Amendment (2025)', 'district_type': 'State'}, {'id': 27998, 'name': 'Texas Proposition 1, Establish Special Funds for State Technical College System Amendment (2025)', 'district_type': 'State'}, {'id': 27944, 'name': 'Texas Proposition 2, Prohibit Capital Gains Tax on Individuals, Estates, and Trusts Amendment (2025)', 'district_type': 'State'}, {'id': 28006, 'name': 'Texas Proposition 3, Denial of Bail for Certain Violent or Sexual Offenses Punishable as a Felony Amendment (2025)', 'district_type': 'State'}, {'id': 28005, 'name': 'Texas Proposition 4, Allocate Portion of Sales Tax Revenue to Water Fund Amendment (2025)', 'district_type': 'State'}, {'id': 27951, 'name': 'Texas Proposition 5, Property Tax Exemption on Retail Animal Feed Amendment (2025)', 'district_type': 'State'}, {'id': 27932, 'name': 'Texas Proposition 6, Prohibit Taxes on Certain Securities Transactions Amendment (2025)', 'district_type': 'State'}, {'id': 27985, 'name': 'Texas Proposition 7, Establish Homestead Exemption for Surviving Spouses of Veterans Killed by a Service-Connected Disease Amendment (2025)', 'district_type': 'State'}, {'id': 27949, 'name': 'Texas Proposition 8, Prohibit Estate Taxes and New Taxes on Estate Transfers, Inheritances, and Gifts Amendment (2025)', 'district_type': 'State'}, {'id': 27958, 'name': 'Texas Proposition 9, Authorize $125,000 Tax Exemption for Tangible Property Used for Income Production Amendment (2025)', 'district_type': 'State'}], 'races': None}]}, {'date': '2026-03-03', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62982, 'office': {'id': 1150, 'name': 'U.S. Senate Texas', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Texas', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Texas,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 194592, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 480284, 'name': 'Rennie Mann', 'first_name': 'Rennie', 'last_name': 'Mann', 'image': {'id': 259440, 'name': 'Rennie_Mann_20250529_012636.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Rennie_Mann_20250529_012636.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Rennie_Mann_20250529_012636.jpg'}, 'url': 'https://ballotpedia.org/Rennie_Mann'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 264716, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 27527, 'name': 'John Cornyn', 'first_name': 'John', 'last_name': 'Cornyn', 'image': {'id': 69348, 'name': 'John_Cornyn.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/John_Cornyn.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/John_Cornyn.jpg'}, 'url': 'https://ballotpedia.org/John_Cornyn'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 307578, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 622164, 'name': 'Leo Wyatt', 'first_name': 'Leo', 'last_name': 'Wyatt', 'image': None, 'url': 'https://ballotpedia.org/Leo_Wyatt'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 308697, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 623620, 'name': 'Tony Schmoker', 'first_name': 'Tony', 'last_name': 'Schmoker', 'image': {'id': 258791, 'name': 'TonySchmoker2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/TonySchmoker2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/TonySchmoker2025.jpg'}, 'url': 'https://ballotpedia.org/Tony_Schmoker'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 309436, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624675, 'name': 'Alexander Duncan', 'first_name': 'Alexander', 'last_name': 'Duncan', 'image': {'id': 248352, 'name': 'AlexanderDuncan_TX.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AlexanderDuncan_TX.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AlexanderDuncan_TX.jpeg'}, 'url': 'https://ballotpedia.org/Alexander_Duncan_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310070, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 625468, 'name': 'Barrett McNabb', 'first_name': 'Barrett', 'last_name': 'McNabb', 'image': {'id': 257306, 'name': 'Barrett_McNabb_20250307_031108.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Barrett_McNabb_20250307_031108.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Barrett_McNabb_20250307_031108.png'}, 'url': 'https://ballotpedia.org/Barrett_McNabb'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329097, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 349024, 'name': 'Gulrez Khan', 'first_name': 'Gulrez', 'last_name': 'Khan', 'image': {'id': 259487, 'name': 'Gulrez_Khan_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Gulrez_Khan_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Gulrez_Khan_2025.jpeg'}, 'url': 'https://ballotpedia.org/Gulrez_Khan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 347628, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31934, 'name': 'Ken Paxton', 'first_name': 'Ken', 'last_name': 'Paxton', 'image': {'id': 213529, 'name': 'Ken-Paxton.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ken-Paxton.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ken-Paxton.jpg'}, 'url': 'https://ballotpedia.org/Ken_Paxton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 348603, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 336399, 'name': 'Andrew Alvarez', 'first_name': 'Andrew', 'last_name': 'Alvarez', 'image': {'id': 221333, 'name': 'Andrew_Alvarez1.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andrew_Alvarez1.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andrew_Alvarez1.png'}, 'url': 'https://ballotpedia.org/Andrew_Alvarez_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351082, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 667895, 'name': 'Michael Swanson', 'first_name': 'Michael', 'last_name': 'Swanson', 'image': {'id': 259267, 'name': 'Michael_Swanson_2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Michael_Swanson_2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Michael_Swanson_2025.jpg'}, 'url': 'https://ballotpedia.org/Michael_Swanson_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354059, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 671153, 'name': 'Matthew Elliot Kelley', 'first_name': 'Matthew Elliot', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Matthew_Elliot_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355726, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 320691, 'name': 'Virgil Bierschwale', 'first_name': 'Virgil', 'last_name': 'Bierschwale', 'image': {'id': 260203, 'name': 'vbierschwale.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/vbierschwale.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/vbierschwale.jpg'}, 'url': 'https://ballotpedia.org/Virgil_Bierschwale'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356111, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675163, 'name': 'Terry Virts', 'first_name': 'Terry', 'last_name': 'Virts', 'image': None, 'url': 'https://ballotpedia.org/Terry_Virts'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356310, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 287100, 'name': 'Colin Allred', 'first_name': 'Colin', 'last_name': 'Allred', 'image': {'id': 237057, 'name': 'ColinAllred2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ColinAllred2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ColinAllred2024.jpeg'}, 'url': 'https://ballotpedia.org/Colin_Allred'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359785, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 679722, 'name': 'Emily Morgul', 'first_name': 'Emily', 'last_name': 'Morgul', 'image': {'id': 261421, 'name': 'Emily_Morgul_20250805_042926.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Emily_Morgul_20250805_042926.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Emily_Morgul_20250805_042926.jpeg'}, 'url': 'https://ballotpedia.org/Emily_Morgul'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359787, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679723, 'name': 'Ronald Evans', 'first_name': 'Ronald', 'last_name': 'Evans', 'image': None, 'url': 'https://ballotpedia.org/Ronald_Evans'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365873, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 293105, 'name': 'James Talarico', 'first_name': 'James', 'last_name': 'Talarico', 'image': {'id': 213740, 'name': 'James-Talarico.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James-Talarico.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James-Talarico.jpg'}, 'url': 'https://ballotpedia.org/James_Talarico'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76845, 'office': {'id': 690, 'name': 'Governor of Texas', 'url': 'https://ballotpedia.org/Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 356163, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675192, 'name': 'Bobby Cole', 'first_name': 'Bobby', 'last_name': 'Cole', 'image': {'id': 260839, 'name': 'Bobby_Cole_20250710_120937.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bobby_Cole_20250710_120937.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bobby_Cole_20250710_120937.jpg'}, 'url': 'https://ballotpedia.org/Bobby_Cole'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356465, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 342856, 'name': 'Ronnie Tullos', 'first_name': 'Ronnie', 'last_name': 'Tullos', 'image': {'id': 240369, 'name': 'Ronnie_Bubba_Tullos_20240808_094757.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ronnie_Bubba_Tullos_20240808_094757.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ronnie_Bubba_Tullos_20240808_094757.jpg'}, 'url': 'https://ballotpedia.org/Ronnie_Tullos'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356626, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676637, 'name': 'Meagan Tehseldar', 'first_name': 'Meagan', 'last_name': 'Tehseldar', 'image': {'id': 261171, 'name': 'MeaganTehseldar2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MeaganTehseldar2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MeaganTehseldar2025.png'}, 'url': 'https://ballotpedia.org/Meagan_Tehseldar'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 360436, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680292, 'name': 'Nick Pappas', 'first_name': 'Nick', 'last_name': 'Pappas', 'image': {'id': 261729, 'name': 'Nick_Pappas_25.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Nick_Pappas_25.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Nick_Pappas_25.jpeg'}, 'url': 'https://ballotpedia.org/Nick_Pappas'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361281, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 20241, 'name': 'Greg Abbott', 'first_name': 'Greg', 'last_name': 'Abbott', 'image': {'id': 65280, 'name': 'GregAbbott2015.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/GregAbbott2015.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/GregAbbott2015.jpg'}, 'url': 'https://ballotpedia.org/Greg_Abbott'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76846, 'office': {'id': 12974, 'name': 'Lieutenant Governor of Texas', 'url': 'https://ballotpedia.org/Lieutenant_Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Lieutenant Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 179947, 'race': 76846, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 11132, 'name': 'Dan Patrick', 'first_name': 'Dan', 'last_name': 'Patrick', 'image': {'id': 60278, 'name': 'Dan_Patrick.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaw

Processing rows:  76%|██████████████████████████████████████            | 38/50 [00:17<00:05,  2.06it/s]

{'success': True, 'data': {'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'state': 'TX'}], 'polling_place_locator': {'url': 'https://teamrv-mvp.sos.texas.gov/MVP/mvp.do'}, 'elections': [{'date': '2025-11-04', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27986, 'name': 'Texas Proposition 10, Property Tax Exemption for Improvements to Homestead Destroyed by Fire Amendment (2025)', 'district_type': 'State'}, {'id': 27976, 'name': 'Texas Proposition 11, Increase Homestead Tax Exemption for Elderly and Disabled Amendment (2025)', 'district_type': 'State'}, {'id': 28007, 'name': 'Texas Proposition 12, Change Membership and Authority of State Commission on Judicial Conduct Amendment (2025)', 'district_type': 'State'}, {'id': 27975, 'name': 'Texas Proposition 13, Increase Homestead Property Tax Exemption Amendment (2025)', 'district_type': 'State'}, {'id': 27950, 'name': 'Texas Proposition 14, Establish Dementia Prevention and Research Institute of Texas Amendment (2025)', 'district_type': 'State'}, {'id': 27967, 'name': 'Texas Proposition 15, Parental Rights Amendment (2025)', 'district_type': 'State'}, {'id': 27948, 'name': 'Texas Proposition 16, Citizenship Voting Requirement Amendment (2025)', 'district_type': 'State'}, {'id': 27974, 'name': 'Texas Proposition 17, Property Tax Exemption for Border Security Infrastructure Amendment (2025)', 'district_type': 'State'}, {'id': 27998, 'name': 'Texas Proposition 1, Establish Special Funds for State Technical College System Amendment (2025)', 'district_type': 'State'}, {'id': 27944, 'name': 'Texas Proposition 2, Prohibit Capital Gains Tax on Individuals, Estates, and Trusts Amendment (2025)', 'district_type': 'State'}, {'id': 28006, 'name': 'Texas Proposition 3, Denial of Bail for Certain Violent or Sexual Offenses Punishable as a Felony Amendment (2025)', 'district_type': 'State'}, {'id': 28005, 'name': 'Texas Proposition 4, Allocate Portion of Sales Tax Revenue to Water Fund Amendment (2025)', 'district_type': 'State'}, {'id': 27951, 'name': 'Texas Proposition 5, Property Tax Exemption on Retail Animal Feed Amendment (2025)', 'district_type': 'State'}, {'id': 27932, 'name': 'Texas Proposition 6, Prohibit Taxes on Certain Securities Transactions Amendment (2025)', 'district_type': 'State'}, {'id': 27985, 'name': 'Texas Proposition 7, Establish Homestead Exemption for Surviving Spouses of Veterans Killed by a Service-Connected Disease Amendment (2025)', 'district_type': 'State'}, {'id': 27949, 'name': 'Texas Proposition 8, Prohibit Estate Taxes and New Taxes on Estate Transfers, Inheritances, and Gifts Amendment (2025)', 'district_type': 'State'}, {'id': 27958, 'name': 'Texas Proposition 9, Authorize $125,000 Tax Exemption for Tangible Property Used for Income Production Amendment (2025)', 'district_type': 'State'}], 'races': None}]}, {'date': '2026-03-03', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62982, 'office': {'id': 1150, 'name': 'U.S. Senate Texas', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Texas', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Texas,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 194592, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 480284, 'name': 'Rennie Mann', 'first_name': 'Rennie', 'last_name': 'Mann', 'image': {'id': 259440, 'name': 'Rennie_Mann_20250529_012636.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Rennie_Mann_20250529_012636.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Rennie_Mann_20250529_012636.jpg'}, 'url': 'https://ballotpedia.org/Rennie_Mann'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 264716, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 27527, 'name': 'John Cornyn', 'first_name': 'John', 'last_name': 'Cornyn', 'image': {'id': 69348, 'name': 'John_Cornyn.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/John_Cornyn.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/John_Cornyn.jpg'}, 'url': 'https://ballotpedia.org/John_Cornyn'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 307578, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 622164, 'name': 'Leo Wyatt', 'first_name': 'Leo', 'last_name': 'Wyatt', 'image': None, 'url': 'https://ballotpedia.org/Leo_Wyatt'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 308697, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 623620, 'name': 'Tony Schmoker', 'first_name': 'Tony', 'last_name': 'Schmoker', 'image': {'id': 258791, 'name': 'TonySchmoker2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/TonySchmoker2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/TonySchmoker2025.jpg'}, 'url': 'https://ballotpedia.org/Tony_Schmoker'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 309436, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624675, 'name': 'Alexander Duncan', 'first_name': 'Alexander', 'last_name': 'Duncan', 'image': {'id': 248352, 'name': 'AlexanderDuncan_TX.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AlexanderDuncan_TX.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AlexanderDuncan_TX.jpeg'}, 'url': 'https://ballotpedia.org/Alexander_Duncan_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310070, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 625468, 'name': 'Barrett McNabb', 'first_name': 'Barrett', 'last_name': 'McNabb', 'image': {'id': 257306, 'name': 'Barrett_McNabb_20250307_031108.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Barrett_McNabb_20250307_031108.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Barrett_McNabb_20250307_031108.png'}, 'url': 'https://ballotpedia.org/Barrett_McNabb'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329097, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 349024, 'name': 'Gulrez Khan', 'first_name': 'Gulrez', 'last_name': 'Khan', 'image': {'id': 259487, 'name': 'Gulrez_Khan_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Gulrez_Khan_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Gulrez_Khan_2025.jpeg'}, 'url': 'https://ballotpedia.org/Gulrez_Khan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 347628, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31934, 'name': 'Ken Paxton', 'first_name': 'Ken', 'last_name': 'Paxton', 'image': {'id': 213529, 'name': 'Ken-Paxton.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ken-Paxton.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ken-Paxton.jpg'}, 'url': 'https://ballotpedia.org/Ken_Paxton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 348603, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 336399, 'name': 'Andrew Alvarez', 'first_name': 'Andrew', 'last_name': 'Alvarez', 'image': {'id': 221333, 'name': 'Andrew_Alvarez1.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andrew_Alvarez1.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andrew_Alvarez1.png'}, 'url': 'https://ballotpedia.org/Andrew_Alvarez_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351082, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 667895, 'name': 'Michael Swanson', 'first_name': 'Michael', 'last_name': 'Swanson', 'image': {'id': 259267, 'name': 'Michael_Swanson_2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Michael_Swanson_2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Michael_Swanson_2025.jpg'}, 'url': 'https://ballotpedia.org/Michael_Swanson_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354059, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 671153, 'name': 'Matthew Elliot Kelley', 'first_name': 'Matthew Elliot', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Matthew_Elliot_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355726, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 320691, 'name': 'Virgil Bierschwale', 'first_name': 'Virgil', 'last_name': 'Bierschwale', 'image': {'id': 260203, 'name': 'vbierschwale.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/vbierschwale.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/vbierschwale.jpg'}, 'url': 'https://ballotpedia.org/Virgil_Bierschwale'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356111, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675163, 'name': 'Terry Virts', 'first_name': 'Terry', 'last_name': 'Virts', 'image': None, 'url': 'https://ballotpedia.org/Terry_Virts'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356310, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 287100, 'name': 'Colin Allred', 'first_name': 'Colin', 'last_name': 'Allred', 'image': {'id': 237057, 'name': 'ColinAllred2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ColinAllred2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ColinAllred2024.jpeg'}, 'url': 'https://ballotpedia.org/Colin_Allred'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359785, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 679722, 'name': 'Emily Morgul', 'first_name': 'Emily', 'last_name': 'Morgul', 'image': {'id': 261421, 'name': 'Emily_Morgul_20250805_042926.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Emily_Morgul_20250805_042926.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Emily_Morgul_20250805_042926.jpeg'}, 'url': 'https://ballotpedia.org/Emily_Morgul'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359787, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679723, 'name': 'Ronald Evans', 'first_name': 'Ronald', 'last_name': 'Evans', 'image': None, 'url': 'https://ballotpedia.org/Ronald_Evans'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365873, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 293105, 'name': 'James Talarico', 'first_name': 'James', 'last_name': 'Talarico', 'image': {'id': 213740, 'name': 'James-Talarico.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James-Talarico.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James-Talarico.jpg'}, 'url': 'https://ballotpedia.org/James_Talarico'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76845, 'office': {'id': 690, 'name': 'Governor of Texas', 'url': 'https://ballotpedia.org/Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 356163, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675192, 'name': 'Bobby Cole', 'first_name': 'Bobby', 'last_name': 'Cole', 'image': {'id': 260839, 'name': 'Bobby_Cole_20250710_120937.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bobby_Cole_20250710_120937.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bobby_Cole_20250710_120937.jpg'}, 'url': 'https://ballotpedia.org/Bobby_Cole'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356465, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 342856, 'name': 'Ronnie Tullos', 'first_name': 'Ronnie', 'last_name': 'Tullos', 'image': {'id': 240369, 'name': 'Ronnie_Bubba_Tullos_20240808_094757.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ronnie_Bubba_Tullos_20240808_094757.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ronnie_Bubba_Tullos_20240808_094757.jpg'}, 'url': 'https://ballotpedia.org/Ronnie_Tullos'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356626, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676637, 'name': 'Meagan Tehseldar', 'first_name': 'Meagan', 'last_name': 'Tehseldar', 'image': {'id': 261171, 'name': 'MeaganTehseldar2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MeaganTehseldar2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MeaganTehseldar2025.png'}, 'url': 'https://ballotpedia.org/Meagan_Tehseldar'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 360436, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680292, 'name': 'Nick Pappas', 'first_name': 'Nick', 'last_name': 'Pappas', 'image': {'id': 261729, 'name': 'Nick_Pappas_25.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Nick_Pappas_25.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Nick_Pappas_25.jpeg'}, 'url': 'https://ballotpedia.org/Nick_Pappas'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361281, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 20241, 'name': 'Greg Abbott', 'first_name': 'Greg', 'last_name': 'Abbott', 'image': {'id': 65280, 'name': 'GregAbbott2015.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/GregAbbott2015.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/GregAbbott2015.jpg'}, 'url': 'https://ballotpedia.org/Greg_Abbott'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76846, 'office': {'id': 12974, 'name': 'Lieutenant Governor of Texas', 'url': 'https://ballotpedia.org/Lieutenant_Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Lieutenant Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 179947, 'race': 76846, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 11132, 'name': 'Dan Patrick', 'first_name': 'Dan', 'last_name': 'Patrick', 'image': {'id': 60278, 'name': 'Dan_Patrick.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaw

Processing rows:  78%|███████████████████████████████████████           | 39/50 [00:17<00:05,  2.10it/s]

{'success': True, 'data': {'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'state': 'TX'}], 'polling_place_locator': {'url': 'https://teamrv-mvp.sos.texas.gov/MVP/mvp.do'}, 'elections': [{'date': '2025-11-04', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27986, 'name': 'Texas Proposition 10, Property Tax Exemption for Improvements to Homestead Destroyed by Fire Amendment (2025)', 'district_type': 'State'}, {'id': 27976, 'name': 'Texas Proposition 11, Increase Homestead Tax Exemption for Elderly and Disabled Amendment (2025)', 'district_type': 'State'}, {'id': 28007, 'name': 'Texas Proposition 12, Change Membership and Authority of State Commission on Judicial Conduct Amendment (2025)', 'district_type': 'State'}, {'id': 27975, 'name': 'Texas Proposition 13, Increase Homestead Property Tax Exemption Amendment (2025)', 'district_type': 'State'}, {'id': 27950, 'name': 'Texas Proposition 14, Establish Dementia Prevention and Research Institute of Texas Amendment (2025)', 'district_type': 'State'}, {'id': 27967, 'name': 'Texas Proposition 15, Parental Rights Amendment (2025)', 'district_type': 'State'}, {'id': 27948, 'name': 'Texas Proposition 16, Citizenship Voting Requirement Amendment (2025)', 'district_type': 'State'}, {'id': 27974, 'name': 'Texas Proposition 17, Property Tax Exemption for Border Security Infrastructure Amendment (2025)', 'district_type': 'State'}, {'id': 27998, 'name': 'Texas Proposition 1, Establish Special Funds for State Technical College System Amendment (2025)', 'district_type': 'State'}, {'id': 27944, 'name': 'Texas Proposition 2, Prohibit Capital Gains Tax on Individuals, Estates, and Trusts Amendment (2025)', 'district_type': 'State'}, {'id': 28006, 'name': 'Texas Proposition 3, Denial of Bail for Certain Violent or Sexual Offenses Punishable as a Felony Amendment (2025)', 'district_type': 'State'}, {'id': 28005, 'name': 'Texas Proposition 4, Allocate Portion of Sales Tax Revenue to Water Fund Amendment (2025)', 'district_type': 'State'}, {'id': 27951, 'name': 'Texas Proposition 5, Property Tax Exemption on Retail Animal Feed Amendment (2025)', 'district_type': 'State'}, {'id': 27932, 'name': 'Texas Proposition 6, Prohibit Taxes on Certain Securities Transactions Amendment (2025)', 'district_type': 'State'}, {'id': 27985, 'name': 'Texas Proposition 7, Establish Homestead Exemption for Surviving Spouses of Veterans Killed by a Service-Connected Disease Amendment (2025)', 'district_type': 'State'}, {'id': 27949, 'name': 'Texas Proposition 8, Prohibit Estate Taxes and New Taxes on Estate Transfers, Inheritances, and Gifts Amendment (2025)', 'district_type': 'State'}, {'id': 27958, 'name': 'Texas Proposition 9, Authorize $125,000 Tax Exemption for Tangible Property Used for Income Production Amendment (2025)', 'district_type': 'State'}], 'races': None}]}, {'date': '2026-03-03', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62982, 'office': {'id': 1150, 'name': 'U.S. Senate Texas', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Texas', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Texas,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 194592, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 480284, 'name': 'Rennie Mann', 'first_name': 'Rennie', 'last_name': 'Mann', 'image': {'id': 259440, 'name': 'Rennie_Mann_20250529_012636.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Rennie_Mann_20250529_012636.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Rennie_Mann_20250529_012636.jpg'}, 'url': 'https://ballotpedia.org/Rennie_Mann'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 264716, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 27527, 'name': 'John Cornyn', 'first_name': 'John', 'last_name': 'Cornyn', 'image': {'id': 69348, 'name': 'John_Cornyn.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/John_Cornyn.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/John_Cornyn.jpg'}, 'url': 'https://ballotpedia.org/John_Cornyn'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 307578, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 622164, 'name': 'Leo Wyatt', 'first_name': 'Leo', 'last_name': 'Wyatt', 'image': None, 'url': 'https://ballotpedia.org/Leo_Wyatt'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 308697, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 623620, 'name': 'Tony Schmoker', 'first_name': 'Tony', 'last_name': 'Schmoker', 'image': {'id': 258791, 'name': 'TonySchmoker2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/TonySchmoker2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/TonySchmoker2025.jpg'}, 'url': 'https://ballotpedia.org/Tony_Schmoker'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 309436, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624675, 'name': 'Alexander Duncan', 'first_name': 'Alexander', 'last_name': 'Duncan', 'image': {'id': 248352, 'name': 'AlexanderDuncan_TX.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AlexanderDuncan_TX.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AlexanderDuncan_TX.jpeg'}, 'url': 'https://ballotpedia.org/Alexander_Duncan_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310070, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 625468, 'name': 'Barrett McNabb', 'first_name': 'Barrett', 'last_name': 'McNabb', 'image': {'id': 257306, 'name': 'Barrett_McNabb_20250307_031108.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Barrett_McNabb_20250307_031108.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Barrett_McNabb_20250307_031108.png'}, 'url': 'https://ballotpedia.org/Barrett_McNabb'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329097, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 349024, 'name': 'Gulrez Khan', 'first_name': 'Gulrez', 'last_name': 'Khan', 'image': {'id': 259487, 'name': 'Gulrez_Khan_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Gulrez_Khan_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Gulrez_Khan_2025.jpeg'}, 'url': 'https://ballotpedia.org/Gulrez_Khan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 347628, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31934, 'name': 'Ken Paxton', 'first_name': 'Ken', 'last_name': 'Paxton', 'image': {'id': 213529, 'name': 'Ken-Paxton.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ken-Paxton.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ken-Paxton.jpg'}, 'url': 'https://ballotpedia.org/Ken_Paxton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 348603, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 336399, 'name': 'Andrew Alvarez', 'first_name': 'Andrew', 'last_name': 'Alvarez', 'image': {'id': 221333, 'name': 'Andrew_Alvarez1.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andrew_Alvarez1.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andrew_Alvarez1.png'}, 'url': 'https://ballotpedia.org/Andrew_Alvarez_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351082, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 667895, 'name': 'Michael Swanson', 'first_name': 'Michael', 'last_name': 'Swanson', 'image': {'id': 259267, 'name': 'Michael_Swanson_2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Michael_Swanson_2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Michael_Swanson_2025.jpg'}, 'url': 'https://ballotpedia.org/Michael_Swanson_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354059, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 671153, 'name': 'Matthew Elliot Kelley', 'first_name': 'Matthew Elliot', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Matthew_Elliot_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355726, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 320691, 'name': 'Virgil Bierschwale', 'first_name': 'Virgil', 'last_name': 'Bierschwale', 'image': {'id': 260203, 'name': 'vbierschwale.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/vbierschwale.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/vbierschwale.jpg'}, 'url': 'https://ballotpedia.org/Virgil_Bierschwale'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356111, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675163, 'name': 'Terry Virts', 'first_name': 'Terry', 'last_name': 'Virts', 'image': None, 'url': 'https://ballotpedia.org/Terry_Virts'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356310, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 287100, 'name': 'Colin Allred', 'first_name': 'Colin', 'last_name': 'Allred', 'image': {'id': 237057, 'name': 'ColinAllred2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ColinAllred2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ColinAllred2024.jpeg'}, 'url': 'https://ballotpedia.org/Colin_Allred'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359785, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 679722, 'name': 'Emily Morgul', 'first_name': 'Emily', 'last_name': 'Morgul', 'image': {'id': 261421, 'name': 'Emily_Morgul_20250805_042926.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Emily_Morgul_20250805_042926.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Emily_Morgul_20250805_042926.jpeg'}, 'url': 'https://ballotpedia.org/Emily_Morgul'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359787, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679723, 'name': 'Ronald Evans', 'first_name': 'Ronald', 'last_name': 'Evans', 'image': None, 'url': 'https://ballotpedia.org/Ronald_Evans'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365873, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 293105, 'name': 'James Talarico', 'first_name': 'James', 'last_name': 'Talarico', 'image': {'id': 213740, 'name': 'James-Talarico.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James-Talarico.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James-Talarico.jpg'}, 'url': 'https://ballotpedia.org/James_Talarico'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76845, 'office': {'id': 690, 'name': 'Governor of Texas', 'url': 'https://ballotpedia.org/Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 356163, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675192, 'name': 'Bobby Cole', 'first_name': 'Bobby', 'last_name': 'Cole', 'image': {'id': 260839, 'name': 'Bobby_Cole_20250710_120937.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bobby_Cole_20250710_120937.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bobby_Cole_20250710_120937.jpg'}, 'url': 'https://ballotpedia.org/Bobby_Cole'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356465, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 342856, 'name': 'Ronnie Tullos', 'first_name': 'Ronnie', 'last_name': 'Tullos', 'image': {'id': 240369, 'name': 'Ronnie_Bubba_Tullos_20240808_094757.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ronnie_Bubba_Tullos_20240808_094757.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ronnie_Bubba_Tullos_20240808_094757.jpg'}, 'url': 'https://ballotpedia.org/Ronnie_Tullos'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356626, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676637, 'name': 'Meagan Tehseldar', 'first_name': 'Meagan', 'last_name': 'Tehseldar', 'image': {'id': 261171, 'name': 'MeaganTehseldar2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MeaganTehseldar2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MeaganTehseldar2025.png'}, 'url': 'https://ballotpedia.org/Meagan_Tehseldar'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 360436, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680292, 'name': 'Nick Pappas', 'first_name': 'Nick', 'last_name': 'Pappas', 'image': {'id': 261729, 'name': 'Nick_Pappas_25.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Nick_Pappas_25.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Nick_Pappas_25.jpeg'}, 'url': 'https://ballotpedia.org/Nick_Pappas'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361281, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 20241, 'name': 'Greg Abbott', 'first_name': 'Greg', 'last_name': 'Abbott', 'image': {'id': 65280, 'name': 'GregAbbott2015.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/GregAbbott2015.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/GregAbbott2015.jpg'}, 'url': 'https://ballotpedia.org/Greg_Abbott'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76846, 'office': {'id': 12974, 'name': 'Lieutenant Governor of Texas', 'url': 'https://ballotpedia.org/Lieutenant_Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Lieutenant Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 179947, 'race': 76846, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 11132, 'name': 'Dan Patrick', 'first_name': 'Dan', 'last_name': 'Patrick', 'image': {'id': 60278, 'name': 'Dan_Patrick.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaw

Processing rows:  80%|████████████████████████████████████████          | 40/50 [00:18<00:04,  2.07it/s]

{'success': True, 'data': {'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'state': 'TX'}], 'polling_place_locator': {'url': 'https://teamrv-mvp.sos.texas.gov/MVP/mvp.do'}, 'elections': [{'date': '2025-11-04', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27986, 'name': 'Texas Proposition 10, Property Tax Exemption for Improvements to Homestead Destroyed by Fire Amendment (2025)', 'district_type': 'State'}, {'id': 27976, 'name': 'Texas Proposition 11, Increase Homestead Tax Exemption for Elderly and Disabled Amendment (2025)', 'district_type': 'State'}, {'id': 28007, 'name': 'Texas Proposition 12, Change Membership and Authority of State Commission on Judicial Conduct Amendment (2025)', 'district_type': 'State'}, {'id': 27975, 'name': 'Texas Proposition 13, Increase Homestead Property Tax Exemption Amendment (2025)', 'district_type': 'State'}, {'id': 27950, 'name': 'Texas Proposition 14, Establish Dementia Prevention and Research Institute of Texas Amendment (2025)', 'district_type': 'State'}, {'id': 27967, 'name': 'Texas Proposition 15, Parental Rights Amendment (2025)', 'district_type': 'State'}, {'id': 27948, 'name': 'Texas Proposition 16, Citizenship Voting Requirement Amendment (2025)', 'district_type': 'State'}, {'id': 27974, 'name': 'Texas Proposition 17, Property Tax Exemption for Border Security Infrastructure Amendment (2025)', 'district_type': 'State'}, {'id': 27998, 'name': 'Texas Proposition 1, Establish Special Funds for State Technical College System Amendment (2025)', 'district_type': 'State'}, {'id': 27944, 'name': 'Texas Proposition 2, Prohibit Capital Gains Tax on Individuals, Estates, and Trusts Amendment (2025)', 'district_type': 'State'}, {'id': 28006, 'name': 'Texas Proposition 3, Denial of Bail for Certain Violent or Sexual Offenses Punishable as a Felony Amendment (2025)', 'district_type': 'State'}, {'id': 28005, 'name': 'Texas Proposition 4, Allocate Portion of Sales Tax Revenue to Water Fund Amendment (2025)', 'district_type': 'State'}, {'id': 27951, 'name': 'Texas Proposition 5, Property Tax Exemption on Retail Animal Feed Amendment (2025)', 'district_type': 'State'}, {'id': 27932, 'name': 'Texas Proposition 6, Prohibit Taxes on Certain Securities Transactions Amendment (2025)', 'district_type': 'State'}, {'id': 27985, 'name': 'Texas Proposition 7, Establish Homestead Exemption for Surviving Spouses of Veterans Killed by a Service-Connected Disease Amendment (2025)', 'district_type': 'State'}, {'id': 27949, 'name': 'Texas Proposition 8, Prohibit Estate Taxes and New Taxes on Estate Transfers, Inheritances, and Gifts Amendment (2025)', 'district_type': 'State'}, {'id': 27958, 'name': 'Texas Proposition 9, Authorize $125,000 Tax Exemption for Tangible Property Used for Income Production Amendment (2025)', 'district_type': 'State'}], 'races': None}]}, {'date': '2026-03-03', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62982, 'office': {'id': 1150, 'name': 'U.S. Senate Texas', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Texas', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Texas,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 194592, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 480284, 'name': 'Rennie Mann', 'first_name': 'Rennie', 'last_name': 'Mann', 'image': {'id': 259440, 'name': 'Rennie_Mann_20250529_012636.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Rennie_Mann_20250529_012636.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Rennie_Mann_20250529_012636.jpg'}, 'url': 'https://ballotpedia.org/Rennie_Mann'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 264716, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 27527, 'name': 'John Cornyn', 'first_name': 'John', 'last_name': 'Cornyn', 'image': {'id': 69348, 'name': 'John_Cornyn.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/John_Cornyn.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/John_Cornyn.jpg'}, 'url': 'https://ballotpedia.org/John_Cornyn'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 307578, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 622164, 'name': 'Leo Wyatt', 'first_name': 'Leo', 'last_name': 'Wyatt', 'image': None, 'url': 'https://ballotpedia.org/Leo_Wyatt'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 308697, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 623620, 'name': 'Tony Schmoker', 'first_name': 'Tony', 'last_name': 'Schmoker', 'image': {'id': 258791, 'name': 'TonySchmoker2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/TonySchmoker2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/TonySchmoker2025.jpg'}, 'url': 'https://ballotpedia.org/Tony_Schmoker'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 309436, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624675, 'name': 'Alexander Duncan', 'first_name': 'Alexander', 'last_name': 'Duncan', 'image': {'id': 248352, 'name': 'AlexanderDuncan_TX.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AlexanderDuncan_TX.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AlexanderDuncan_TX.jpeg'}, 'url': 'https://ballotpedia.org/Alexander_Duncan_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310070, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 625468, 'name': 'Barrett McNabb', 'first_name': 'Barrett', 'last_name': 'McNabb', 'image': {'id': 257306, 'name': 'Barrett_McNabb_20250307_031108.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Barrett_McNabb_20250307_031108.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Barrett_McNabb_20250307_031108.png'}, 'url': 'https://ballotpedia.org/Barrett_McNabb'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329097, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 349024, 'name': 'Gulrez Khan', 'first_name': 'Gulrez', 'last_name': 'Khan', 'image': {'id': 259487, 'name': 'Gulrez_Khan_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Gulrez_Khan_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Gulrez_Khan_2025.jpeg'}, 'url': 'https://ballotpedia.org/Gulrez_Khan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 347628, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31934, 'name': 'Ken Paxton', 'first_name': 'Ken', 'last_name': 'Paxton', 'image': {'id': 213529, 'name': 'Ken-Paxton.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ken-Paxton.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ken-Paxton.jpg'}, 'url': 'https://ballotpedia.org/Ken_Paxton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 348603, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 336399, 'name': 'Andrew Alvarez', 'first_name': 'Andrew', 'last_name': 'Alvarez', 'image': {'id': 221333, 'name': 'Andrew_Alvarez1.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andrew_Alvarez1.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andrew_Alvarez1.png'}, 'url': 'https://ballotpedia.org/Andrew_Alvarez_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351082, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 667895, 'name': 'Michael Swanson', 'first_name': 'Michael', 'last_name': 'Swanson', 'image': {'id': 259267, 'name': 'Michael_Swanson_2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Michael_Swanson_2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Michael_Swanson_2025.jpg'}, 'url': 'https://ballotpedia.org/Michael_Swanson_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354059, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 671153, 'name': 'Matthew Elliot Kelley', 'first_name': 'Matthew Elliot', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Matthew_Elliot_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355726, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 320691, 'name': 'Virgil Bierschwale', 'first_name': 'Virgil', 'last_name': 'Bierschwale', 'image': {'id': 260203, 'name': 'vbierschwale.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/vbierschwale.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/vbierschwale.jpg'}, 'url': 'https://ballotpedia.org/Virgil_Bierschwale'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356111, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675163, 'name': 'Terry Virts', 'first_name': 'Terry', 'last_name': 'Virts', 'image': None, 'url': 'https://ballotpedia.org/Terry_Virts'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356310, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 287100, 'name': 'Colin Allred', 'first_name': 'Colin', 'last_name': 'Allred', 'image': {'id': 237057, 'name': 'ColinAllred2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ColinAllred2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ColinAllred2024.jpeg'}, 'url': 'https://ballotpedia.org/Colin_Allred'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359785, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 679722, 'name': 'Emily Morgul', 'first_name': 'Emily', 'last_name': 'Morgul', 'image': {'id': 261421, 'name': 'Emily_Morgul_20250805_042926.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Emily_Morgul_20250805_042926.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Emily_Morgul_20250805_042926.jpeg'}, 'url': 'https://ballotpedia.org/Emily_Morgul'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359787, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679723, 'name': 'Ronald Evans', 'first_name': 'Ronald', 'last_name': 'Evans', 'image': None, 'url': 'https://ballotpedia.org/Ronald_Evans'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365873, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 293105, 'name': 'James Talarico', 'first_name': 'James', 'last_name': 'Talarico', 'image': {'id': 213740, 'name': 'James-Talarico.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James-Talarico.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James-Talarico.jpg'}, 'url': 'https://ballotpedia.org/James_Talarico'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76845, 'office': {'id': 690, 'name': 'Governor of Texas', 'url': 'https://ballotpedia.org/Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 356163, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675192, 'name': 'Bobby Cole', 'first_name': 'Bobby', 'last_name': 'Cole', 'image': {'id': 260839, 'name': 'Bobby_Cole_20250710_120937.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bobby_Cole_20250710_120937.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bobby_Cole_20250710_120937.jpg'}, 'url': 'https://ballotpedia.org/Bobby_Cole'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356465, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 342856, 'name': 'Ronnie Tullos', 'first_name': 'Ronnie', 'last_name': 'Tullos', 'image': {'id': 240369, 'name': 'Ronnie_Bubba_Tullos_20240808_094757.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ronnie_Bubba_Tullos_20240808_094757.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ronnie_Bubba_Tullos_20240808_094757.jpg'}, 'url': 'https://ballotpedia.org/Ronnie_Tullos'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356626, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676637, 'name': 'Meagan Tehseldar', 'first_name': 'Meagan', 'last_name': 'Tehseldar', 'image': {'id': 261171, 'name': 'MeaganTehseldar2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MeaganTehseldar2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MeaganTehseldar2025.png'}, 'url': 'https://ballotpedia.org/Meagan_Tehseldar'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 360436, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680292, 'name': 'Nick Pappas', 'first_name': 'Nick', 'last_name': 'Pappas', 'image': {'id': 261729, 'name': 'Nick_Pappas_25.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Nick_Pappas_25.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Nick_Pappas_25.jpeg'}, 'url': 'https://ballotpedia.org/Nick_Pappas'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361281, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 20241, 'name': 'Greg Abbott', 'first_name': 'Greg', 'last_name': 'Abbott', 'image': {'id': 65280, 'name': 'GregAbbott2015.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/GregAbbott2015.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/GregAbbott2015.jpg'}, 'url': 'https://ballotpedia.org/Greg_Abbott'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76846, 'office': {'id': 12974, 'name': 'Lieutenant Governor of Texas', 'url': 'https://ballotpedia.org/Lieutenant_Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Lieutenant Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 179947, 'race': 76846, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 11132, 'name': 'Dan Patrick', 'first_name': 'Dan', 'last_name': 'Patrick', 'image': {'id': 60278, 'name': 'Dan_Patrick.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaw

Processing rows:  82%|█████████████████████████████████████████         | 41/50 [00:18<00:04,  2.01it/s]

{'success': True, 'data': {'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'state': 'TX'}], 'polling_place_locator': {'url': 'https://teamrv-mvp.sos.texas.gov/MVP/mvp.do'}, 'elections': [{'date': '2025-11-04', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27986, 'name': 'Texas Proposition 10, Property Tax Exemption for Improvements to Homestead Destroyed by Fire Amendment (2025)', 'district_type': 'State'}, {'id': 27976, 'name': 'Texas Proposition 11, Increase Homestead Tax Exemption for Elderly and Disabled Amendment (2025)', 'district_type': 'State'}, {'id': 28007, 'name': 'Texas Proposition 12, Change Membership and Authority of State Commission on Judicial Conduct Amendment (2025)', 'district_type': 'State'}, {'id': 27975, 'name': 'Texas Proposition 13, Increase Homestead Property Tax Exemption Amendment (2025)', 'district_type': 'State'}, {'id': 27950, 'name': 'Texas Proposition 14, Establish Dementia Prevention and Research Institute of Texas Amendment (2025)', 'district_type': 'State'}, {'id': 27967, 'name': 'Texas Proposition 15, Parental Rights Amendment (2025)', 'district_type': 'State'}, {'id': 27948, 'name': 'Texas Proposition 16, Citizenship Voting Requirement Amendment (2025)', 'district_type': 'State'}, {'id': 27974, 'name': 'Texas Proposition 17, Property Tax Exemption for Border Security Infrastructure Amendment (2025)', 'district_type': 'State'}, {'id': 27998, 'name': 'Texas Proposition 1, Establish Special Funds for State Technical College System Amendment (2025)', 'district_type': 'State'}, {'id': 27944, 'name': 'Texas Proposition 2, Prohibit Capital Gains Tax on Individuals, Estates, and Trusts Amendment (2025)', 'district_type': 'State'}, {'id': 28006, 'name': 'Texas Proposition 3, Denial of Bail for Certain Violent or Sexual Offenses Punishable as a Felony Amendment (2025)', 'district_type': 'State'}, {'id': 28005, 'name': 'Texas Proposition 4, Allocate Portion of Sales Tax Revenue to Water Fund Amendment (2025)', 'district_type': 'State'}, {'id': 27951, 'name': 'Texas Proposition 5, Property Tax Exemption on Retail Animal Feed Amendment (2025)', 'district_type': 'State'}, {'id': 27932, 'name': 'Texas Proposition 6, Prohibit Taxes on Certain Securities Transactions Amendment (2025)', 'district_type': 'State'}, {'id': 27985, 'name': 'Texas Proposition 7, Establish Homestead Exemption for Surviving Spouses of Veterans Killed by a Service-Connected Disease Amendment (2025)', 'district_type': 'State'}, {'id': 27949, 'name': 'Texas Proposition 8, Prohibit Estate Taxes and New Taxes on Estate Transfers, Inheritances, and Gifts Amendment (2025)', 'district_type': 'State'}, {'id': 27958, 'name': 'Texas Proposition 9, Authorize $125,000 Tax Exemption for Tangible Property Used for Income Production Amendment (2025)', 'district_type': 'State'}], 'races': None}]}, {'date': '2026-03-03', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62982, 'office': {'id': 1150, 'name': 'U.S. Senate Texas', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Texas', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Texas,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 194592, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 480284, 'name': 'Rennie Mann', 'first_name': 'Rennie', 'last_name': 'Mann', 'image': {'id': 259440, 'name': 'Rennie_Mann_20250529_012636.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Rennie_Mann_20250529_012636.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Rennie_Mann_20250529_012636.jpg'}, 'url': 'https://ballotpedia.org/Rennie_Mann'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 264716, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 27527, 'name': 'John Cornyn', 'first_name': 'John', 'last_name': 'Cornyn', 'image': {'id': 69348, 'name': 'John_Cornyn.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/John_Cornyn.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/John_Cornyn.jpg'}, 'url': 'https://ballotpedia.org/John_Cornyn'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 307578, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 622164, 'name': 'Leo Wyatt', 'first_name': 'Leo', 'last_name': 'Wyatt', 'image': None, 'url': 'https://ballotpedia.org/Leo_Wyatt'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 308697, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 623620, 'name': 'Tony Schmoker', 'first_name': 'Tony', 'last_name': 'Schmoker', 'image': {'id': 258791, 'name': 'TonySchmoker2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/TonySchmoker2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/TonySchmoker2025.jpg'}, 'url': 'https://ballotpedia.org/Tony_Schmoker'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 309436, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624675, 'name': 'Alexander Duncan', 'first_name': 'Alexander', 'last_name': 'Duncan', 'image': {'id': 248352, 'name': 'AlexanderDuncan_TX.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AlexanderDuncan_TX.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AlexanderDuncan_TX.jpeg'}, 'url': 'https://ballotpedia.org/Alexander_Duncan_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310070, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 625468, 'name': 'Barrett McNabb', 'first_name': 'Barrett', 'last_name': 'McNabb', 'image': {'id': 257306, 'name': 'Barrett_McNabb_20250307_031108.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Barrett_McNabb_20250307_031108.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Barrett_McNabb_20250307_031108.png'}, 'url': 'https://ballotpedia.org/Barrett_McNabb'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329097, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 349024, 'name': 'Gulrez Khan', 'first_name': 'Gulrez', 'last_name': 'Khan', 'image': {'id': 259487, 'name': 'Gulrez_Khan_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Gulrez_Khan_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Gulrez_Khan_2025.jpeg'}, 'url': 'https://ballotpedia.org/Gulrez_Khan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 347628, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31934, 'name': 'Ken Paxton', 'first_name': 'Ken', 'last_name': 'Paxton', 'image': {'id': 213529, 'name': 'Ken-Paxton.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ken-Paxton.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ken-Paxton.jpg'}, 'url': 'https://ballotpedia.org/Ken_Paxton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 348603, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 336399, 'name': 'Andrew Alvarez', 'first_name': 'Andrew', 'last_name': 'Alvarez', 'image': {'id': 221333, 'name': 'Andrew_Alvarez1.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andrew_Alvarez1.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andrew_Alvarez1.png'}, 'url': 'https://ballotpedia.org/Andrew_Alvarez_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351082, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 667895, 'name': 'Michael Swanson', 'first_name': 'Michael', 'last_name': 'Swanson', 'image': {'id': 259267, 'name': 'Michael_Swanson_2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Michael_Swanson_2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Michael_Swanson_2025.jpg'}, 'url': 'https://ballotpedia.org/Michael_Swanson_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354059, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 671153, 'name': 'Matthew Elliot Kelley', 'first_name': 'Matthew Elliot', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Matthew_Elliot_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355726, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 320691, 'name': 'Virgil Bierschwale', 'first_name': 'Virgil', 'last_name': 'Bierschwale', 'image': {'id': 260203, 'name': 'vbierschwale.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/vbierschwale.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/vbierschwale.jpg'}, 'url': 'https://ballotpedia.org/Virgil_Bierschwale'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356111, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675163, 'name': 'Terry Virts', 'first_name': 'Terry', 'last_name': 'Virts', 'image': None, 'url': 'https://ballotpedia.org/Terry_Virts'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356310, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 287100, 'name': 'Colin Allred', 'first_name': 'Colin', 'last_name': 'Allred', 'image': {'id': 237057, 'name': 'ColinAllred2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ColinAllred2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ColinAllred2024.jpeg'}, 'url': 'https://ballotpedia.org/Colin_Allred'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359785, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 679722, 'name': 'Emily Morgul', 'first_name': 'Emily', 'last_name': 'Morgul', 'image': {'id': 261421, 'name': 'Emily_Morgul_20250805_042926.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Emily_Morgul_20250805_042926.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Emily_Morgul_20250805_042926.jpeg'}, 'url': 'https://ballotpedia.org/Emily_Morgul'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359787, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679723, 'name': 'Ronald Evans', 'first_name': 'Ronald', 'last_name': 'Evans', 'image': None, 'url': 'https://ballotpedia.org/Ronald_Evans'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365873, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 293105, 'name': 'James Talarico', 'first_name': 'James', 'last_name': 'Talarico', 'image': {'id': 213740, 'name': 'James-Talarico.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James-Talarico.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James-Talarico.jpg'}, 'url': 'https://ballotpedia.org/James_Talarico'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76845, 'office': {'id': 690, 'name': 'Governor of Texas', 'url': 'https://ballotpedia.org/Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 356163, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675192, 'name': 'Bobby Cole', 'first_name': 'Bobby', 'last_name': 'Cole', 'image': {'id': 260839, 'name': 'Bobby_Cole_20250710_120937.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bobby_Cole_20250710_120937.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bobby_Cole_20250710_120937.jpg'}, 'url': 'https://ballotpedia.org/Bobby_Cole'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356465, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 342856, 'name': 'Ronnie Tullos', 'first_name': 'Ronnie', 'last_name': 'Tullos', 'image': {'id': 240369, 'name': 'Ronnie_Bubba_Tullos_20240808_094757.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ronnie_Bubba_Tullos_20240808_094757.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ronnie_Bubba_Tullos_20240808_094757.jpg'}, 'url': 'https://ballotpedia.org/Ronnie_Tullos'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356626, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676637, 'name': 'Meagan Tehseldar', 'first_name': 'Meagan', 'last_name': 'Tehseldar', 'image': {'id': 261171, 'name': 'MeaganTehseldar2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MeaganTehseldar2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MeaganTehseldar2025.png'}, 'url': 'https://ballotpedia.org/Meagan_Tehseldar'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 360436, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680292, 'name': 'Nick Pappas', 'first_name': 'Nick', 'last_name': 'Pappas', 'image': {'id': 261729, 'name': 'Nick_Pappas_25.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Nick_Pappas_25.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Nick_Pappas_25.jpeg'}, 'url': 'https://ballotpedia.org/Nick_Pappas'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361281, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 20241, 'name': 'Greg Abbott', 'first_name': 'Greg', 'last_name': 'Abbott', 'image': {'id': 65280, 'name': 'GregAbbott2015.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/GregAbbott2015.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/GregAbbott2015.jpg'}, 'url': 'https://ballotpedia.org/Greg_Abbott'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76846, 'office': {'id': 12974, 'name': 'Lieutenant Governor of Texas', 'url': 'https://ballotpedia.org/Lieutenant_Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Lieutenant Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 179947, 'race': 76846, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 11132, 'name': 'Dan Patrick', 'first_name': 'Dan', 'last_name': 'Patrick', 'image': {'id': 60278, 'name': 'Dan_Patrick.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaw

Processing rows:  84%|██████████████████████████████████████████        | 42/50 [00:19<00:04,  1.88it/s]

{'success': True, 'data': {'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'state': 'TX'}], 'polling_place_locator': {'url': 'https://teamrv-mvp.sos.texas.gov/MVP/mvp.do'}, 'elections': [{'date': '2025-11-04', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27986, 'name': 'Texas Proposition 10, Property Tax Exemption for Improvements to Homestead Destroyed by Fire Amendment (2025)', 'district_type': 'State'}, {'id': 27976, 'name': 'Texas Proposition 11, Increase Homestead Tax Exemption for Elderly and Disabled Amendment (2025)', 'district_type': 'State'}, {'id': 28007, 'name': 'Texas Proposition 12, Change Membership and Authority of State Commission on Judicial Conduct Amendment (2025)', 'district_type': 'State'}, {'id': 27975, 'name': 'Texas Proposition 13, Increase Homestead Property Tax Exemption Amendment (2025)', 'district_type': 'State'}, {'id': 27950, 'name': 'Texas Proposition 14, Establish Dementia Prevention and Research Institute of Texas Amendment (2025)', 'district_type': 'State'}, {'id': 27967, 'name': 'Texas Proposition 15, Parental Rights Amendment (2025)', 'district_type': 'State'}, {'id': 27948, 'name': 'Texas Proposition 16, Citizenship Voting Requirement Amendment (2025)', 'district_type': 'State'}, {'id': 27974, 'name': 'Texas Proposition 17, Property Tax Exemption for Border Security Infrastructure Amendment (2025)', 'district_type': 'State'}, {'id': 27998, 'name': 'Texas Proposition 1, Establish Special Funds for State Technical College System Amendment (2025)', 'district_type': 'State'}, {'id': 27944, 'name': 'Texas Proposition 2, Prohibit Capital Gains Tax on Individuals, Estates, and Trusts Amendment (2025)', 'district_type': 'State'}, {'id': 28006, 'name': 'Texas Proposition 3, Denial of Bail for Certain Violent or Sexual Offenses Punishable as a Felony Amendment (2025)', 'district_type': 'State'}, {'id': 28005, 'name': 'Texas Proposition 4, Allocate Portion of Sales Tax Revenue to Water Fund Amendment (2025)', 'district_type': 'State'}, {'id': 27951, 'name': 'Texas Proposition 5, Property Tax Exemption on Retail Animal Feed Amendment (2025)', 'district_type': 'State'}, {'id': 27932, 'name': 'Texas Proposition 6, Prohibit Taxes on Certain Securities Transactions Amendment (2025)', 'district_type': 'State'}, {'id': 27985, 'name': 'Texas Proposition 7, Establish Homestead Exemption for Surviving Spouses of Veterans Killed by a Service-Connected Disease Amendment (2025)', 'district_type': 'State'}, {'id': 27949, 'name': 'Texas Proposition 8, Prohibit Estate Taxes and New Taxes on Estate Transfers, Inheritances, and Gifts Amendment (2025)', 'district_type': 'State'}, {'id': 27958, 'name': 'Texas Proposition 9, Authorize $125,000 Tax Exemption for Tangible Property Used for Income Production Amendment (2025)', 'district_type': 'State'}], 'races': None}]}, {'date': '2026-03-03', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62982, 'office': {'id': 1150, 'name': 'U.S. Senate Texas', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Texas', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Texas,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 194592, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 480284, 'name': 'Rennie Mann', 'first_name': 'Rennie', 'last_name': 'Mann', 'image': {'id': 259440, 'name': 'Rennie_Mann_20250529_012636.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Rennie_Mann_20250529_012636.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Rennie_Mann_20250529_012636.jpg'}, 'url': 'https://ballotpedia.org/Rennie_Mann'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 264716, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 27527, 'name': 'John Cornyn', 'first_name': 'John', 'last_name': 'Cornyn', 'image': {'id': 69348, 'name': 'John_Cornyn.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/John_Cornyn.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/John_Cornyn.jpg'}, 'url': 'https://ballotpedia.org/John_Cornyn'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 307578, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 622164, 'name': 'Leo Wyatt', 'first_name': 'Leo', 'last_name': 'Wyatt', 'image': None, 'url': 'https://ballotpedia.org/Leo_Wyatt'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 308697, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 623620, 'name': 'Tony Schmoker', 'first_name': 'Tony', 'last_name': 'Schmoker', 'image': {'id': 258791, 'name': 'TonySchmoker2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/TonySchmoker2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/TonySchmoker2025.jpg'}, 'url': 'https://ballotpedia.org/Tony_Schmoker'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 309436, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624675, 'name': 'Alexander Duncan', 'first_name': 'Alexander', 'last_name': 'Duncan', 'image': {'id': 248352, 'name': 'AlexanderDuncan_TX.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AlexanderDuncan_TX.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AlexanderDuncan_TX.jpeg'}, 'url': 'https://ballotpedia.org/Alexander_Duncan_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310070, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 625468, 'name': 'Barrett McNabb', 'first_name': 'Barrett', 'last_name': 'McNabb', 'image': {'id': 257306, 'name': 'Barrett_McNabb_20250307_031108.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Barrett_McNabb_20250307_031108.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Barrett_McNabb_20250307_031108.png'}, 'url': 'https://ballotpedia.org/Barrett_McNabb'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329097, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 349024, 'name': 'Gulrez Khan', 'first_name': 'Gulrez', 'last_name': 'Khan', 'image': {'id': 259487, 'name': 'Gulrez_Khan_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Gulrez_Khan_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Gulrez_Khan_2025.jpeg'}, 'url': 'https://ballotpedia.org/Gulrez_Khan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 347628, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31934, 'name': 'Ken Paxton', 'first_name': 'Ken', 'last_name': 'Paxton', 'image': {'id': 213529, 'name': 'Ken-Paxton.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ken-Paxton.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ken-Paxton.jpg'}, 'url': 'https://ballotpedia.org/Ken_Paxton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 348603, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 336399, 'name': 'Andrew Alvarez', 'first_name': 'Andrew', 'last_name': 'Alvarez', 'image': {'id': 221333, 'name': 'Andrew_Alvarez1.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andrew_Alvarez1.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andrew_Alvarez1.png'}, 'url': 'https://ballotpedia.org/Andrew_Alvarez_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351082, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 667895, 'name': 'Michael Swanson', 'first_name': 'Michael', 'last_name': 'Swanson', 'image': {'id': 259267, 'name': 'Michael_Swanson_2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Michael_Swanson_2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Michael_Swanson_2025.jpg'}, 'url': 'https://ballotpedia.org/Michael_Swanson_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354059, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 671153, 'name': 'Matthew Elliot Kelley', 'first_name': 'Matthew Elliot', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Matthew_Elliot_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355726, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 320691, 'name': 'Virgil Bierschwale', 'first_name': 'Virgil', 'last_name': 'Bierschwale', 'image': {'id': 260203, 'name': 'vbierschwale.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/vbierschwale.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/vbierschwale.jpg'}, 'url': 'https://ballotpedia.org/Virgil_Bierschwale'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356111, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675163, 'name': 'Terry Virts', 'first_name': 'Terry', 'last_name': 'Virts', 'image': None, 'url': 'https://ballotpedia.org/Terry_Virts'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356310, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 287100, 'name': 'Colin Allred', 'first_name': 'Colin', 'last_name': 'Allred', 'image': {'id': 237057, 'name': 'ColinAllred2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ColinAllred2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ColinAllred2024.jpeg'}, 'url': 'https://ballotpedia.org/Colin_Allred'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359785, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 679722, 'name': 'Emily Morgul', 'first_name': 'Emily', 'last_name': 'Morgul', 'image': {'id': 261421, 'name': 'Emily_Morgul_20250805_042926.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Emily_Morgul_20250805_042926.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Emily_Morgul_20250805_042926.jpeg'}, 'url': 'https://ballotpedia.org/Emily_Morgul'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359787, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679723, 'name': 'Ronald Evans', 'first_name': 'Ronald', 'last_name': 'Evans', 'image': None, 'url': 'https://ballotpedia.org/Ronald_Evans'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365873, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 293105, 'name': 'James Talarico', 'first_name': 'James', 'last_name': 'Talarico', 'image': {'id': 213740, 'name': 'James-Talarico.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James-Talarico.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James-Talarico.jpg'}, 'url': 'https://ballotpedia.org/James_Talarico'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76845, 'office': {'id': 690, 'name': 'Governor of Texas', 'url': 'https://ballotpedia.org/Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 356163, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675192, 'name': 'Bobby Cole', 'first_name': 'Bobby', 'last_name': 'Cole', 'image': {'id': 260839, 'name': 'Bobby_Cole_20250710_120937.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bobby_Cole_20250710_120937.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bobby_Cole_20250710_120937.jpg'}, 'url': 'https://ballotpedia.org/Bobby_Cole'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356465, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 342856, 'name': 'Ronnie Tullos', 'first_name': 'Ronnie', 'last_name': 'Tullos', 'image': {'id': 240369, 'name': 'Ronnie_Bubba_Tullos_20240808_094757.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ronnie_Bubba_Tullos_20240808_094757.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ronnie_Bubba_Tullos_20240808_094757.jpg'}, 'url': 'https://ballotpedia.org/Ronnie_Tullos'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356626, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676637, 'name': 'Meagan Tehseldar', 'first_name': 'Meagan', 'last_name': 'Tehseldar', 'image': {'id': 261171, 'name': 'MeaganTehseldar2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MeaganTehseldar2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MeaganTehseldar2025.png'}, 'url': 'https://ballotpedia.org/Meagan_Tehseldar'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 360436, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680292, 'name': 'Nick Pappas', 'first_name': 'Nick', 'last_name': 'Pappas', 'image': {'id': 261729, 'name': 'Nick_Pappas_25.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Nick_Pappas_25.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Nick_Pappas_25.jpeg'}, 'url': 'https://ballotpedia.org/Nick_Pappas'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361281, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 20241, 'name': 'Greg Abbott', 'first_name': 'Greg', 'last_name': 'Abbott', 'image': {'id': 65280, 'name': 'GregAbbott2015.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/GregAbbott2015.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/GregAbbott2015.jpg'}, 'url': 'https://ballotpedia.org/Greg_Abbott'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76846, 'office': {'id': 12974, 'name': 'Lieutenant Governor of Texas', 'url': 'https://ballotpedia.org/Lieutenant_Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Lieutenant Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 179947, 'race': 76846, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 11132, 'name': 'Dan Patrick', 'first_name': 'Dan', 'last_name': 'Patrick', 'image': {'id': 60278, 'name': 'Dan_Patrick.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaw

Processing rows:  86%|███████████████████████████████████████████       | 43/50 [00:20<00:03,  1.88it/s]

{'success': True, 'data': {'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'state': 'TX'}], 'polling_place_locator': {'url': 'https://teamrv-mvp.sos.texas.gov/MVP/mvp.do'}, 'elections': [{'date': '2025-11-04', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27986, 'name': 'Texas Proposition 10, Property Tax Exemption for Improvements to Homestead Destroyed by Fire Amendment (2025)', 'district_type': 'State'}, {'id': 27976, 'name': 'Texas Proposition 11, Increase Homestead Tax Exemption for Elderly and Disabled Amendment (2025)', 'district_type': 'State'}, {'id': 28007, 'name': 'Texas Proposition 12, Change Membership and Authority of State Commission on Judicial Conduct Amendment (2025)', 'district_type': 'State'}, {'id': 27975, 'name': 'Texas Proposition 13, Increase Homestead Property Tax Exemption Amendment (2025)', 'district_type': 'State'}, {'id': 27950, 'name': 'Texas Proposition 14, Establish Dementia Prevention and Research Institute of Texas Amendment (2025)', 'district_type': 'State'}, {'id': 27967, 'name': 'Texas Proposition 15, Parental Rights Amendment (2025)', 'district_type': 'State'}, {'id': 27948, 'name': 'Texas Proposition 16, Citizenship Voting Requirement Amendment (2025)', 'district_type': 'State'}, {'id': 27974, 'name': 'Texas Proposition 17, Property Tax Exemption for Border Security Infrastructure Amendment (2025)', 'district_type': 'State'}, {'id': 27998, 'name': 'Texas Proposition 1, Establish Special Funds for State Technical College System Amendment (2025)', 'district_type': 'State'}, {'id': 27944, 'name': 'Texas Proposition 2, Prohibit Capital Gains Tax on Individuals, Estates, and Trusts Amendment (2025)', 'district_type': 'State'}, {'id': 28006, 'name': 'Texas Proposition 3, Denial of Bail for Certain Violent or Sexual Offenses Punishable as a Felony Amendment (2025)', 'district_type': 'State'}, {'id': 28005, 'name': 'Texas Proposition 4, Allocate Portion of Sales Tax Revenue to Water Fund Amendment (2025)', 'district_type': 'State'}, {'id': 27951, 'name': 'Texas Proposition 5, Property Tax Exemption on Retail Animal Feed Amendment (2025)', 'district_type': 'State'}, {'id': 27932, 'name': 'Texas Proposition 6, Prohibit Taxes on Certain Securities Transactions Amendment (2025)', 'district_type': 'State'}, {'id': 27985, 'name': 'Texas Proposition 7, Establish Homestead Exemption for Surviving Spouses of Veterans Killed by a Service-Connected Disease Amendment (2025)', 'district_type': 'State'}, {'id': 27949, 'name': 'Texas Proposition 8, Prohibit Estate Taxes and New Taxes on Estate Transfers, Inheritances, and Gifts Amendment (2025)', 'district_type': 'State'}, {'id': 27958, 'name': 'Texas Proposition 9, Authorize $125,000 Tax Exemption for Tangible Property Used for Income Production Amendment (2025)', 'district_type': 'State'}], 'races': None}]}, {'date': '2026-03-03', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62982, 'office': {'id': 1150, 'name': 'U.S. Senate Texas', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Texas', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Texas,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 194592, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 480284, 'name': 'Rennie Mann', 'first_name': 'Rennie', 'last_name': 'Mann', 'image': {'id': 259440, 'name': 'Rennie_Mann_20250529_012636.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Rennie_Mann_20250529_012636.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Rennie_Mann_20250529_012636.jpg'}, 'url': 'https://ballotpedia.org/Rennie_Mann'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 264716, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 27527, 'name': 'John Cornyn', 'first_name': 'John', 'last_name': 'Cornyn', 'image': {'id': 69348, 'name': 'John_Cornyn.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/John_Cornyn.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/John_Cornyn.jpg'}, 'url': 'https://ballotpedia.org/John_Cornyn'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 307578, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 622164, 'name': 'Leo Wyatt', 'first_name': 'Leo', 'last_name': 'Wyatt', 'image': None, 'url': 'https://ballotpedia.org/Leo_Wyatt'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 308697, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 623620, 'name': 'Tony Schmoker', 'first_name': 'Tony', 'last_name': 'Schmoker', 'image': {'id': 258791, 'name': 'TonySchmoker2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/TonySchmoker2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/TonySchmoker2025.jpg'}, 'url': 'https://ballotpedia.org/Tony_Schmoker'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 309436, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624675, 'name': 'Alexander Duncan', 'first_name': 'Alexander', 'last_name': 'Duncan', 'image': {'id': 248352, 'name': 'AlexanderDuncan_TX.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AlexanderDuncan_TX.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AlexanderDuncan_TX.jpeg'}, 'url': 'https://ballotpedia.org/Alexander_Duncan_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310070, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 625468, 'name': 'Barrett McNabb', 'first_name': 'Barrett', 'last_name': 'McNabb', 'image': {'id': 257306, 'name': 'Barrett_McNabb_20250307_031108.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Barrett_McNabb_20250307_031108.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Barrett_McNabb_20250307_031108.png'}, 'url': 'https://ballotpedia.org/Barrett_McNabb'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329097, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 349024, 'name': 'Gulrez Khan', 'first_name': 'Gulrez', 'last_name': 'Khan', 'image': {'id': 259487, 'name': 'Gulrez_Khan_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Gulrez_Khan_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Gulrez_Khan_2025.jpeg'}, 'url': 'https://ballotpedia.org/Gulrez_Khan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 347628, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31934, 'name': 'Ken Paxton', 'first_name': 'Ken', 'last_name': 'Paxton', 'image': {'id': 213529, 'name': 'Ken-Paxton.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ken-Paxton.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ken-Paxton.jpg'}, 'url': 'https://ballotpedia.org/Ken_Paxton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 348603, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 336399, 'name': 'Andrew Alvarez', 'first_name': 'Andrew', 'last_name': 'Alvarez', 'image': {'id': 221333, 'name': 'Andrew_Alvarez1.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andrew_Alvarez1.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andrew_Alvarez1.png'}, 'url': 'https://ballotpedia.org/Andrew_Alvarez_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351082, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 667895, 'name': 'Michael Swanson', 'first_name': 'Michael', 'last_name': 'Swanson', 'image': {'id': 259267, 'name': 'Michael_Swanson_2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Michael_Swanson_2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Michael_Swanson_2025.jpg'}, 'url': 'https://ballotpedia.org/Michael_Swanson_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354059, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 671153, 'name': 'Matthew Elliot Kelley', 'first_name': 'Matthew Elliot', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Matthew_Elliot_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355726, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 320691, 'name': 'Virgil Bierschwale', 'first_name': 'Virgil', 'last_name': 'Bierschwale', 'image': {'id': 260203, 'name': 'vbierschwale.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/vbierschwale.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/vbierschwale.jpg'}, 'url': 'https://ballotpedia.org/Virgil_Bierschwale'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356111, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675163, 'name': 'Terry Virts', 'first_name': 'Terry', 'last_name': 'Virts', 'image': None, 'url': 'https://ballotpedia.org/Terry_Virts'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356310, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 287100, 'name': 'Colin Allred', 'first_name': 'Colin', 'last_name': 'Allred', 'image': {'id': 237057, 'name': 'ColinAllred2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ColinAllred2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ColinAllred2024.jpeg'}, 'url': 'https://ballotpedia.org/Colin_Allred'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359785, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 679722, 'name': 'Emily Morgul', 'first_name': 'Emily', 'last_name': 'Morgul', 'image': {'id': 261421, 'name': 'Emily_Morgul_20250805_042926.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Emily_Morgul_20250805_042926.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Emily_Morgul_20250805_042926.jpeg'}, 'url': 'https://ballotpedia.org/Emily_Morgul'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359787, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679723, 'name': 'Ronald Evans', 'first_name': 'Ronald', 'last_name': 'Evans', 'image': None, 'url': 'https://ballotpedia.org/Ronald_Evans'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365873, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 293105, 'name': 'James Talarico', 'first_name': 'James', 'last_name': 'Talarico', 'image': {'id': 213740, 'name': 'James-Talarico.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James-Talarico.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James-Talarico.jpg'}, 'url': 'https://ballotpedia.org/James_Talarico'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76845, 'office': {'id': 690, 'name': 'Governor of Texas', 'url': 'https://ballotpedia.org/Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 356163, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675192, 'name': 'Bobby Cole', 'first_name': 'Bobby', 'last_name': 'Cole', 'image': {'id': 260839, 'name': 'Bobby_Cole_20250710_120937.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bobby_Cole_20250710_120937.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bobby_Cole_20250710_120937.jpg'}, 'url': 'https://ballotpedia.org/Bobby_Cole'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356465, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 342856, 'name': 'Ronnie Tullos', 'first_name': 'Ronnie', 'last_name': 'Tullos', 'image': {'id': 240369, 'name': 'Ronnie_Bubba_Tullos_20240808_094757.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ronnie_Bubba_Tullos_20240808_094757.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ronnie_Bubba_Tullos_20240808_094757.jpg'}, 'url': 'https://ballotpedia.org/Ronnie_Tullos'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356626, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676637, 'name': 'Meagan Tehseldar', 'first_name': 'Meagan', 'last_name': 'Tehseldar', 'image': {'id': 261171, 'name': 'MeaganTehseldar2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MeaganTehseldar2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MeaganTehseldar2025.png'}, 'url': 'https://ballotpedia.org/Meagan_Tehseldar'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 360436, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680292, 'name': 'Nick Pappas', 'first_name': 'Nick', 'last_name': 'Pappas', 'image': {'id': 261729, 'name': 'Nick_Pappas_25.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Nick_Pappas_25.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Nick_Pappas_25.jpeg'}, 'url': 'https://ballotpedia.org/Nick_Pappas'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361281, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 20241, 'name': 'Greg Abbott', 'first_name': 'Greg', 'last_name': 'Abbott', 'image': {'id': 65280, 'name': 'GregAbbott2015.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/GregAbbott2015.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/GregAbbott2015.jpg'}, 'url': 'https://ballotpedia.org/Greg_Abbott'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76846, 'office': {'id': 12974, 'name': 'Lieutenant Governor of Texas', 'url': 'https://ballotpedia.org/Lieutenant_Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Lieutenant Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 179947, 'race': 76846, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 11132, 'name': 'Dan Patrick', 'first_name': 'Dan', 'last_name': 'Patrick', 'image': {'id': 60278, 'name': 'Dan_Patrick.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaw

Processing rows:  88%|████████████████████████████████████████████      | 44/50 [00:20<00:03,  1.90it/s]

{'success': True, 'data': {'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'state': 'TX'}], 'polling_place_locator': {'url': 'https://teamrv-mvp.sos.texas.gov/MVP/mvp.do'}, 'elections': [{'date': '2025-11-04', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27986, 'name': 'Texas Proposition 10, Property Tax Exemption for Improvements to Homestead Destroyed by Fire Amendment (2025)', 'district_type': 'State'}, {'id': 27976, 'name': 'Texas Proposition 11, Increase Homestead Tax Exemption for Elderly and Disabled Amendment (2025)', 'district_type': 'State'}, {'id': 28007, 'name': 'Texas Proposition 12, Change Membership and Authority of State Commission on Judicial Conduct Amendment (2025)', 'district_type': 'State'}, {'id': 27975, 'name': 'Texas Proposition 13, Increase Homestead Property Tax Exemption Amendment (2025)', 'district_type': 'State'}, {'id': 27950, 'name': 'Texas Proposition 14, Establish Dementia Prevention and Research Institute of Texas Amendment (2025)', 'district_type': 'State'}, {'id': 27967, 'name': 'Texas Proposition 15, Parental Rights Amendment (2025)', 'district_type': 'State'}, {'id': 27948, 'name': 'Texas Proposition 16, Citizenship Voting Requirement Amendment (2025)', 'district_type': 'State'}, {'id': 27974, 'name': 'Texas Proposition 17, Property Tax Exemption for Border Security Infrastructure Amendment (2025)', 'district_type': 'State'}, {'id': 27998, 'name': 'Texas Proposition 1, Establish Special Funds for State Technical College System Amendment (2025)', 'district_type': 'State'}, {'id': 27944, 'name': 'Texas Proposition 2, Prohibit Capital Gains Tax on Individuals, Estates, and Trusts Amendment (2025)', 'district_type': 'State'}, {'id': 28006, 'name': 'Texas Proposition 3, Denial of Bail for Certain Violent or Sexual Offenses Punishable as a Felony Amendment (2025)', 'district_type': 'State'}, {'id': 28005, 'name': 'Texas Proposition 4, Allocate Portion of Sales Tax Revenue to Water Fund Amendment (2025)', 'district_type': 'State'}, {'id': 27951, 'name': 'Texas Proposition 5, Property Tax Exemption on Retail Animal Feed Amendment (2025)', 'district_type': 'State'}, {'id': 27932, 'name': 'Texas Proposition 6, Prohibit Taxes on Certain Securities Transactions Amendment (2025)', 'district_type': 'State'}, {'id': 27985, 'name': 'Texas Proposition 7, Establish Homestead Exemption for Surviving Spouses of Veterans Killed by a Service-Connected Disease Amendment (2025)', 'district_type': 'State'}, {'id': 27949, 'name': 'Texas Proposition 8, Prohibit Estate Taxes and New Taxes on Estate Transfers, Inheritances, and Gifts Amendment (2025)', 'district_type': 'State'}, {'id': 27958, 'name': 'Texas Proposition 9, Authorize $125,000 Tax Exemption for Tangible Property Used for Income Production Amendment (2025)', 'district_type': 'State'}], 'races': None}]}, {'date': '2026-03-03', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62982, 'office': {'id': 1150, 'name': 'U.S. Senate Texas', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Texas', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Texas,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 194592, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 480284, 'name': 'Rennie Mann', 'first_name': 'Rennie', 'last_name': 'Mann', 'image': {'id': 259440, 'name': 'Rennie_Mann_20250529_012636.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Rennie_Mann_20250529_012636.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Rennie_Mann_20250529_012636.jpg'}, 'url': 'https://ballotpedia.org/Rennie_Mann'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 264716, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 27527, 'name': 'John Cornyn', 'first_name': 'John', 'last_name': 'Cornyn', 'image': {'id': 69348, 'name': 'John_Cornyn.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/John_Cornyn.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/John_Cornyn.jpg'}, 'url': 'https://ballotpedia.org/John_Cornyn'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 307578, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 622164, 'name': 'Leo Wyatt', 'first_name': 'Leo', 'last_name': 'Wyatt', 'image': None, 'url': 'https://ballotpedia.org/Leo_Wyatt'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 308697, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 623620, 'name': 'Tony Schmoker', 'first_name': 'Tony', 'last_name': 'Schmoker', 'image': {'id': 258791, 'name': 'TonySchmoker2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/TonySchmoker2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/TonySchmoker2025.jpg'}, 'url': 'https://ballotpedia.org/Tony_Schmoker'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 309436, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624675, 'name': 'Alexander Duncan', 'first_name': 'Alexander', 'last_name': 'Duncan', 'image': {'id': 248352, 'name': 'AlexanderDuncan_TX.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AlexanderDuncan_TX.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AlexanderDuncan_TX.jpeg'}, 'url': 'https://ballotpedia.org/Alexander_Duncan_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310070, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 625468, 'name': 'Barrett McNabb', 'first_name': 'Barrett', 'last_name': 'McNabb', 'image': {'id': 257306, 'name': 'Barrett_McNabb_20250307_031108.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Barrett_McNabb_20250307_031108.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Barrett_McNabb_20250307_031108.png'}, 'url': 'https://ballotpedia.org/Barrett_McNabb'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329097, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 349024, 'name': 'Gulrez Khan', 'first_name': 'Gulrez', 'last_name': 'Khan', 'image': {'id': 259487, 'name': 'Gulrez_Khan_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Gulrez_Khan_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Gulrez_Khan_2025.jpeg'}, 'url': 'https://ballotpedia.org/Gulrez_Khan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 347628, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31934, 'name': 'Ken Paxton', 'first_name': 'Ken', 'last_name': 'Paxton', 'image': {'id': 213529, 'name': 'Ken-Paxton.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ken-Paxton.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ken-Paxton.jpg'}, 'url': 'https://ballotpedia.org/Ken_Paxton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 348603, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 336399, 'name': 'Andrew Alvarez', 'first_name': 'Andrew', 'last_name': 'Alvarez', 'image': {'id': 221333, 'name': 'Andrew_Alvarez1.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andrew_Alvarez1.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andrew_Alvarez1.png'}, 'url': 'https://ballotpedia.org/Andrew_Alvarez_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351082, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 667895, 'name': 'Michael Swanson', 'first_name': 'Michael', 'last_name': 'Swanson', 'image': {'id': 259267, 'name': 'Michael_Swanson_2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Michael_Swanson_2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Michael_Swanson_2025.jpg'}, 'url': 'https://ballotpedia.org/Michael_Swanson_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354059, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 671153, 'name': 'Matthew Elliot Kelley', 'first_name': 'Matthew Elliot', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Matthew_Elliot_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355726, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 320691, 'name': 'Virgil Bierschwale', 'first_name': 'Virgil', 'last_name': 'Bierschwale', 'image': {'id': 260203, 'name': 'vbierschwale.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/vbierschwale.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/vbierschwale.jpg'}, 'url': 'https://ballotpedia.org/Virgil_Bierschwale'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356111, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675163, 'name': 'Terry Virts', 'first_name': 'Terry', 'last_name': 'Virts', 'image': None, 'url': 'https://ballotpedia.org/Terry_Virts'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356310, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 287100, 'name': 'Colin Allred', 'first_name': 'Colin', 'last_name': 'Allred', 'image': {'id': 237057, 'name': 'ColinAllred2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ColinAllred2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ColinAllred2024.jpeg'}, 'url': 'https://ballotpedia.org/Colin_Allred'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359785, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 679722, 'name': 'Emily Morgul', 'first_name': 'Emily', 'last_name': 'Morgul', 'image': {'id': 261421, 'name': 'Emily_Morgul_20250805_042926.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Emily_Morgul_20250805_042926.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Emily_Morgul_20250805_042926.jpeg'}, 'url': 'https://ballotpedia.org/Emily_Morgul'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359787, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679723, 'name': 'Ronald Evans', 'first_name': 'Ronald', 'last_name': 'Evans', 'image': None, 'url': 'https://ballotpedia.org/Ronald_Evans'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365873, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 293105, 'name': 'James Talarico', 'first_name': 'James', 'last_name': 'Talarico', 'image': {'id': 213740, 'name': 'James-Talarico.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James-Talarico.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James-Talarico.jpg'}, 'url': 'https://ballotpedia.org/James_Talarico'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76845, 'office': {'id': 690, 'name': 'Governor of Texas', 'url': 'https://ballotpedia.org/Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 356163, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675192, 'name': 'Bobby Cole', 'first_name': 'Bobby', 'last_name': 'Cole', 'image': {'id': 260839, 'name': 'Bobby_Cole_20250710_120937.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bobby_Cole_20250710_120937.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bobby_Cole_20250710_120937.jpg'}, 'url': 'https://ballotpedia.org/Bobby_Cole'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356465, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 342856, 'name': 'Ronnie Tullos', 'first_name': 'Ronnie', 'last_name': 'Tullos', 'image': {'id': 240369, 'name': 'Ronnie_Bubba_Tullos_20240808_094757.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ronnie_Bubba_Tullos_20240808_094757.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ronnie_Bubba_Tullos_20240808_094757.jpg'}, 'url': 'https://ballotpedia.org/Ronnie_Tullos'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356626, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676637, 'name': 'Meagan Tehseldar', 'first_name': 'Meagan', 'last_name': 'Tehseldar', 'image': {'id': 261171, 'name': 'MeaganTehseldar2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MeaganTehseldar2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MeaganTehseldar2025.png'}, 'url': 'https://ballotpedia.org/Meagan_Tehseldar'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 360436, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680292, 'name': 'Nick Pappas', 'first_name': 'Nick', 'last_name': 'Pappas', 'image': {'id': 261729, 'name': 'Nick_Pappas_25.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Nick_Pappas_25.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Nick_Pappas_25.jpeg'}, 'url': 'https://ballotpedia.org/Nick_Pappas'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361281, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 20241, 'name': 'Greg Abbott', 'first_name': 'Greg', 'last_name': 'Abbott', 'image': {'id': 65280, 'name': 'GregAbbott2015.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/GregAbbott2015.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/GregAbbott2015.jpg'}, 'url': 'https://ballotpedia.org/Greg_Abbott'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76846, 'office': {'id': 12974, 'name': 'Lieutenant Governor of Texas', 'url': 'https://ballotpedia.org/Lieutenant_Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Lieutenant Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 179947, 'race': 76846, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 11132, 'name': 'Dan Patrick', 'first_name': 'Dan', 'last_name': 'Patrick', 'image': {'id': 60278, 'name': 'Dan_Patrick.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaw

Processing rows:  90%|█████████████████████████████████████████████     | 45/50 [00:21<00:02,  1.85it/s]

{'success': True, 'data': {'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'state': 'TX'}], 'polling_place_locator': {'url': 'https://teamrv-mvp.sos.texas.gov/MVP/mvp.do'}, 'elections': [{'date': '2025-11-04', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27986, 'name': 'Texas Proposition 10, Property Tax Exemption for Improvements to Homestead Destroyed by Fire Amendment (2025)', 'district_type': 'State'}, {'id': 27976, 'name': 'Texas Proposition 11, Increase Homestead Tax Exemption for Elderly and Disabled Amendment (2025)', 'district_type': 'State'}, {'id': 28007, 'name': 'Texas Proposition 12, Change Membership and Authority of State Commission on Judicial Conduct Amendment (2025)', 'district_type': 'State'}, {'id': 27975, 'name': 'Texas Proposition 13, Increase Homestead Property Tax Exemption Amendment (2025)', 'district_type': 'State'}, {'id': 27950, 'name': 'Texas Proposition 14, Establish Dementia Prevention and Research Institute of Texas Amendment (2025)', 'district_type': 'State'}, {'id': 27967, 'name': 'Texas Proposition 15, Parental Rights Amendment (2025)', 'district_type': 'State'}, {'id': 27948, 'name': 'Texas Proposition 16, Citizenship Voting Requirement Amendment (2025)', 'district_type': 'State'}, {'id': 27974, 'name': 'Texas Proposition 17, Property Tax Exemption for Border Security Infrastructure Amendment (2025)', 'district_type': 'State'}, {'id': 27998, 'name': 'Texas Proposition 1, Establish Special Funds for State Technical College System Amendment (2025)', 'district_type': 'State'}, {'id': 27944, 'name': 'Texas Proposition 2, Prohibit Capital Gains Tax on Individuals, Estates, and Trusts Amendment (2025)', 'district_type': 'State'}, {'id': 28006, 'name': 'Texas Proposition 3, Denial of Bail for Certain Violent or Sexual Offenses Punishable as a Felony Amendment (2025)', 'district_type': 'State'}, {'id': 28005, 'name': 'Texas Proposition 4, Allocate Portion of Sales Tax Revenue to Water Fund Amendment (2025)', 'district_type': 'State'}, {'id': 27951, 'name': 'Texas Proposition 5, Property Tax Exemption on Retail Animal Feed Amendment (2025)', 'district_type': 'State'}, {'id': 27932, 'name': 'Texas Proposition 6, Prohibit Taxes on Certain Securities Transactions Amendment (2025)', 'district_type': 'State'}, {'id': 27985, 'name': 'Texas Proposition 7, Establish Homestead Exemption for Surviving Spouses of Veterans Killed by a Service-Connected Disease Amendment (2025)', 'district_type': 'State'}, {'id': 27949, 'name': 'Texas Proposition 8, Prohibit Estate Taxes and New Taxes on Estate Transfers, Inheritances, and Gifts Amendment (2025)', 'district_type': 'State'}, {'id': 27958, 'name': 'Texas Proposition 9, Authorize $125,000 Tax Exemption for Tangible Property Used for Income Production Amendment (2025)', 'district_type': 'State'}], 'races': None}]}, {'date': '2026-03-03', 'candidate_lists_complete': False, 'districts': [{'id': 556, 'name': 'Texas', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': None, 'races': [{'id': 62982, 'office': {'id': 1150, 'name': 'U.S. Senate Texas', 'url': 'https://ballotpedia.org/List_of_United_States_Senators_from_Texas', 'level': 'Federal', 'branch': 'Legislative', 'chamber': 'Upper', 'type': 'Senator', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/United_States_Senate_election_in_Texas,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 194592, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 480284, 'name': 'Rennie Mann', 'first_name': 'Rennie', 'last_name': 'Mann', 'image': {'id': 259440, 'name': 'Rennie_Mann_20250529_012636.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Rennie_Mann_20250529_012636.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Rennie_Mann_20250529_012636.jpg'}, 'url': 'https://ballotpedia.org/Rennie_Mann'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 264716, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 27527, 'name': 'John Cornyn', 'first_name': 'John', 'last_name': 'Cornyn', 'image': {'id': 69348, 'name': 'John_Cornyn.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/John_Cornyn.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/John_Cornyn.jpg'}, 'url': 'https://ballotpedia.org/John_Cornyn'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 307578, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 622164, 'name': 'Leo Wyatt', 'first_name': 'Leo', 'last_name': 'Wyatt', 'image': None, 'url': 'https://ballotpedia.org/Leo_Wyatt'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 308697, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 623620, 'name': 'Tony Schmoker', 'first_name': 'Tony', 'last_name': 'Schmoker', 'image': {'id': 258791, 'name': 'TonySchmoker2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/TonySchmoker2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/TonySchmoker2025.jpg'}, 'url': 'https://ballotpedia.org/Tony_Schmoker'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 309436, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 624675, 'name': 'Alexander Duncan', 'first_name': 'Alexander', 'last_name': 'Duncan', 'image': {'id': 248352, 'name': 'AlexanderDuncan_TX.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/AlexanderDuncan_TX.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/AlexanderDuncan_TX.jpeg'}, 'url': 'https://ballotpedia.org/Alexander_Duncan_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 310070, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 625468, 'name': 'Barrett McNabb', 'first_name': 'Barrett', 'last_name': 'McNabb', 'image': {'id': 257306, 'name': 'Barrett_McNabb_20250307_031108.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Barrett_McNabb_20250307_031108.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Barrett_McNabb_20250307_031108.png'}, 'url': 'https://ballotpedia.org/Barrett_McNabb'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 329097, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 349024, 'name': 'Gulrez Khan', 'first_name': 'Gulrez', 'last_name': 'Khan', 'image': {'id': 259487, 'name': 'Gulrez_Khan_2025.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Gulrez_Khan_2025.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Gulrez_Khan_2025.jpeg'}, 'url': 'https://ballotpedia.org/Gulrez_Khan'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 347628, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 31934, 'name': 'Ken Paxton', 'first_name': 'Ken', 'last_name': 'Paxton', 'image': {'id': 213529, 'name': 'Ken-Paxton.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ken-Paxton.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ken-Paxton.jpg'}, 'url': 'https://ballotpedia.org/Ken_Paxton'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 348603, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 336399, 'name': 'Andrew Alvarez', 'first_name': 'Andrew', 'last_name': 'Alvarez', 'image': {'id': 221333, 'name': 'Andrew_Alvarez1.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Andrew_Alvarez1.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Andrew_Alvarez1.png'}, 'url': 'https://ballotpedia.org/Andrew_Alvarez_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 351082, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 667895, 'name': 'Michael Swanson', 'first_name': 'Michael', 'last_name': 'Swanson', 'image': {'id': 259267, 'name': 'Michael_Swanson_2025.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Michael_Swanson_2025.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Michael_Swanson_2025.jpg'}, 'url': 'https://ballotpedia.org/Michael_Swanson_(Texas)'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 354059, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 671153, 'name': 'Matthew Elliot Kelley', 'first_name': 'Matthew Elliot', 'last_name': 'Kelley', 'image': None, 'url': 'https://ballotpedia.org/Matthew_Elliot_Kelley'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 355726, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 320691, 'name': 'Virgil Bierschwale', 'first_name': 'Virgil', 'last_name': 'Bierschwale', 'image': {'id': 260203, 'name': 'vbierschwale.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/vbierschwale.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/vbierschwale.jpg'}, 'url': 'https://ballotpedia.org/Virgil_Bierschwale'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356111, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675163, 'name': 'Terry Virts', 'first_name': 'Terry', 'last_name': 'Virts', 'image': None, 'url': 'https://ballotpedia.org/Terry_Virts'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356310, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 287100, 'name': 'Colin Allred', 'first_name': 'Colin', 'last_name': 'Allred', 'image': {'id': 237057, 'name': 'ColinAllred2024.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/ColinAllred2024.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/ColinAllred2024.jpeg'}, 'url': 'https://ballotpedia.org/Colin_Allred'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359785, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 679722, 'name': 'Emily Morgul', 'first_name': 'Emily', 'last_name': 'Morgul', 'image': {'id': 261421, 'name': 'Emily_Morgul_20250805_042926.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Emily_Morgul_20250805_042926.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Emily_Morgul_20250805_042926.jpeg'}, 'url': 'https://ballotpedia.org/Emily_Morgul'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 359787, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 679723, 'name': 'Ronald Evans', 'first_name': 'Ronald', 'last_name': 'Evans', 'image': None, 'url': 'https://ballotpedia.org/Ronald_Evans'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 365873, 'race': 62982, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 293105, 'name': 'James Talarico', 'first_name': 'James', 'last_name': 'Talarico', 'image': {'id': 213740, 'name': 'James-Talarico.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/James-Talarico.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/James-Talarico.jpg'}, 'url': 'https://ballotpedia.org/James_Talarico'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76845, 'office': {'id': 690, 'name': 'Governor of Texas', 'url': 'https://ballotpedia.org/Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 356163, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 675192, 'name': 'Bobby Cole', 'first_name': 'Bobby', 'last_name': 'Cole', 'image': {'id': 260839, 'name': 'Bobby_Cole_20250710_120937.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Bobby_Cole_20250710_120937.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Bobby_Cole_20250710_120937.jpg'}, 'url': 'https://ballotpedia.org/Bobby_Cole'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}, {'id': 356465, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 342856, 'name': 'Ronnie Tullos', 'first_name': 'Ronnie', 'last_name': 'Tullos', 'image': {'id': 240369, 'name': 'Ronnie_Bubba_Tullos_20240808_094757.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Ronnie_Bubba_Tullos_20240808_094757.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Ronnie_Bubba_Tullos_20240808_094757.jpg'}, 'url': 'https://ballotpedia.org/Ronnie_Tullos'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 356626, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 676637, 'name': 'Meagan Tehseldar', 'first_name': 'Meagan', 'last_name': 'Tehseldar', 'image': {'id': 261171, 'name': 'MeaganTehseldar2025.png', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/MeaganTehseldar2025.png', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/MeaganTehseldar2025.png'}, 'url': 'https://ballotpedia.org/Meagan_Tehseldar'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 360436, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 2, 'name': 'Democratic Party', 'url': 'https://ballotpedia.org/Democratic_Party'}], 'person': {'id': 680292, 'name': 'Nick Pappas', 'first_name': 'Nick', 'last_name': 'Pappas', 'image': {'id': 261729, 'name': 'Nick_Pappas_25.jpeg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/Nick_Pappas_25.jpeg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/Nick_Pappas_25.jpeg'}, 'url': 'https://ballotpedia.org/Nick_Pappas'}, 'is_incumbent': False, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': True}, {'id': 361281, 'race': 76845, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 20241, 'name': 'Greg Abbott', 'first_name': 'Greg', 'last_name': 'Abbott', 'image': {'id': 65280, 'name': 'GregAbbott2015.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaws.com/files/GregAbbott2015.jpg', 'thumbnail': 'https://ballotpedia-api4.s3.amazonaws.com/files/thumbs/100/100/GregAbbott2015.jpg'}, 'url': 'https://ballotpedia.org/Greg_Abbott'}, 'is_incumbent': True, 'status': 'Candidacy Declared', 'is_write_in': False, 'withdrew_still_on_ballot': False, 'running_mate_id': None, 'survey_exists': False}]}, {'id': 76846, 'office': {'id': 12974, 'name': 'Lieutenant Governor of Texas', 'url': 'https://ballotpedia.org/Lieutenant_Governor_of_Texas', 'level': 'State', 'branch': 'Executive', 'chamber': None, 'type': 'Lieutenant Governor', 'primary_type': 'Open', 'is_partisan': 'Partisan all'}, 'office_district': 556, 'url': 'https://ballotpedia.org/Texas_lieutenant_gubernatorial_election,_2026', 'stage_type': 'Primary', 'district_type': 'State', 'office_position': None, 'number_of_seats': 1, 'race_type': 'Regular', 'candidates': [{'id': 179947, 'race': 76846, 'running_mate': None, 'party_affiliation': [{'id': 1, 'name': 'Republican Party', 'url': 'https://ballotpedia.org/Republican_Party'}], 'person': {'id': 11132, 'name': 'Dan Patrick', 'first_name': 'Dan', 'last_name': 'Patrick', 'image': {'id': 60278, 'name': 'Dan_Patrick.jpg', 'url': 'https://ballotpedia-api4.s3.amazonaw

Processing rows:  92%|██████████████████████████████████████████████    | 46/50 [00:21<00:02,  1.97it/s]

{'success': True, 'data': {'districts': [{'id': 512, 'name': 'Alabama', 'type': 'State', 'state': 'AL'}], 'polling_place_locator': {'url': 'https://myinfo.alabamavotes.gov/VoterView/PollingPlaceSearch.do'}, 'elections': [{'date': '2026-05-19', 'candidate_lists_complete': False, 'districts': [{'id': 512, 'name': 'Alabama', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27933, 'name': 'Alabama Allow Judges to Deny Bail for Certain Weapon Discharges and Solicitation, Attempt, or Conspiracy to Commit Murder Amendment (May 2026)', 'district_type': 'State'}, {'id': 27947, 'name': 'Alabama Prohibit Diminishing District Attorney Compensation During Term of Office Amendment (May 2026)', 'district_type': 'State'}], 'races': None}, {'id': 3, 'name': 'Alabama District 3', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': [{'id': 1093, 'sort': 1, 'text': 'A three-judge panel of the United States District Court for the Northern District of Alabama ruled on Sept. 5, 2023, that the revised congressional district boundaries that Alabama enacted on July 21, 2023, were not in accordance with the Voting Rights Act. <a href="https://ballotpedia.org/Redistricting_in_Alabama_after_the_2020_census" target="_blank">Click here to learn more.</a>', 'district': 3, 'election_date': None, 'created': '2023-07-25T15:00:39.639531', 'updated': '2023-09-06T17:42:37.149497'}], 'ballot_measures': None, 'races': None}]}]}, 'message': None}

Processing rows:  94%|███████████████████████████████████████████████   | 47/50 [00:21<00:01,  2.04it/s]

{'success': True, 'data': {'districts': [{'id': 512, 'name': 'Alabama', 'type': 'State', 'state': 'AL'}], 'polling_place_locator': {'url': 'https://myinfo.alabamavotes.gov/VoterView/PollingPlaceSearch.do'}, 'elections': [{'date': '2026-05-19', 'candidate_lists_complete': False, 'districts': [{'id': 512, 'name': 'Alabama', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27933, 'name': 'Alabama Allow Judges to Deny Bail for Certain Weapon Discharges and Solicitation, Attempt, or Conspiracy to Commit Murder Amendment (May 2026)', 'district_type': 'State'}, {'id': 27947, 'name': 'Alabama Prohibit Diminishing District Attorney Compensation During Term of Office Amendment (May 2026)', 'district_type': 'State'}], 'races': None}, {'id': 3, 'name': 'Alabama District 3', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': [{'id': 1093, 'sort': 1, 'text': 'A three-judge panel of the United States District Court for the Northern District of Alabama ruled on Sept. 5, 2023, that the revised congressional district boundaries that Alabama enacted on July 21, 2023, were not in accordance with the Voting Rights Act. <a href="https://ballotpedia.org/Redistricting_in_Alabama_after_the_2020_census" target="_blank">Click here to learn more.</a>', 'district': 3, 'election_date': None, 'created': '2023-07-25T15:00:39.639531', 'updated': '2023-09-06T17:42:37.149497'}], 'ballot_measures': None, 'races': None}]}]}, 'message': None}

Processing rows:  96%|████████████████████████████████████████████████  | 48/50 [00:22<00:00,  2.12it/s]

{'success': True, 'data': {'districts': [{'id': 512, 'name': 'Alabama', 'type': 'State', 'state': 'AL'}], 'polling_place_locator': {'url': 'https://myinfo.alabamavotes.gov/VoterView/PollingPlaceSearch.do'}, 'elections': [{'date': '2026-05-19', 'candidate_lists_complete': False, 'districts': [{'id': 512, 'name': 'Alabama', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27933, 'name': 'Alabama Allow Judges to Deny Bail for Certain Weapon Discharges and Solicitation, Attempt, or Conspiracy to Commit Murder Amendment (May 2026)', 'district_type': 'State'}, {'id': 27947, 'name': 'Alabama Prohibit Diminishing District Attorney Compensation During Term of Office Amendment (May 2026)', 'district_type': 'State'}], 'races': None}, {'id': 3, 'name': 'Alabama District 3', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': [{'id': 1093, 'sort': 1, 'text': 'A three-judge panel of the United States District Court for the Northern District of Alabama ruled on Sept. 5, 2023, that the revised congressional district boundaries that Alabama enacted on July 21, 2023, were not in accordance with the Voting Rights Act. <a href="https://ballotpedia.org/Redistricting_in_Alabama_after_the_2020_census" target="_blank">Click here to learn more.</a>', 'district': 3, 'election_date': None, 'created': '2023-07-25T15:00:39.639531', 'updated': '2023-09-06T17:42:37.149497'}], 'ballot_measures': None, 'races': None}]}]}, 'message': None}

Processing rows:  98%|█████████████████████████████████████████████████ | 49/50 [00:22<00:00,  2.27it/s]

{'success': True, 'data': {'districts': [{'id': 512, 'name': 'Alabama', 'type': 'State', 'state': 'AL'}], 'polling_place_locator': {'url': 'https://myinfo.alabamavotes.gov/VoterView/PollingPlaceSearch.do'}, 'elections': [{'date': '2026-05-19', 'candidate_lists_complete': False, 'districts': [{'id': 512, 'name': 'Alabama', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27933, 'name': 'Alabama Allow Judges to Deny Bail for Certain Weapon Discharges and Solicitation, Attempt, or Conspiracy to Commit Murder Amendment (May 2026)', 'district_type': 'State'}, {'id': 27947, 'name': 'Alabama Prohibit Diminishing District Attorney Compensation During Term of Office Amendment (May 2026)', 'district_type': 'State'}], 'races': None}, {'id': 3, 'name': 'Alabama District 3', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': [{'id': 1093, 'sort': 1, 'text': 'A three-judge panel of the United States District Court for the Northern District of Alabama ruled on Sept. 5, 2023, that the revised congressional district boundaries that Alabama enacted on July 21, 2023, were not in accordance with the Voting Rights Act. <a href="https://ballotpedia.org/Redistricting_in_Alabama_after_the_2020_census" target="_blank">Click here to learn more.</a>', 'district': 3, 'election_date': None, 'created': '2023-07-25T15:00:39.639531', 'updated': '2023-09-06T17:42:37.149497'}], 'ballot_measures': None, 'races': None}]}]}, 'message': None}

Processing rows: 100%|██████████████████████████████████████████████████| 50/50 [00:23<00:00,  2.16it/s]

{'success': True, 'data': {'districts': [{'id': 512, 'name': 'Alabama', 'type': 'State', 'state': 'AL'}], 'polling_place_locator': {'url': 'https://myinfo.alabamavotes.gov/VoterView/PollingPlaceSearch.do'}, 'elections': [{'date': '2026-05-19', 'candidate_lists_complete': False, 'districts': [{'id': 512, 'name': 'Alabama', 'type': 'State', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': None, 'ballot_measures': [{'id': 27933, 'name': 'Alabama Allow Judges to Deny Bail for Certain Weapon Discharges and Solicitation, Attempt, or Conspiracy to Commit Murder Amendment (May 2026)', 'district_type': 'State'}, {'id': 27947, 'name': 'Alabama Prohibit Diminishing District Attorney Compensation During Term of Office Amendment (May 2026)', 'district_type': 'State'}], 'races': None}, {'id': 3, 'name': 'Alabama District 3', 'type': 'Congress', 'precise_boundary': True, 'disclaimers': None, 'permanent_disclaimers': [{'id': 1093, 'sort': 1, 'text': 'A three-judge panel of the United States District Court for the Northern District of Alabama ruled on Sept. 5, 2023, that the revised congressional district boundaries that Alabama enacted on July 21, 2023, were not in accordance with the Voting Rights Act. <a href="https://ballotpedia.org/Redistricting_in_Alabama_after_the_2020_census" target="_blank">Click here to learn more.</a>', 'district': 3, 'election_date': None, 'created': '2023-07-25T15:00:39.639531', 'updated': '2023-09-06T17:42:37.149497'}], 'ballot_measures': None, 'races': None}]}]}, 'message': None}

In [53]:
print(result_df)

     election_date district_name district_type       race_type  \
0       2025-11-04    California         State  Ballot Measure
1       2025-11-04    California         State  Ballot Measure
2       2025-11-04    California         State  Ballot Measure
3       2026-05-19      Kentucky         State       Candidate
4       2026-05-19      Kentucky         State       Candidate
...            ...           ...           ...             ...
1244    2026-05-19       Alabama         State  Ballot Measure
1245    2026-05-19       Alabama         State  Ballot Measure
1246    2026-05-19       Alabama         State  Ballot Measure
1247    2026-05-19       Alabama         State  Ballot Measure
1248    2026-05-19       Alabama         State  Ballot Measure

                                            office.name     office.type  \
0     California Proposition 50, Use of Legislative ...  Ballot Measure
1     California Proposition 50, Use of Legislative ...  Ballot Measure
2     California Proposition 50, Use of Legislative ...  Ballot Measure
3                                  U.S. Senate Kentucky         Senator
4                                  U.S. Senate Kentucky         Senator
...                                                 ...             ...
1244  Alabama Prohibit Diminishing District Attorney...  Ballot Measure
1245  Alabama Allow Judges to Deny Bail for Certain ...  Ballot Measure
1246  Alabama Prohibit Diminishing District Attorney...  Ballot Measure
1247  Alabama Allow Judges to Deny Bail for Certain ...  Ballot Measure
1248  Alabama Prohibit Diminishing District Attorney...  Ballot Measure

     office.level office.branch  number_of_seats       person.name  ...  \
0           State           N/A                1   Yes/No Question  ...
1           State           N/A                1   Yes/No Question  ...
2           State           N/A                1   Yes/No Question  ...
3         Federal   Legislative                1  Pamela Stevenson  ...
4         Federal   Legislative                1     Wende Kennedy  ...
...           ...           ...              ...               ...  ...
1244        State           N/A                1   Yes/No Question  ...
1245        State           N/A                1   Yes/No Question  ...
1246        State           N/A                1   Yes/No Question  ...
1247        State           N/A                1   Yes/No Question  ...
1248        State           N/A                1   Yes/No Question  ...

             lng unique_decisions total_options  \
0    -120.792790                1             2
1    -120.972498                1             2
2    -120.861590                1             2
3     -85.159074                1            11
4     -85.159074                1            11
...          ...              ...           ...
1244  -86.154560                2             4
1245  -86.163496                2             4
1246  -86.163496                2             4
1247  -86.037136                2             4
1248  -86.037136                2             4

                                               response intersection_id  \
0     {"success": true, "data": {"districts": [{"id"...             140
1     {"success": true, "data": {"districts": [{"id"...             141
2     {"success": true, "data": {"districts": [{"id"...             142
3     {"success": true, "data": {"districts": [{"id"...             145
4     {"success": true, "data": {"districts": [{"id"...             145
...                                                 ...             ...
1244  {"success": true, "data": {"districts": [{"id"...             194
1245  {"success": true, "data": {"districts": [{"id"...             195
1246  {"success": true, "data": {"districts": [{"id"...             195
1247  {"success": true, "data": {"districts": [{"id"...             196
1248  {"success": true, "data": {"districts": [{"id"...             196

      district   county       state    zip  \
0           03   Sierra  California  95936
1           03   Sierra  California  95960
2           03   Sierra  California  95944
3           01  Clinton   Tennessee  38549
4           01  Clinton   Tennessee  38549
...        ...      ...         ...    ...
1244        03     Clay     Alabama  35082
1245        03     Clay     Alabama  35150
1246        03     Clay     Alabama  35150
1247        03     Clay     Alabama  35160
1248        03     Clay     Alabama  35160

                                               geometry
0     POLYGON ((-2095264.5212082318 2111470.26092156...
1     POLYGON ((-2103559.9321298925 2099602.53433268...
2     POLYGON ((-2096173.572862002 2113442.188701270...
3     MULTIPOLYGON (((957477.5037434566 1563339.0295...
4     MULTIPOLYGON (((957477.5037434566 1563339.0295...
...                                                 ...
1244  POLYGON ((909418.2882089905 1164945.133038352,...
1245  POLYGON ((909475.3354828499 1164319.0129441076...
1246  POLYGON ((909475.3354828499 1164319.0129441076...
1247  POLYGON ((925051.0774362169 1189252.3000487196...
1248  POLYGON ((925051.0774362169 1189252.3000487196...

[1249 rows x 29 columns]

In [54]:
result_df['district'] = result_df.district.str.replace('00', '01')
import re

def extract_type_district_numbers(text, state):
    # Regular expression pattern to match <TYPE> District <NUMBER>
    pattern = f'U\\.S\\. House \\b{state}\\b (?:D|d)istrict (\\d+)'
    matches = re.findall(pattern, text)
    
    # Return matches as a list of tuples with <TYPE> and <NUMBER>
    return (matches or [None])[0]

In [56]:
state_id_lookup = dict(zip(area_df.state, area_df.state_id))

In [58]:
print(state_id_lookup)

{'Nebraska': 'NE', 'Washington': 'WA', 'New Mexico': 'NM', 'South Dakota': 'SD', 'Texas': 'TX', 'Nevada': 'NV', 'California': 'CA', 'Tennessee': 'TN', 'Kentucky': 'KY', 'Ohio': 'OH', 'Alabama': 'AL', 'Georgia': 'GA', 'Wisconsin': 'WI', 'Arkansas': 'AR', 'Oregon': 'OR', 'Pennsylvania': 'PA', 'Mississippi': 'MS', 'Missouri': 'MO', 'Colorado': 'CO', 'North Carolina': 'NC', 'Utah': 'UT', 'Oklahoma': 'OK', 'Virginia': 'VA', 'Wyoming': 'WY', 'West Virginia': 'WV', 'Louisiana': 'LA', 'New York': 'NY', 'Michigan': 'MI', 'Indiana': 'IN', 'Massachusetts': 'MA', 'Kansas': 'KS', 'Idaho': 'ID', 'Florida': 'FL', 'Alaska': 'AK', 'Illinois': 'IL', 'Vermont': 'VT', 'Montana': 'MT', 'Minnesota': 'MN', 'New Jersey': 'NJ', 'North Dakota': 'ND', 'Maryland': 'MD', 'Iowa': 'IA', 'South Carolina': 'SC', 'Maine': 'ME', 'Hawaii': 'HI', 'New Hampshire': 'NH', 'Arizona': 'AZ', 'Delaware': 'DE', 'District of Columbia': 'DC', 'Rhode Island': 'RI', 'Connecticut': 'CT'}

In [59]:
result_df['state_id'] = result_df.state.map(state_id_lookup)
result_df['district'] = result_df.progress_apply(
    lambda x: f'{x.state_id}-CD{int(str(x.district)[-2:]):02}'
    if x.district is not None and str(x.district)[-3:] != 'nan' else None, axis=1
)
result_df['extracted_district'] = result_df.progress_apply(
    lambda x: extract_type_district_numbers(x.response, x.state) or 0, axis=1
)
result_df['extracted_district'] = result_df.progress_apply(
    lambda x: f'{x.state_id}-CD{int(x.extracted_district):02}', axis=1
)

100%|████████████████████████████████████████████████████████████| 1249/1249 [00:00<00:00, 20651.41it/s]
100%|████████████████████████████████████████████████████████████| 1249/1249 [00:00<00:00, 23923.56it/s]
100%|████████████████████████████████████████████████████████████| 1249/1249 [00:00<00:00, 47015.35it/s]

In [60]:
result_df['district'] = result_df.district.fillna(result_df.extracted_district)

In [61]:
result_df['district']

0       CA-CD03
1       CA-CD03
2       CA-CD03
3       TN-CD01
4       TN-CD01
         ...
1244    AL-CD03
1245    AL-CD03
1246    AL-CD03
1247    AL-CD03
1248    AL-CD03
Name: district, Length: 1249, dtype: object

In [62]:
result_df['extracted_district']

0       CA-CD00
1       CA-CD00
2       CA-CD00
3       TN-CD00
4       TN-CD00
         ...
1244    AL-CD00
1245    AL-CD00
1246    AL-CD00
1247    AL-CD00
1248    AL-CD00
Name: extracted_district, Length: 1249, dtype: object

In [63]:
index = (result_df.district != result_df.extracted_district) & (~result_df.extracted_district.str.endswith('00'))
result_df.loc[index, 'extracted_district'].value_counts()
result_df.loc[index, 'district'] = result_df.loc[index, 'extracted_district']

extracted_district
KY-CD01    42
Name: count, dtype: int64

In [66]:
from datetime import date

today = date.today().strftime("%Y-%m-%d")

result_df[[
    'zip', 'county', 'district', 'state', 'lat', 'lng', 'response'
]].drop_duplicates(['zip', 'county', 'district']).to_csv(f'data/2025/results_{today}.csv')

In [18]:
alert('Complete!')

# Define ballot complexity analyzer

Function to analyze ballot complexity using GPT-4:
- Identifies non-partisan contests

Uses structured Pydantic models to validate GPT-4 outputs.

In [67]:
import json
import os
import re

from typing import List, Optional, Union, Literal
from pydantic import BaseModel, Field
from openai import OpenAI
from functools import lru_cache
from typing import List
from collections import Counter

# Initialize OpenAI client
# client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

class NonPartisanContest(BaseModel):
    is_non_partisan: bool

In [68]:
# Updated prompt for remaining indicators and analysis
SYSTEM_PROMPT = """
Determine if this is a non-partisan election contest.

Non-partisan contests typically:
- Don't list party affiliations
- Include local offices like school boards, city councils
- Include most judicial positions
- Are specifically designated as non-partisan

Partisan contests typically:
- List party affiliations
- Include races for Congress, President, Governor
- Are primary elections for political parties
- Include party committee positions

Provide analysis in JSON format:
{
    "is_non_partisan": boolean
}
"""
# Function to analyze a single ballot
@lru_cache(maxsize=100_000)
def analyze_race(race):
    
    # Create prompt for remaining analysis
    prompt = f"""
    Analyze the following race:
    {race}
    
    Provide the analysis in the specified structured JSON format.
    """
    
    try:
        completion = client.beta.chat.completions.parse(
            model="gpt-4o-mini",
            temperature=0.0,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt}
            ],
            response_format=NonPartisanContest
        )
        
        # Parse the JSON response
        analysis = json.loads(completion.choices[0].message.content)
        return analysis['is_non_partisan']
    except Exception as e:
        print(f"Error analyzing ballot: {e}")
        return None

# Define ballot formatting functions

Functions to create a markdown-formatted ballot display:
- Sorts races by importance (President → Federal → State → Local → Measures)
- Formats candidate details including party, incumbent status, and links
- Creates checkboxes for voting options

In [69]:
import pandas as pd

def format_and_display_ballot_info(group):
    # Sort the races
    sorted_group = sort_races(group)
    
    # Start building the markdown output
    markdown_output = f"# Ballot for {sorted_group['county'].iloc[0]} County, {sorted_group['state'].iloc[0]}\n\n"
    markdown_output += f"Election Date: {sorted_group['election_date'].iloc[0]}\n\n"

    # Process races by office
    outputs = []
    for office, office_group in sorted_group.groupby('office.name'):
        outputs.append((format_office(office, office_group), office_group.key.iloc[0]))

    outputs.sort(key=lambda x: x[1])
    for output, key in outputs:
        markdown_output += output

    return markdown_output

def sort_races(group):
    def race_priority(row):
        office = row['office.name'].lower()
        if row['race_type'] == 'Ballot Measure':
            return 5
        elif 'president' in office:
            return 0
        elif office.startswith('u.s.'):
            return 1
        elif 'governor' in office:
            return 2
        elif row['office.level'] == 'State':
            return 3
        else:
            return 4

    group['key'] = group.apply(race_priority, axis=1)
    group = group.sort_values(by='key')

    return group

def format_office(office, office_group):
    first_row = office_group.iloc[0]
    output = f"## {office}\n\n"
    
    if first_row['race_type'] == 'Ballot Measure':
        output += format_ballot_measure(first_row)
    else:
        output += format_candidate_race(office_group)
    
    output += "---\n\n"
    return output

def format_ballot_measure(measure):
    output = f"**Type:** Ballot Measure\n"
    output += f"**Level:** {measure['measure_district_type']}\n\n"
    return output

def format_candidate_race(race_group):
    first_row = race_group.iloc[0]
    output = f"**Level:** {first_row['office.level']}\n"
    output += f"**Branch:** {first_row['office.branch']}\n"
    output += f"**Number of Seats:** {first_row['number_of_seats']}\n\n"
    output += "### Candidates:\n"
    
    for _, candidate in race_group.iterrows():
        output += format_candidate(candidate)
    
    return output

def format_candidate(candidate):
    party = candidate['party_affiliation']
    party_name = party[0]['name'] if isinstance(party, list) and party else 'Unknown'
    
    output = f"- **{candidate['person.name']}** ({party_name})\n"
    bullets = []
    if pd.notna(candidate['running_mate.name']):
        bullets.append(f"Running Mate: {candidate['running_mate.name']}\n")
    if pd.notna(candidate['person.url']):
        bullets.append(f"[More Info]({candidate['person.url']})\n")
    if len(bullets) > 1:
        output += '    - ' + '    - '.join(bullets)
    else:
        output += ''.join(bullets)
    output += "\n"
    return output

In [70]:
for markdown_output in result_df.iloc[:100].groupby(['intersection_id', 'state']).apply(format_and_display_ballot_info):
    print(markdown_output)
    display(Markdown(markdown_output))
    break

# Ballot for Sierra County, California

Election Date: 2025-11-04

## California Proposition 50, Use of Legislative Congressional Redistricting Map Amendment (2025)

**Type:** Ballot Measure
**Level:** State

---

# Ballot for Sierra County, California

Election Date: 2025-11-04

## California Proposition 50, Use of Legislative Congressional Redistricting Map Amendment (2025)

**Type:** Ballot Measure
**Level:** State

---

In [71]:
import markdown
from bs4 import BeautifulSoup

def count_markdown_words(md_text):
    # Convert Markdown to HTML
    html = markdown.markdown(md_text)
    # Extract text from HTML
    text = BeautifulSoup(html, 'html.parser').get_text()
    # Count words
    return len(text.split())

In [72]:
tqdm.pandas()

rows = []
for group_name, group in tqdm(result_df.groupby(['intersection_id', 'state'])):
    subset = [c for c in group.columns if c not in ['lat', 'lng', 'group_id', 'zip']]
    ballot_text = format_and_display_ballot_info(group.drop_duplicates(['office.name', 'person.name']))
    
    races = [format_office(office, office_group)
             for office, office_group in group.groupby('office.name')
             if office_group.iloc[0].race_type != 'Ballot Measure']
    
    measures = [format_office(office, office_group)
                for office, office_group in group.groupby('office.name')
                if office_group.iloc[0].race_type == 'Ballot Measure']
    
    comp_races = [format_office(office, office_group)
                  for office, office_group in group.groupby('office.name')
                  if office_group.iloc[0].race_type != 'Ballot Measure' and len(office_group) > office_group.iloc[0].number_of_seats]
    
    non_partisan_races = [r.strip('# ').split('\n')[0] for r in races if 'nonpartisan' in r.lower()]
    ballot_length = len(ballot_text)
    word_count = count_markdown_words(ballot_text)
    
    row = {
        'intersection_id': group_name[0],
        'lat': group['lat'].iloc[0], 'lng': group['lng'].iloc[0],
        'zip': int(group['zip'].iloc[0]),
        'response': group['response'].iloc[0],
        'ballot_markdown': ballot_text, 
        'state_name': group_name[1],
        'county': group['county'].iloc[0],
        'district': group['district'].iloc[0],
        'unique_decisions':  group['office.name'].nunique(),
        'measures': measures,
        'races': races,
        'comp_races': comp_races,
        'non_partisan_races': non_partisan_races,
        "ballot_length": ballot_length,
        "word_count": word_count,
        'geometry': group['geometry'].iloc[0],
        'total_options': (group.race_type == 'Ballot Measure').sum() * 2 + (group.race_type != 'Ballot Measure').sum()
    }
    rows.append(row)

full_df = pd.DataFrame(rows).set_index(['intersection_id', 'state_name'])

100%|███████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 38.58it/s]

In [74]:
full_df.tail(10)

,,lat,lng,zip,response,ballot_markdown,county,district,unique_decisions,measures,races,comp_races,non_partisan_races,ballot_length,word_count,geometry,total_options
intersection_id,state_name,,,,,,,,,,,,,,,,
187,Texas,33.881340,-101.598810,79250,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,POLYGON ((-509937.0183781471 1229657.914430047...,67
188,Texas,33.983660,-101.993020,79021,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,POLYGON ((-551068.5756636254 1231618.650399775...,67
189,Texas,34.287800,-101.894920,79032,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,POLYGON ((-540454.0791680462 1266811.127153755...,67
190,Texas,33.857810,-101.882280,79311,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,"POLYGON ((-525229.83892836 1211659.9064766727,...",67
191,Texas,33.956080,-101.949240,79073,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,POLYGON ((-546156.7047345301 1228821.619732102...,67
192,Alabama,33.135830,-85.694478,36276,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clay County, Alabama\n\nElection ...",Clay,AL-CD03,2,[## Alabama Allow Judges to Deny Bail for Cert...,[],[],[],412,52,POLYGON ((956816.1426509152 1175354.1865688218...,4
193,Alabama,33.112564,-85.765995,36256,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clay County, Alabama\n\nElection ...",Clay,AL-CD03,2,[## Alabama Allow Judges to Deny Bail for Cert...,[],[],[],412,52,POLYGON ((949030.7837886392 1166290.6676511853...,4
194,Alabama,33.156300,-86.154560,35082,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clay County, Alabama\n\nElection ...",Clay,AL-CD03,2,[## Alabama Allow Judges to Deny Bail for Cert...,[],[],[],412,52,"POLYGON ((909418.2882089905 1164945.133038352,...",4
195,Alabama,33.118477,-86.163496,35150,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clay County, Alabama\n\nElection ...",Clay,AL-CD03,2,[## Alabama Allow Judges to Deny Bail for Cert...,[],[],[],412,52,POLYGON ((909475.3354828499 1164319.0129441076...,4
196,Alabama,33.256637,-86.037136,35160,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clay County, Alabama\n\nElection ...",Clay,AL-CD03,2,[## Alabama Allow Judges to Deny Bail for Cert...,[],[],[],412,52,POLYGON ((925051.0774362169 1189252.3000487196...,4

In [77]:
full_df

,,lat,lng,zip,response,ballot_markdown,county,district,unique_decisions,measures,races,comp_races,non_partisan_races,ballot_length,word_count,geometry,total_options
intersection_id,state_name,,,,,,,,,,,,,,,,
140,California,39.563360,-120.792790,95936,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Sierra County, California\n\nElec...",Sierra,CA-CD03,1,"[## California Proposition 50, Use of Legislat...",[],[],[],214,24,POLYGON ((-2095264.5212082318 2111470.26092156...,2
141,California,39.433973,-120.972498,95960,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Sierra County, California\n\nElec...",Sierra,CA-CD03,1,"[## California Proposition 50, Use of Legislat...",[],[],[],214,24,POLYGON ((-2103559.9321298925 2099602.53433268...,2
142,California,39.534820,-120.861590,95944,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Sierra County, California\n\nElec...",Sierra,CA-CD03,1,"[## California Proposition 50, Use of Legislat...",[],[],[],214,24,POLYGON ((-2096173.572862002 2113442.188701270...,2
145,Tennessee,36.629042,-85.159074,38549,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clinton County, Tennessee\n\nElec...",Clinton,TN-CD01,3,[],[## Kentucky House of Representatives District...,[## U.S. House Kentucky District 1\n\n**Level:...,[],1730,134,MULTIPOLYGON (((957477.5037434566 1563339.0295...,14
146,Kentucky,36.670118,-85.264284,42717,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clinton County, Kentucky\n\nElect...",Clinton,KY-CD01,3,[],[## Kentucky House of Representatives District...,[## U.S. House Kentucky District 1\n\n**Level:...,[],1729,134,MULTIPOLYGON (((948198.6851217566 1562503.1105...,14
147,Kentucky,36.626036,-85.295355,42717,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clinton County, Kentucky\n\nElect...",Clinton,KY-CD01,3,[],[## Kentucky House of Representatives District...,[## U.S. House Kentucky District 1\n\n**Level:...,[],1729,134,MULTIPOLYGON (((946836.97126505 1562308.294266...,14
148,Kentucky,36.716344,-85.009947,42602,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clinton County, Kentucky\n\nElect...",Clinton,KY-CD05,2,[],[## U.S. House Kentucky District 5\n\n**Level:...,[## U.S. House Kentucky District 5\n\n**Level:...,[],1583,118,MULTIPOLYGON (((973730.4785105877 1564660.9135...,14
149,Kentucky,36.732010,-85.133240,42602,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clinton County, Kentucky\n\nElect...",Clinton,KY-CD01,3,[],[## Kentucky House of Representatives District...,[## U.S. House Kentucky District 1\n\n**Level:...,[],1729,134,POLYGON ((969991.0601767872 1577959.9489515154...,14
150,Kentucky,36.622390,-85.096303,42602,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clinton County, Kentucky\n\nElect...",Clinton,KY-CD01,3,[],[## Kentucky House of Representatives District...,[## U.S. House Kentucky District 1\n\n**Level:...,[],1729,134,POLYGON ((964046.5528060909 1563809.6571805691...,14
151,Kentucky,36.788504,-85.020575,42603,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clinton County, Kentucky\n\nElect...",Clinton,KY-CD01,3,[],[## Kentucky House of Representatives District...,[## U.S. House Kentucky District 1\n\n**Level:...,[],1729,134,POLYGON ((967814.0778903841 1585001.8956076186...,14
152,Kentucky,36.772652,-85.025494,42603,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clinton County, Kentucky\n\nElect...",Clinton,KY-CD01,3,[],[## Kentucky House of Representatives District...,[## U.S. House Kentucky District 1\n\n**Level:...,[],1729,134,"POLYGON ((970386.9046696564 1579606.193177357,...",14
155,Ohio,40.950000,-83.780000,45881,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1011882.4111094767 2061936.051944227...,26
157,Ohio,40.829524,-83.813094,45810,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1015883.4663233168 2043975.282718384...,26
158,Ohio,41.106880,-83.803380,45858,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1008147.0832571784 2066508.531540659...,26
159,Ohio,40.823042,-83.669213,45836,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1030103.3039941313 2045794.513858715...,26
160,Ohio,40.959368,-83.878160,45877,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1009218.3351340103 2058253.091215886...,26
162,Ohio,40.884100,-83.838151,45817,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1009683.3803083822 2054676.218693769...,26
164,Ohio,40.836650,-83.632171,45843,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1041198.3691142631 2048756.247918095...,26
165,Ohio,40.930266,-83.480219,43316,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,MULTIPOLYGON (((1044240.2130180825 2062707.118...,26
166,Ohio,41.160429,-83.836722,43516,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,MULTIPOLYGON (((1011724.6058417382 2082789.239...,26
167,Ohio,41.107080,-83.535380,44804,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1030940.7701624109 2077214.278572766...,26
168,Ohio,41.038053,-83.444721,44802,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1045634.8262485652 2075542.157358717...,26
169,Ohio,41.154916,-83.545817,44817,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1032342.991807829 2085303.6796538038...,26
170,Ohio,41.124931,-83.463032,44830,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1037616.4226249112 2085888.760111273...,26
171,Ohio,40.969860,-83.848390,45868,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1008991.9748417786 2059962.636122374...,26
172,Ohio,41.161758,-83.703551,45872,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,MULTIPOLYGON (((1025396.9807741722 2084494.564...,26
173,Ohio,41.146060,-83.641010,45889,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1029154.5963923564 2084947.704883386...,26
174,Ohio,40.977520,-83.491050,45890,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1043840.105760144 2067051.6021043728...,26
175,Ohio,40.834340,-83.656760,45897,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1030187.1388362489 2045805.695034001...,26
176,Ohio,40.901190,-83.615450,45814,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1025614.324663101 2049845.5523236778...,26
177,Ohio,41.004520,-83.793920,45816,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1015573.7208399775 2065180.350525238...,26
178,Ohio,41.026260,-83.649430,45840,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1008399.0362948197 2064584.249346466...,26
179,Ohio,40.879550,-83.735000,45841,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1018310.3237591778 2049719.147747173...,26
180,Ohio,41.138666,-83.875803,45856,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1006763.4226193173 2077157.425013940...,26
181,Ohio,40.897950,-83.538250,45867,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hancock County, Ohio\n\nElection ...",Hancock,OH-CD05,8,[],[## Attorney General of Ohio\n\n**Level:** Sta...,[## Attorney General of Ohio\n\n**Level:** Sta...,[],3293,267,POLYGON ((1042836.6124134143 2061209.247253310...,26
182,Texas,34.296774,-101.884382,79052,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,MULTIPOLYGON (((-538507.5652567688 1266693.258...,67
183,Texas,34.037600,-101.934660,79041,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,POLYGON ((-558461.640664815 1221203.6408534653...,67
184,Texas,34.202555,-102.060361,79064,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,POLYGON ((-557270.7616022541 1242296.721398084...,67
185,Texas,34.171900,-101.745000,79072,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,POLYGON ((-526540.3195608112 1265948.065702747...,67
186,Texas,34.294737,-102.058403,79043,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,POLYGON ((-555279.349279222 1267759.4973497302...,67
187,Texas,33.881340,-101.598810,79250,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,POLYGON ((-509937.0183781471 1229657.914430047...,67
188,Texas,33.983660,-101.993020,79021,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,POLYGON ((-551068.5756636254 1231618.650399775...,67
189,Texas,34.287800,-101.894920,79032,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,POLYGON ((-540454.0791680462 1266811.127153755...,67
190,Texas,33.857810,-101.882280,79311,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,"POLYGON ((-525229.83892836 1211659.9064766727,...",67
191,Texas,33.956080,-101.949240,79073,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Hale County, Texas\n\nElection Da...",Hale,TX-CD19,23,"[## Texas Proposition 1, Establish Special Fun...",[## Attorney General of Texas\n\n**Level:** St...,[## Attorney General of Texas\n\n**Level:** St...,[],6329,596,POLYGON ((-546156.7047345301 1228821.619732102...,67
192,Alabama,33.135830,-85.694478,36276,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clay County, Alabama\n\nElection ...",Clay,AL-CD03,2,[## Alabama Allow Judges to Deny Bail for Cert...,[],[],[],412,52,POLYGON ((956816.1426509152 1175354.1865688218...,4
193,Alabama,33.112564,-85.765995,36256,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clay County, Alabama\n\nElection ...",Clay,AL-CD03,2,[## Alabama Allow Judges to Deny Bail for Cert...,[],[],[],412,52,POLYGON ((949030.7837886392 1166290.6676511853...,4
194,Alabama,33.156300,-86.154560,35082,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clay County, Alabama\n\nElection ...",Clay,AL-CD03,2,[## Alabama Allow Judges to Deny Bail for Cert...,[],[],[],412,52,"POLYGON ((909418.2882089905 1164945.133038352,...",4
195,Alabama,33.118477,-86.163496,35150,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clay County, Alabama\n\nElection ...",Clay,AL-CD03,2,[## Alabama Allow Judges to Deny Bail for Cert...,[],[],[],412,52,POLYGON ((909475.3354828499 1164319.0129441076...,4
196,Alabama,33.256637,-86.037136,35160,"{""success"": true, ""data"": {""districts"": [{""id""...","# Ballot for Clay County, Alabama\n\nElection ...",Clay,AL-CD03,2,[## Alabama Allow Judges to Deny Bail for Cert...,[],[],[],412,52,POLYGON ((925051.0774362169 1189252.3000487196...,4

In [78]:
full_df['ballot_markdown']

intersection_id  state_name
140              California    # Ballot for Sierra County, California\n\nElec...
141              California    # Ballot for Sierra County, California\n\nElec...
142              California    # Ballot for Sierra County, California\n\nElec...
145              Tennessee     # Ballot for Clinton County, Tennessee\n\nElec...
146              Kentucky      # Ballot for Clinton County, Kentucky\n\nElect...
147              Kentucky      # Ballot for Clinton County, Kentucky\n\nElect...
148              Kentucky      # Ballot for Clinton County, Kentucky\n\nElect...
149              Kentucky      # Ballot for Clinton County, Kentucky\n\nElect...
150              Kentucky      # Ballot for Clinton County, Kentucky\n\nElect...
151              Kentucky      # Ballot for Clinton County, Kentucky\n\nElect...
152              Kentucky      # Ballot for Clinton County, Kentucky\n\nElect...
155              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
157              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
158              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
159              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
160              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
162              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
164              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
165              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
166              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
167              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
168              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
169              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
170              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
171              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
172              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
173              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
174              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
175              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
176              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
177              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
178              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
179              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
180              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
181              Ohio          # Ballot for Hancock County, Ohio\n\nElection ...
182              Texas         # Ballot for Hale County, Texas\n\nElection Da...
183              Texas         # Ballot for Hale County, Texas\n\nElection Da...
184              Texas         # Ballot for Hale County, Texas\n\nElection Da...
185              Texas         # Ballot for Hale County, Texas\n\nElection Da...
186              Texas         # Ballot for Hale County, Texas\n\nElection Da...
187              Texas         # Ballot for Hale County, Texas\n\nElection Da...
188              Texas         # Ballot for Hale County, Texas\n\nElection Da...
189              Texas         # Ballot for Hale County, Texas\n\nElection Da...
190              Texas         # Ballot for Hale County, Texas\n\nElection Da...
191              Texas         # Ballot for Hale County, Texas\n\nElection Da...
192              Alabama       # Ballot for Clay County, Alabama\n\nElection ...
193              Alabama       # Ballot for Clay County, Alabama\n\nElection ...
194              Alabama       # Ballot for Clay County, Alabama\n\nElection ...
195              Alabama       # Ballot for Clay County, Alabama\n\nElection ...
196              Alabama       # Ballot for Clay County, Alabama\n\nElection ...
Name: ballot_markdown, dtype: object

In [95]:
full_df.to_csv("data/2025/markdown_2025-22-25.csv")

In [80]:
search_string = '20251104'
filtered_df = full_df[full_df['ballot_markdown'].str.contains(search_string, case=False, na=False)]

print(filtered_df)

Empty DataFrame
Columns: [lat, lng, zip, response, ballot_markdown, county, district, unique_decisions, measures, races, comp_races, non_partisan_races, ballot_length, word_count, geometry, total_options]
Index: []

# Define readability calculator

Function to calculate Flesch-Kincaid Grade Level score for ballot text:
- Strips markdown formatting
- Returns reading grade level (higher score = more complex)

In [96]:
#thanks chagpt 

import re
from textstat import flesch_kincaid_grade
import ast  # to safely evaluate the stringified lists

def get_clean_prose(row):
    # Try to parse races and measures as Python lists
    try:
        races = ast.literal_eval(row['races']) if isinstance(row['races'], str) else []
        measures = ast.literal_eval(row['measures']) if isinstance(row['measures'], str) else []
    except Exception:
        races, measures = [], []
    
    # Combine and clean text
    combined = "\n".join(races + measures)
    # Remove markdown artifacts
    clean_text = re.sub(r'[#+*_`]', '', combined)
    return clean_text.strip()
    

def calculate_fk_from_cleaned(text):
    if not isinstance(text, str) or not re.search(r'[a-zA-Z]', text):
        return 0.0
    try:
        return round(flesch_kincaid_grade(text), 2)
    except Exception:
        return 0.0

In [87]:
#thasnks Obama! (chatgpt)
# def calculate_flesch_kincaid(text):
#     import re
#     from textstat import flesch_kincaid_grade

#     if not isinstance(text, str) or not re.search(r'[a-zA-Z]', text):
#         return 0.0  # or return 0.0 or np.nan
    
#     clean_text = re.sub(r'[#*_`]', '', text)
#     try:
#         return round(flesch_kincaid_grade(clean_text), 2)
#     except Exception:
#         return 0.0

In [81]:
# import re
# from textstat import flesch_kincaid_grade

# def calculate_flesch_kincaid(text):
#     if not isinstance(text, str) or not re.search(r'[a-zA-Z]', text):
#     return None  # or return 0.0 or np.nan
    
# # Remove any markdown formatting
#     clean_text = re.sub(r'[#*_`]', '', text)
    
#     # Calculate Flesch-Kincaid Grade Level
#     grade_level = flesch_kincaid_grade(clean_text)
    
#     return round(grade_level, 2)

In [104]:
#thanks Sam Altman
full_df["ballot_prose"] = full_df.apply(get_clean_prose, axis=1)
full_df["flesch_kincaid_grade"] = full_df["ballot_prose"].apply(calculate_fk_from_cleaned)
full_df["grade_level"] = full_df["flesch_kincaid_grade"].apply(lambda x: f"{x:.1f}")

In [88]:
# Apply the analysis to the DataFramerow['ballot_markdown'])
# full_df['flesch_kincaid_grade'] = full_df.ballot_markdown.progress_apply(calculate_flesch_kincaid)
# full_df['grade_level'] = full_df.flesch_kincaid_grade.apply(lambda x: f'{x:.1f}')

100%|█████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 1910.08it/s]

In [105]:
full_df = full_df[full_df.ballot_markdown.notna()]

In [107]:
full_df['grade_level']

intersection_id  state_name
140              California    0.0
141              California    0.0
142              California    0.0
145              Tennessee     0.0
146              Kentucky      0.0
147              Kentucky      0.0
148              Kentucky      0.0
149              Kentucky      0.0
150              Kentucky      0.0
151              Kentucky      0.0
152              Kentucky      0.0
155              Ohio          0.0
157              Ohio          0.0
158              Ohio          0.0
159              Ohio          0.0
160              Ohio          0.0
162              Ohio          0.0
164              Ohio          0.0
165              Ohio          0.0
166              Ohio          0.0
167              Ohio          0.0
168              Ohio          0.0
169              Ohio          0.0
170              Ohio          0.0
171              Ohio          0.0
172              Ohio          0.0
173              Ohio          0.0
174              Ohio          0.0
175              Ohio          0.0
176              Ohio          0.0
177              Ohio          0.0
178              Ohio          0.0
179              Ohio          0.0
180              Ohio          0.0
181              Ohio          0.0
182              Texas         0.0
183              Texas         0.0
184              Texas         0.0
185              Texas         0.0
186              Texas         0.0
187              Texas         0.0
188              Texas         0.0
189              Texas         0.0
190              Texas         0.0
191              Texas         0.0
192              Alabama       0.0
193              Alabama       0.0
194              Alabama       0.0
195              Alabama       0.0
196              Alabama       0.0
Name: grade_level, dtype: object

In [103]:
# pd.set_option('display.max_colwidth', None)
full_df['measures'].head(1)

intersection_id  state_name
140              California    [## California Proposition 50, Use of Legislative Congressional Redistricting Map Amendment (2025)\n\n**Type:** Ballot Measure\n**Level:** State\n\n---\n\n]
Name: measures, dtype: object

# Calculate complexity scores

Function to compute weighted ballot complexity scores based on multiple factors:
- Technical language and readability (Flesch-Kincaid)
- Ballot length and word count 
- Information density
- Number and complexity of decisions
- Non-partisan contest presence

Each factor is normalized against maximum values across all ballots.

In [28]:
full_df['avg_words_per_decision'] = full_df.word_count / full_df.unique_decisions
full_df['avg_options_per_decision'] = full_df.total_options / full_df.unique_decisions

In [29]:
def calculate_complexity_score(ballot_analysis, max_avg_options_per_decision, max_avg_words_per_decision, max_unique_decisions,
                               max_ballot_length, max_word_count, max_flesch_kincaid_grade):
    # Define weights for each indicator
    weights = {
        'ballot_length': 0.175,
        'word_count': 0.125,
        'avg_words_per_decision': 0.125,
        'unique_decisions': 0.15,
        'non_partisan_contests': 0.075,  # increased by 0.025
        'avg_options_per_decision': 0.125,
        'flesch_kincaid_grade': 0.125
    }    
    # Extract values with nested field access where necessary
    score = (
        (ballot_analysis['ballot_length'] * weights['ballot_length'] / max_ballot_length) +
        (ballot_analysis['word_count'] * weights['word_count'] / max_word_count) +
        (ballot_analysis['avg_words_per_decision'] * weights['avg_words_per_decision'] / max_avg_words_per_decision) +
        (ballot_analysis['avg_options_per_decision'] * weights['avg_options_per_decision'] / max_avg_options_per_decision) +
        (ballot_analysis['unique_decisions'] * weights['unique_decisions'] / max_unique_decisions) +
        (ballot_analysis['flesch_kincaid_grade'] * weights['flesch_kincaid_grade'] / max_flesch_kincaid_grade) +
        (int(not not ballot_analysis['non_partisan_races']) * weights['non_partisan_contests'])
    )
    
    return score

full_df['complexity_score'] = full_df.apply(
    calculate_complexity_score,
    max_ballot_length=full_df.ballot_length.max(),
    max_word_count=full_df.word_count.max(),
    max_avg_words_per_decision=full_df.avg_words_per_decision.max(),
    max_avg_options_per_decision=full_df.avg_options_per_decision.max(),
    max_unique_decisions=full_df.unique_decisions.max(),
    max_flesch_kincaid_grade=full_df.flesch_kincaid_grade.max(),
    axis=1
)

In [30]:
full_df['percentile'] = (full_df.complexity_score.rank() / len(full_df)) * 100

In [31]:
# # Sort and identify highest and lowest complexity ballots

full_df_sorted = full_df.reset_index().drop_duplicates('intersection_id').sort_values('complexity_score', ascending=False)
full_df_sorted['zip_count'] = full_df_sorted.zip.map(dict(full_df_sorted.zip.value_counts()))

highest_complexity = full_df_sorted.head(20000)
lowest_complexity = full_df_sorted.tail(50000)

highest_complexity[['zip', 'county', 'district', 'state_name', 'complexity_score', 'zip_count']].drop_duplicates(['state_name'], keep='first').head(10)
lowest_complexity[['zip', 'county', 'district', 'state_name', 'complexity_score', 'zip_count']].drop_duplicates(['state_name'], keep='last').tail(10)

         zip          county district  state_name  complexity_score  zip_count
23439  77375          Harris  TX-CD02       Texas          0.684667          3
47032  48363         Oakland  MI-CD09    Michigan          0.580760          1
19974  92377  San Bernardino  CA-CD33  California          0.548130          1
5000   97227       Multnomah  OR-CD03      Oregon          0.519702          2
19745  59701      Silver Bow  MT-CD01     Montana          0.495234          6
31262  98283         Whatcom  WA-CD02  Washington          0.473855          2
36233  51544   Pottawattamie  IA-CD04        Iowa          0.462521          4
20105  68110         Douglas  NE-CD02    Nebraska          0.462221          1
15427  85035        Maricopa  AZ-CD03     Arizona          0.461927          2
9243   82431        Big Horn  WY-CD01     Wyoming          0.460147          1

         zip     county district      state_name  complexity_score  zip_count
59198  36528     Mobile  AL-CD01         Alabama          0.189444          1
45347  40177     Hardin  KY-CD02        Kentucky          0.179346          5
58589   6706  New Haven  CT-CD03     Connecticut          0.178495          3
59319   4570    Lincoln  ME-CD01           Maine          0.177988          2
16718   3576       Coos  NH-CD02   New Hampshire          0.177982          2
57270   1944      Essex  MA-CD06   Massachusetts          0.165557          2
19714  29643   Anderson  SC-CD03  South Carolina          0.161379          2
59459  23440   Accomack  VA-CD02        Virginia          0.156886          1
1478   30250    Clayton  GA-CD13         Georgia          0.155076          1
37010  14468     Monroe  NY-CD25        New York          0.148877          1

# Define report generator

Function to create a markdown-formatted ballot complexity report with:
- Overall complexity score
- Decision complexity metrics (unique decisions, options, density)
- Language complexity (Flesch-Kincaid grade level)
- Ballot length statistics
- AI analysis disclaimer

In [32]:
def get_report_markdown(ballot_report, complexity_score):
    # Generate Markdown report with AI disclaimer
    report_md = f"""# Ballot Complexity Report
 
*This report provides an AI-assisted analysis of ballot complexity. Please note that this is a supplementary analysis and not a substitute for official election information.*

**This ballot is more complex than {str(round(ballot_report['percentile']) or 1).replace('100', '99')} percent of U.S. Ballots.**
|                         |                                 |                                          |
|-------------------------|---------------------------------|------------------------------------------|
| **Decision Complexity** | Number of Questions             | {ballot_report['unique_decisions']}      |
|                         | Average Words per Question      | {ballot_report['avg_words_per_decision']:.1f}|
|                         | Average Options per Question    | {ballot_report['avg_options_per_decision']:.1f}|
|                         | Number of Races                 | {len(ballot_report['races'])}|
|                         | Number of Competitive Races     | {len(ballot_report['comp_races'])}|
|                         | Number of Ballot Measures       | {len(ballot_report['measures'])}|
"""
    
    # Conditionally add Non-Partisan Contests
    if ballot_report['non_partisan_races']:
        report_md += "|                         | Non-Partisan Races  | " + ", ".join(ballot_report['non_partisan_races'][:3]) + " |\n"
    
    # Language Complexity Section
    report_md += f"""| **Language Complexity** | [Flesch-Kincaid Grade Level](https://ballotpedia.org/Ballot_measure_readability_scores,_2024#Flesch-Kincaid_Grade_Level)""" + \
    f"""| {ballot_report['flesch_kincaid_grade']}  years of education      |
"""
    # Length Section
    report_md += f"""| **Length**              | Ballot Length                 | {ballot_report['ballot_length']:,} characters       |
|                         | Word Count                     | {ballot_report['word_count']:,}                         |
"""
    return report_md.replace('.0', '')

In [33]:
pop_df = pd.read_csv('data/raw/zip_code_demographics.csv')
population_lookup = dict(zip(pop_df.zip.astype(str), pop_df.population))
state_id_lookup = dict(zip(pop_df.zip.astype(str), pop_df.state_id))

In [34]:
full_df['zip'] = full_df.zip.apply(lambda x: f'{int(x):05}').astype(str)
full_df['population'] = full_df.zip.map(population_lookup)
full_df = full_df.sort_values(by='population', ascending=False)

zip_lookup = full_df.reset_index().rename(columns={
    'county_name': 'county',
    'state_name': 'state',
})[['state', 'county', 'zip', 'population']]

zip_lookup = zip_lookup.sort_values(by='population', ascending=False).drop(columns=['population'])
zip_lookup = zip_lookup.drop_duplicates(['state', 'county', 'zip'])
zip_lookup.head()

zip_lookup.to_csv('data/processed/zip_lookup.csv', index=False)

      state     county    zip
0     Texas     Waller  77494
3     Texas  Fort Bend  77494
1     Texas     Harris  77494
6     Texas     Harris  77449
7  New York     Queens  11368

In [35]:
full_df['full_markdown'] = full_df.apply(
    lambda x: get_report_markdown(x, x.complexity_score), axis=1
) + '\n---\n' + full_df.ballot_markdown

In [36]:
COLUMNS = {
    'unique_decisions': 'unique_questions',
    'avg_words_per_decision': 'avg_words_per_question',
    'avg_options_per_decision': 'avg_options_per_question',
    'races': 'races',
    'measures': 'measures',
    'avg_words_per_decision': 'avg_words_per_question',
    'comp_races': 'competitive_races',
    'non_partisan_races': 'non_partisan_races',
    'flesch_kincaid_grade': 'flesch_kincaid_grade',
    'ballot_length': 'ballot_length',
    'word_count': 'word_count'
}

In [37]:
from collections import defaultdict

full_df['population'] = full_df.zip.map(population_lookup)
full_df['state_id'] = full_df.zip.map(state_id_lookup)
data_lookup = full_df.reset_index().sort_values(by='population', ascending=False).rename(columns={
    'county_name': 'county',
    'state_name': 'state',
    **COLUMNS
})[['state', 'district', 'county', 'zip', 'full_markdown', *COLUMNS.values()]].drop_duplicates(
    ['state', 'district', 'county', 'zip']
)

In [38]:
grouping = ['state', 'district', 'county', 'zip', 'full_markdown']
data_lookup = data_lookup.groupby(grouping).apply(
    lambda df: pd.Series({
        **df.drop(columns=grouping).to_dict(orient='records')[0],
        'measures': len(df.measures.iloc[0]),
        'races': len(df.races.iloc[0]),
        'competitive_races': len(df.competitive_races.iloc[0]),
        'non_partisan_races': df.non_partisan_races.iloc[0],
    })
).reset_index()
data_lookup['district'] = data_lookup.district.str.replace('00', '01')
data_lookup['district'] = data_lookup.district.str.replace('DC-CD98', '')

In [39]:
alert('Data Lookup Complete')

In [40]:
from IPython.display import display, Markdown
display(Markdown(data_lookup.full_markdown.sample(1).iloc[0]))

# Ballot Complexity Report

*This report provides an AI-assisted analysis of ballot complexity. Please note that this is a supplementary analysis and not a substitute for official election information.*

**This ballot is more complex than 75 percent of U.S. Ballots.**
|                         |                                 |                                          |
|-------------------------|---------------------------------|------------------------------------------|
| **Decision Complexity** | Number of Questions             | 20      |
|                         | Average Words per Question      | 26.4|
|                         | Average Options per Question    | 2.5|
|                         | Number of Races                 | 9|
|                         | Number of Competitive Races     | 9|
|                         | Number of Ballot Measures       | 11|
|                         | Non-Partisan Races  | Covelo Fire Protection District At-large, Mendocino Coast Health Care District Board At-large, Mendocino County Board of Education Trustee Area 3 |
| **Language Complexity** | [Flesch-Kincaid Grade Level](https://ballotpedia.org/Ballot_measure_readability_scores,_2024#Flesch-Kincaid_Grade_Level)| 23.5  years of education      |
| **Length**              | Ballot Length                 | 6,904 characters       |
|                         | Word Count                     | 527                         |

---
# Ballot for Mendocino County, California

Election Date: 2024-11-05

## President of the United States

**Level:** Federal
**Branch:** Executive
**Number of Seats:** 1

### Candidates:
- **Kamala D. Harris** (Democratic Party)
    - Running Mate: Tim Walz
    - [More Info](https://ballotpedia.org/Kamala_Harris)

- **Claudia De La Cruz** (Peace and Freedom Party)
    - Running Mate: Karina Garcia
    - [More Info](https://ballotpedia.org/Claudia_De_La_Cruz)

- **Chase Oliver** (Libertarian Party)
    - Running Mate: Mike ter Maat
    - [More Info](https://ballotpedia.org/Chase_Oliver)

- **Robert F. Kennedy Jr.** (American Independent Party)
    - Running Mate: Nicole Shanahan
    - [More Info](https://ballotpedia.org/Robert_F._Kennedy_Jr.)

- **Donald Trump** (Republican Party)
    - Running Mate: J.D. Vance
    - [More Info](https://ballotpedia.org/Donald_Trump)

- **Jill Stein** (Green Party)
    - Running Mate: Butch Ware
    - [More Info](https://ballotpedia.org/Jill_Stein)

---

## U.S. House California District 2

**Level:** Federal
**Branch:** Legislative
**Number of Seats:** 1

### Candidates:
- **Chris Coulombe** (Republican Party)
[More Info](https://ballotpedia.org/Chris_Coulombe)

- **Jared Huffman** (Democratic Party)
[More Info](https://ballotpedia.org/Jared_Huffman)

---

## U.S. Senate California

**Level:** Federal
**Branch:** Legislative
**Number of Seats:** 1

### Candidates:
- **Steve Garvey** (Republican Party)
[More Info](https://ballotpedia.org/Steve_Garvey_(California))

- **Adam Schiff** (Democratic Party)
[More Info](https://ballotpedia.org/Adam_Schiff)

---

## California State Assembly District 2

**Level:** State
**Branch:** Legislative
**Number of Seats:** 1

### Candidates:
- **Chris Rogers** (Democratic Party)
[More Info](https://ballotpedia.org/Chris_Rogers_(California))

- **Michael Greer** (Republican Party)
[More Info](https://ballotpedia.org/Michael_Greer_(California))

---

## Covelo Fire Protection District At-large

**Level:** Local
**Branch:** Legislative
**Number of Seats:** 3

### Candidates:
- **Cindy Nelson** (Nonpartisan)
[More Info](https://ballotpedia.org/Cindy_Nelson_(Covelo_Fire_Protection_District_At-large,_California,_candidate_2024))

- **Leanne G. Durham** (Nonpartisan)
[More Info](https://ballotpedia.org/Leanne_G._Durham_(Covelo_Fire_Protection_District_At-large,_California,_candidate_2024))

- **Edward Wilson** (Nonpartisan)
[More Info](https://ballotpedia.org/Edward_Wilson_(Covelo_Fire_Protection_District_At-large,_California,_candidate_2024))

- **Bryant Earl Hale** (Nonpartisan)
[More Info](https://ballotpedia.org/Bryant_Earl_Hale_(Covelo_Fire_Protection_District_At-large,_California,_candidate_2024))

- **Lindon A. Duke** (Nonpartisan)
[More Info](https://ballotpedia.org/Lindon_A._Duke_(Covelo_Fire_Protection_District_At-large,_California,_candidate_2024))

---

## Mendocino Coast Health Care District Board At-large

**Level:** Local
**Branch:** Legislative
**Number of Seats:** 2

### Candidates:
- **Lynn Finley** (Nonpartisan)
[More Info](https://ballotpedia.org/Lynn_Finley_(Mendocino_Coast_Health_Care_District_Board_At-large,_California,_candidate_2024))

- **Paul Katzeff** (Nonpartisan)
[More Info](https://ballotpedia.org/Paul_Katzeff_(Mendocino_Coast_Health_Care_District_Board_At-large,_California,_candidate_2024))

- **Mikael Blaisdell** (Nonpartisan)
[More Info](https://ballotpedia.org/Mikael_Blaisdell_(Mendocino_Coast_Health_Care_District_Board_At-large,_California,_candidate_2024))

- **Gabriel Quinn Maroney** (Nonpartisan)
[More Info](https://ballotpedia.org/Gabriel_Quinn_Maroney_(Mendocino_Coast_Health_Care_District_Board_At-large,_California,_candidate_2024))

---

## Mendocino County Board of Education Trustee Area 3

**Level:** Local
**Branch:** Legislative
**Number of Seats:** 1

### Candidates:
- **David R. Strock** (Nonpartisan)
[More Info](https://ballotpedia.org/David_R._Strock_(Mendocino_County_Board_of_Education_Trustee_Area_3,_California,_candidate_2024))

- **Michelle Hutchins** (Nonpartisan)
[More Info](https://ballotpedia.org/Michelle_Hutchins_(Mendocino_County_Board_of_Education_Trustee_Area_3,_California,_candidate_2024))

---

## Mendocino Unified School District school board Trustee Area 3

**Level:** Local
**Branch:** Legislative
**Number of Seats:** 1

### Candidates:
- **Jim Gagnon** (Nonpartisan)
[More Info](https://ballotpedia.org/Jim_Gagnon_(Mendocino_Unified_School_District_school_board_Trustee_Area_3,_California,_candidate_2024))

- **Michael Schaeffer** (Nonpartisan)
[More Info](https://ballotpedia.org/Michael_Schaeffer_(Mendocino_Unified_School_District_school_board_Trustee_Area_3,_California,_candidate_2024))

---

## Mendocino-Lake Community College District Governing Board Trustee Area 3

**Level:** Local
**Branch:** Legislative
**Number of Seats:** 1

### Candidates:
- **Gabriel Baca Meza** (Nonpartisan)
[More Info](https://ballotpedia.org/Gabriel_Baca_Meza_(Mendocino-Lake_Community_College_District_Governing_Board_Trustee_Area_3,_California,_candidate_2024))

- **Jay Epstein** (Nonpartisan)
[More Info](https://ballotpedia.org/Jay_Epstein_(Mendocino-Lake_Community_College_District_Governing_Board_Trustee_Area_3,_California,_candidate_2024))

---

## Albion-Little River Fire Protection District, California, Measure S, Parcel Unit Tax Measure (November 2024)

**Type:** Ballot Measure
**Level:** County

---

## California Proposition 2, Public Education Facilities Bond Measure (2024)

**Type:** Ballot Measure
**Level:** State

---

## California Proposition 3, Right to Marry and Repeal Proposition 8 Amendment (2024)

**Type:** Ballot Measure
**Level:** State

---

## California Proposition 32, $18 Minimum Wage Initiative (2024)

**Type:** Ballot Measure
**Level:** State

---

## California Proposition 33, Prohibit State Limitations on Local Rent Control Initiative (2024)

**Type:** Ballot Measure
**Level:** State

---

## California Proposition 34, Require Certain Participants in Medi-Cal Rx Program to Spend 98% of Revenues on Patient Care Initiative (2024)

**Type:** Ballot Measure
**Level:** State

---

## California Proposition 35, Managed Care Organization Tax Authorization Initiative (2024)

**Type:** Ballot Measure
**Level:** State

---

## California Proposition 36, Drug and Theft Crime Penalties and Treatment-Mandated Felonies Initiative (2024)

**Type:** Ballot Measure
**Level:** State

---

## California Proposition 4, Parks, Environment, Energy, and Water Bond Measure (2024)

**Type:** Ballot Measure
**Level:** State

---

## California Proposition 5, Lower Supermajority Requirement to 55% for Local Bond Measures to Fund Housing and Public Infrastructure Amendment (2024)

**Type:** Ballot Measure
**Level:** State

---

## California Proposition 6, Remove Involuntary Servitude as Punishment for Crime Amendment (2024)

**Type:** Ballot Measure
**Level:** State

---

In [41]:
from datetime import date

today = date.today().strftime("%Y%m%d")
data_lookup.to_csv(f'data/archive/data.csv')
data_lookup.to_csv(f'data/archive/data_{today}.csv')
for zip_code in tqdm(data_lookup.zip.unique()):
    data_lookup[data_lookup.zip == zip_code].to_csv(f'data/processed/zip_data_{zip_code}.csv'.lower().replace(' ', ''))

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33698/33698 [00:56<00:00, 591.34it/s]

In [42]:
alert('Files Saved')

# Make maps

# TODO
[x] Percentile rank

[x] mf212mf@gmail.com

[x] bbg415bbg

[x] Percentile Rank for Complexity Score

[ ] Origin tweet -- edit and send out

[x] Fix the top ranking

# TODO

[ ] Surface outliers
[ ] Fix charts
[ ] Add literacy-readbility map
[ ] Add turnout map

In [49]:
alert("plots generated")

# Get NYTimes Data

True

# Perform repairs

Fix old reports without having to reprocess all the data.